// Package artifacts uploads run evidence (screenshots, traces, network and
// console logs) straight to object storage using presigned URLs issued by the
// backend. Evidence never travels through the API.
//
// Stage-1: only the object key layout from contract F is fixed here, so the
// backend and the daemon agree on it before either side is written. The
// uploader itself is implemented in T05.
package artifacts

import (
	"fmt"
	"strings"
	"time"
)

// ObjectKey builds the storage key for one piece of run evidence:
//
//	runs/{YYYY-MM-DD}/{runID}/{testCaseID}/{name}
//
// Every segment is validated rather than escaped. Run and test-case
// identifiers are generated by the platform, but the file name can be derived
// from data the daemon observed on the page under test, so a name containing
// a path separator or a traversal segment is rejected outright instead of
// being allowed to reach outside the run's prefix.
func ObjectKey(day time.Time, runID, testCaseID, name string) (string, error) {
	for label, segment := range map[string]string{
		"runID":      runID,
		"testCaseID": testCaseID,
		"name":       name,
	} {
		if err := validateSegment(label, segment); err != nil {
			return "", err
		}
	}
	return fmt.Sprintf("runs/%s/%s/%s/%s", day.UTC().Format(time.DateOnly), runID, testCaseID, name), nil
}

func validateSegment(label, segment string) error {
	switch {
	case segment == "":
		return fmt.Errorf("%s is empty", label)
	case segment == "." || segment == "..":
		return fmt.Errorf("%s is a path traversal segment", label)
	case strings.ContainsAny(segment, "/\\"):
		return fmt.Errorf("%s contains a path separator: %q", label, segment)
	case strings.ContainsRune(segment, 0):
		return fmt.Errorf("%s contains a NUL byte", label)
	}
	return nil
}
