// Code generated by packages/qa-schema/scripts/generate.mjs. DO NOT EDIT.
// Run `make gen` after changing anything under packages/qa-schema/schemas.

package qaschema

// SchemaIDs lists every contract in this package, sorted. It is generated from
// the files in packages/qa-schema/schemas, so it cannot drift from what is on
// disk the way a hand-written list can.
var SchemaIDs = []string{
	"application-map@1",
	"daemon-envelope@1",
	"execution-result@1",
	"finding@1",
	"test-case@1",
	"test-plan@1",
}

// ContractVersions maps a schema id to its full semantic version. The major
// matches the id suffix; a minor bump means members were added, and a consumer
// built against an older minor must reject what it does not recognise.
var ContractVersions = map[string]string{
	"application-map@1":  "1.0.0",
	"daemon-envelope@1":  "1.1.0",
	"execution-result@1": "1.0.0",
	"finding@1":          "1.0.0",
	"test-case@1":        "1.0.0",
	"test-plan@1":        "1.0.0",
}

// schemaURIs maps a schema id to the $id used by $ref.
var schemaURIs = map[string]string{
	"application-map@1":  "https://qa.local/schema/application-map/1",
	"daemon-envelope@1":  "https://qa.local/schema/daemon-envelope/1",
	"execution-result@1": "https://qa.local/schema/execution-result/1",
	"finding@1":          "https://qa.local/schema/finding/1",
	"test-case@1":        "https://qa.local/schema/test-case/1",
	"test-plan@1":        "https://qa.local/schema/test-plan/1",
}

// schemaFiles maps a schema id to its file inside the embedded schemas/ directory.
var schemaFiles = map[string]string{
	"application-map@1":  "application-map.schema.json",
	"daemon-envelope@1":  "daemon-envelope.schema.json",
	"execution-result@1": "execution-result.schema.json",
	"finding@1":          "finding.schema.json",
	"test-case@1":        "test-case.schema.json",
	"test-plan@1":        "test-plan.schema.json",
}
