// Code generated by packages/qa-schema/scripts/generate.mjs. DO NOT EDIT.
// Run `make gen` after changing anything under packages/qa-schema/schemas.

package qaschema

import "encoding/json"

// AgentCapability is part of the generated contract types.
type AgentCapability struct {
	Name    AgentCapabilityName `json:"name"`
	Version *string             `json:"version,omitempty"`
	Ok      bool                `json:"ok"`
	Error   *string             `json:"error,omitempty"`
}

// AgentCapabilityName is part of the generated contract types.
type AgentCapabilityName string

const (
	AgentCapabilityNameClaude      AgentCapabilityName = "claude"
	AgentCapabilityNameOpencode    AgentCapabilityName = "opencode"
	AgentCapabilityNameAntigravity AgentCapabilityName = "antigravity"
)

// AgentCapabilityNameValues lists every member this build knows about, in schema order.
var AgentCapabilityNameValues = []AgentCapabilityName{AgentCapabilityNameClaude, AgentCapabilityNameOpencode, AgentCapabilityNameAntigravity}

// IsValid reports whether v is a member this build knows about. A value that
// is not must be rejected with an error: quietly treating it as a default is
// how an unimplemented action turns into a passing test.
func (v AgentCapabilityName) IsValid() bool {
	for _, candidate := range AgentCapabilityNameValues {
		if v == candidate {
			return true
		}
	}
	return false
}

// AnalyzedBy is part of the generated contract types.
type AnalyzedBy struct {
	Provider AnalyzedByProvider `json:"provider"`
	Version  *string            `json:"version,omitempty"`
}

// AnalyzedByProvider is part of the generated contract types.
type AnalyzedByProvider string

const (
	AnalyzedByProviderClaude      AnalyzedByProvider = "claude"
	AnalyzedByProviderOpencode    AnalyzedByProvider = "opencode"
	AnalyzedByProviderAntigravity AnalyzedByProvider = "antigravity"
)

// AnalyzedByProviderValues lists every member this build knows about, in schema order.
var AnalyzedByProviderValues = []AnalyzedByProvider{AnalyzedByProviderClaude, AnalyzedByProviderOpencode, AnalyzedByProviderAntigravity}

// IsValid reports whether v is a member this build knows about. A value that
// is not must be rejected with an error: quietly treating it as a default is
// how an unimplemented action turns into a passing test.
func (v AnalyzedByProvider) IsValid() bool {
	for _, candidate := range AnalyzedByProviderValues {
		if v == candidate {
			return true
		}
	}
	return false
}

// ApplicationMap is part of the generated contract types.
type ApplicationMap struct {
	Version          int        `json:"version"`
	BaseURL          string     `json:"baseUrl"`
	ProjectID        *string    `json:"projectId,omitempty"`
	GeneratedAtRunID *RunID     `json:"generatedAtRunId,omitempty"`
	Pages            []Page     `json:"pages"`
	Workflows        []Workflow `json:"workflows"`
}

// Artifact is part of the generated contract types.
type Artifact struct {
	ID   ArtifactID   `json:"id"`
	Kind ArtifactKind `json:"kind"`

	// Key — Object storage key:
	// orgs/{orgId}/runs/{YYYY-MM-DD}/{runId}/{testCaseId}/{filename}, with the
	// {testCaseId} segment omitted for a run-level artifact such as a discovery
	// HAR. That segment is a test case *ref* (TC-001), not the database uuid: the
	// daemon builds the key from the test-case document it was handed and never
	// sees the uuid the backend assigns. What carries the tenant boundary is the
	// orgs/{orgId}/runs/{runId}/ prefix, which is the same prefix the presigned
	// PUT policy is scoped to — so every segment is anchored to start with an
	// alphanumeric, exactly as the artifacts_storage_key_layout CHECK does. A
	// segment that could be ".." would make that prefix bound nothing, and the
	// upload happens before the row is ever inserted: the database is the last
	// gate here, not the first.
	Key         string  `json:"key"`
	ContentType *string `json:"contentType,omitempty"`
	SizeBytes   *int    `json:"sizeBytes,omitempty"`
	Sha256      *string `json:"sha256,omitempty"`
}

// ArtifactID — Run-local handle the daemon makes up so that steps, assertions
// and findings can point at the same evidence before anything has been stored.
// It is NOT the database id.
type ArtifactID = string

// ArtifactKind is part of the generated contract types.
type ArtifactKind string

const (
	ArtifactKindScreenshot ArtifactKind = "screenshot"
	ArtifactKindTrace      ArtifactKind = "trace"
	ArtifactKindVideo      ArtifactKind = "video"
	ArtifactKindNetwork    ArtifactKind = "network"
	ArtifactKindConsole    ArtifactKind = "console"
	ArtifactKindDOM        ArtifactKind = "dom"
	ArtifactKindReport     ArtifactKind = "report"
)

// ArtifactKindValues lists every member this build knows about, in schema order.
var ArtifactKindValues = []ArtifactKind{ArtifactKindScreenshot, ArtifactKindTrace, ArtifactKindVideo, ArtifactKindNetwork, ArtifactKindConsole, ArtifactKindDOM, ArtifactKindReport}

// IsValid reports whether v is a member this build knows about. A value that
// is not must be rejected with an error: quietly treating it as a default is
// how an unimplemented action turns into a passing test.
func (v ArtifactKind) IsValid() bool {
	for _, candidate := range ArtifactKindValues {
		if v == candidate {
			return true
		}
	}
	return false
}

// ArtifactUpload is part of the generated contract types.
type ArtifactUpload struct {
	PresignedPutBase string `json:"presignedPutBase"`

	// KeyPrefix — The daemon may only write below this prefix; the presigned
	// policy enforces the same bound server-side. Segments are anchored the same
	// way as Artifact.key: a prefix whose run segment could be ".." is not a
	// bound.
	KeyPrefix string `json:"keyPrefix"`
	ExpiresAt string `json:"expiresAt"`
}

// Assertion — Go has no sum type, so this struct carries the fields of every
// variant (TargetAssertion, TextAssertion, URLMatchesAssertion,
// ElementCountAssertion, HTTPStatusNotAssertion, NoConsoleErrorAssertion), all
// optional except the discriminator. Switch on it, then read the fields that
// variant defines; the schema is what guarantees they are present. A field
// whose type differs between variants is kept as raw JSON.
type Assertion struct {
	Type      AssertionType   `json:"type"`
	Message   *string         `json:"message,omitempty"`
	Target    *Target         `json:"target,omitempty"`
	TimeoutMs *TimeoutMs      `json:"timeoutMs,omitempty"`
	Value     json.RawMessage `json:"value,omitempty"`

	// Operator — Absent means eq.
	Operator       *ElementCountAssertionOperator `json:"operator,omitempty"`
	IgnorePatterns []string                       `json:"ignorePatterns,omitempty"`
}

// AssertionResult is part of the generated contract types.
type AssertionResult struct {
	Index    int           `json:"index"`
	Type     AssertionType `json:"type"`
	Status   Outcome       `json:"status"`
	Expected *string       `json:"expected,omitempty"`

	// Actual — Observed value, lifted off the page under test. Untrusted text.
	Actual      *string      `json:"actual,omitempty"`
	Message     *string      `json:"message,omitempty"`
	ArtifactIDs []ArtifactID `json:"artifactIds,omitempty"`
}

// AssertionType — Frozen at v1. Same rule as steps: an unknown assertion type
// fails the case, it is never skipped.
type AssertionType string

const (
	AssertionTypeVisible        AssertionType = "visible"
	AssertionTypeHidden         AssertionType = "hidden"
	AssertionTypeTextEquals     AssertionType = "textEquals"
	AssertionTypeTextContains   AssertionType = "textContains"
	AssertionTypeURLMatches     AssertionType = "urlMatches"
	AssertionTypeElementCount   AssertionType = "elementCount"
	AssertionTypeHTTPStatusNot  AssertionType = "httpStatusNot"
	AssertionTypeNoConsoleError AssertionType = "noConsoleError"
)

// AssertionTypeValues lists every member this build knows about, in schema order.
var AssertionTypeValues = []AssertionType{AssertionTypeVisible, AssertionTypeHidden, AssertionTypeTextEquals, AssertionTypeTextContains, AssertionTypeURLMatches, AssertionTypeElementCount, AssertionTypeHTTPStatusNot, AssertionTypeNoConsoleError}

// IsValid reports whether v is a member this build knows about. A value that
// is not must be rejected with an error: quietly treating it as a default is
// how an unimplemented action turns into a passing test.
func (v AssertionType) IsValid() bool {
	for _, candidate := range AssertionTypeValues {
		if v == candidate {
			return true
		}
	}
	return false
}

// CheckStep is part of the generated contract types.
type CheckStep struct {
	Action      string  `json:"action"`
	Description *string `json:"description,omitempty"`
	Target      Target  `json:"target"`

	// Checked — Absent means true.
	Checked   *bool      `json:"checked,omitempty"`
	TimeoutMs *TimeoutMs `json:"timeoutMs,omitempty"`
}

// ClickStep is part of the generated contract types.
type ClickStep struct {
	Action      string           `json:"action"`
	Description *string          `json:"description,omitempty"`
	Target      Target           `json:"target"`
	Button      *ClickStepButton `json:"button,omitempty"`
	ClickCount  *int             `json:"clickCount,omitempty"`
	TimeoutMs   *TimeoutMs       `json:"timeoutMs,omitempty"`
}

// ClickStepButton is part of the generated contract types.
type ClickStepButton string

const (
	ClickStepButtonLeft   ClickStepButton = "left"
	ClickStepButtonRight  ClickStepButton = "right"
	ClickStepButtonMiddle ClickStepButton = "middle"
)

// ClickStepButtonValues lists every member this build knows about, in schema order.
var ClickStepButtonValues = []ClickStepButton{ClickStepButtonLeft, ClickStepButtonRight, ClickStepButtonMiddle}

// IsValid reports whether v is a member this build knows about. A value that
// is not must be rejected with an error: quietly treating it as a default is
// how an unimplemented action turns into a passing test.
func (v ClickStepButton) IsValid() bool {
	for _, candidate := range ClickStepButtonValues {
		if v == candidate {
			return true
		}
	}
	return false
}

// Element is part of the generated contract types.
type Element struct {
	Ref Ref `json:"ref"`

	// Type — Frozen at v1. Anything the crawler cannot classify is other, never a
	// made-up member.
	Type ElementType `json:"type"`

	// Label — Human-visible text lifted off the page under test. Untrusted: it is
	// data for a prompt, never instructions.
	Label *string `json:"label,omitempty"`

	// Locators — Ordered fallback chain. The executor tries them in order and
	// reports which one resolved.
	Locators []Locator `json:"locators"`

	// LastSeenRunID — Which run last observed this element. Elements not seen for
	// N runs are expired rather than silently trusted.
	LastSeenRunID RunID `json:"lastSeenRunId"`
}

// ElementCountAssertion is part of the generated contract types.
type ElementCountAssertion struct {
	Type    string  `json:"type"`
	Message *string `json:"message,omitempty"`
	Target  Target  `json:"target"`
	Value   int     `json:"value"`

	// Operator — Absent means eq.
	Operator  *ElementCountAssertionOperator `json:"operator,omitempty"`
	TimeoutMs *TimeoutMs                     `json:"timeoutMs,omitempty"`
}

// ElementCountAssertionOperator — Absent means eq.
type ElementCountAssertionOperator string

const (
	ElementCountAssertionOperatorEq  ElementCountAssertionOperator = "eq"
	ElementCountAssertionOperatorGte ElementCountAssertionOperator = "gte"
	ElementCountAssertionOperatorLte ElementCountAssertionOperator = "lte"
)

// ElementCountAssertionOperatorValues lists every member this build knows about, in schema order.
var ElementCountAssertionOperatorValues = []ElementCountAssertionOperator{ElementCountAssertionOperatorEq, ElementCountAssertionOperatorGte, ElementCountAssertionOperatorLte}

// IsValid reports whether v is a member this build knows about. A value that
// is not must be rejected with an error: quietly treating it as a default is
// how an unimplemented action turns into a passing test.
func (v ElementCountAssertionOperator) IsValid() bool {
	for _, candidate := range ElementCountAssertionOperatorValues {
		if v == candidate {
			return true
		}
	}
	return false
}

// ElementRef — Reference into application-map@1 elements[].ref.
type ElementRef = string

// ElementType — Frozen at v1. Anything the crawler cannot classify is other,
// never a made-up member.
type ElementType string

const (
	ElementTypeButton   ElementType = "button"
	ElementTypeLink     ElementType = "link"
	ElementTypeInput    ElementType = "input"
	ElementTypeTextarea ElementType = "textarea"
	ElementTypeSelect   ElementType = "select"
	ElementTypeCheckbox ElementType = "checkbox"
	ElementTypeRadio    ElementType = "radio"
	ElementTypeForm     ElementType = "form"
	ElementTypeTable    ElementType = "table"
	ElementTypeRow      ElementType = "row"
	ElementTypeCell     ElementType = "cell"
	ElementTypeText     ElementType = "text"
	ElementTypeImage    ElementType = "image"
	ElementTypeDialog   ElementType = "dialog"
	ElementTypeTab      ElementType = "tab"
	ElementTypeMenu     ElementType = "menu"
	ElementTypeToast    ElementType = "toast"
	ElementTypeOther    ElementType = "other"
)

// ElementTypeValues lists every member this build knows about, in schema order.
var ElementTypeValues = []ElementType{ElementTypeButton, ElementTypeLink, ElementTypeInput, ElementTypeTextarea, ElementTypeSelect, ElementTypeCheckbox, ElementTypeRadio, ElementTypeForm, ElementTypeTable, ElementTypeRow, ElementTypeCell, ElementTypeText, ElementTypeImage, ElementTypeDialog, ElementTypeTab, ElementTypeMenu, ElementTypeToast, ElementTypeOther}

// IsValid reports whether v is a member this build knows about. A value that
// is not must be rejected with an error: quietly treating it as a default is
// how an unimplemented action turns into a passing test.
func (v ElementType) IsValid() bool {
	for _, candidate := range ElementTypeValues {
		if v == candidate {
			return true
		}
	}
	return false
}

// Envelope is part of the generated contract types.
type Envelope struct {
	V     int          `json:"v"`
	Type  EnvelopeType `json:"type"`
	MsgID string       `json:"msgId"`

	// RunID — Required for every run.* frame, null or absent for hello and
	// heartbeat.
	RunID *string `json:"runId,omitempty"`

	// Seq — Monotonic per (connection, runId). The server deduplicates on (runId,
	// seq).
	Seq     int             `json:"seq"`
	Ts      string          `json:"ts"`
	Payload json.RawMessage `json:"payload"`
}

// EnvelopeType is part of the generated contract types.
type EnvelopeType string

const (
	EnvelopeTypeHello     EnvelopeType = "hello"
	EnvelopeTypeHeartbeat EnvelopeType = "heartbeat"
	EnvelopeTypeRunAssign EnvelopeType = "run.assign"
	EnvelopeTypeRunCancel EnvelopeType = "run.cancel"
	EnvelopeTypeRunEvent  EnvelopeType = "run.event"
	EnvelopeTypeRunResult EnvelopeType = "run.result"
)

// EnvelopeTypeValues lists every member this build knows about, in schema order.
var EnvelopeTypeValues = []EnvelopeType{EnvelopeTypeHello, EnvelopeTypeHeartbeat, EnvelopeTypeRunAssign, EnvelopeTypeRunCancel, EnvelopeTypeRunEvent, EnvelopeTypeRunResult}

// IsValid reports whether v is a member this build knows about. A value that
// is not must be rejected with an error: quietly treating it as a default is
// how an unimplemented action turns into a passing test.
func (v EnvelopeType) IsValid() bool {
	for _, candidate := range EnvelopeTypeValues {
		if v == candidate {
			return true
		}
	}
	return false
}

// ExecutionResult is part of the generated contract types.
type ExecutionResult struct {
	Version      int           `json:"version"`
	TestCaseID   string        `json:"testCaseId"`
	RunID        *string       `json:"runId,omitempty"`
	Attempt      *int          `json:"attempt,omitempty"`
	Result       Outcome       `json:"result"`
	FailureClass *FailureClass `json:"failureClass,omitempty"`

	// Message — Executor-authored summary. Never the raw page text.
	Message    *string           `json:"message,omitempty"`
	Steps      []StepResult      `json:"steps"`
	Assertions []AssertionResult `json:"assertions,omitempty"`
	Artifacts  []Artifact        `json:"artifacts"`
	StartedAt  string            `json:"startedAt"`
	EndedAt    string            `json:"endedAt"`
	DurationMs *int              `json:"durationMs,omitempty"`
}

// FailureClass — Frozen at v1. UNKNOWN is the honest answer; a consumer that
// meets a class it does not recognise must fail loudly rather than bucket it
// as UNKNOWN.
type FailureClass string

const (
	FailureClassPRODUCTBUG          FailureClass = "PRODUCT_BUG"
	FailureClassTESTBUG             FailureClass = "TEST_BUG"
	FailureClassENVIRONMENTERROR    FailureClass = "ENVIRONMENT_ERROR"
	FailureClassNETWORKERROR        FailureClass = "NETWORK_ERROR"
	FailureClassAUTHENTICATIONERROR FailureClass = "AUTHENTICATION_ERROR"
	FailureClassTIMEOUT             FailureClass = "TIMEOUT"
	FailureClassUNKNOWN             FailureClass = "UNKNOWN"
)

// FailureClassValues lists every member this build knows about, in schema order.
var FailureClassValues = []FailureClass{FailureClassPRODUCTBUG, FailureClassTESTBUG, FailureClassENVIRONMENTERROR, FailureClassNETWORKERROR, FailureClassAUTHENTICATIONERROR, FailureClassTIMEOUT, FailureClassUNKNOWN}

// IsValid reports whether v is a member this build knows about. A value that
// is not must be rejected with an error: quietly treating it as a default is
// how an unimplemented action turns into a passing test.
func (v FailureClass) IsValid() bool {
	for _, candidate := range FailureClassValues {
		if v == candidate {
			return true
		}
	}
	return false
}

// FillStep is part of the generated contract types.
type FillStep struct {
	Action      string     `json:"action"`
	Description *string    `json:"description,omitempty"`
	Target      Target     `json:"target"`
	Value       string     `json:"value"`
	TimeoutMs   *TimeoutMs `json:"timeoutMs,omitempty"`
}

// Finding is part of the generated contract types.
type Finding struct {
	Version     int     `json:"version"`
	TestCaseID  string  `json:"testCaseId"`
	ExecutionID *string `json:"executionId,omitempty"`

	// StepIndex — Which step the analyst blames. null when the failure is not
	// attributable to a single step.
	StepIndex    *int         `json:"stepIndex,omitempty"`
	FailureClass FailureClass `json:"failureClass"`
	Summary      *string      `json:"summary,omitempty"`
	RootCause    string       `json:"rootCause"`

	// Confidence — The analyst's own confidence. Shown to the user; never used to
	// silently drop a finding.
	Confidence float64 `json:"confidence"`

	// Evidence — Artifact ids from the execution result. A finding with no
	// evidence is a guess, so at least one is required.
	Evidence     []ArtifactID `json:"evidence"`
	SuggestedFix *string      `json:"suggestedFix,omitempty"`
	AnalyzedBy   *AnalyzedBy  `json:"analyzedBy,omitempty"`
}

// HeartbeatPayload is part of the generated contract types.
type HeartbeatPayload struct {
	UptimeSec  int      `json:"uptimeSec"`
	ActiveRuns []string `json:"activeRuns,omitempty"`
}

// HelloPayload is part of the generated contract types.
type HelloPayload struct {
	RuntimeID string                     `json:"runtimeId"`
	Version   string                     `json:"version"`
	Hostname  *string                    `json:"hostname,omitempty"`
	OS        *HelloPayloadOS            `json:"os,omitempty"`
	Browsers  []HelloPayloadBrowsersItem `json:"browsers"`
	Agents    []AgentCapability          `json:"agents"`
}

// HelloPayloadBrowsersItem is part of the generated contract types.
type HelloPayloadBrowsersItem string

const (
	HelloPayloadBrowsersItemChromium HelloPayloadBrowsersItem = "chromium"
	HelloPayloadBrowsersItemFirefox  HelloPayloadBrowsersItem = "firefox"
	HelloPayloadBrowsersItemWebkit   HelloPayloadBrowsersItem = "webkit"
)

// HelloPayloadBrowsersItemValues lists every member this build knows about, in schema order.
var HelloPayloadBrowsersItemValues = []HelloPayloadBrowsersItem{HelloPayloadBrowsersItemChromium, HelloPayloadBrowsersItemFirefox, HelloPayloadBrowsersItemWebkit}

// IsValid reports whether v is a member this build knows about. A value that
// is not must be rejected with an error: quietly treating it as a default is
// how an unimplemented action turns into a passing test.
func (v HelloPayloadBrowsersItem) IsValid() bool {
	for _, candidate := range HelloPayloadBrowsersItemValues {
		if v == candidate {
			return true
		}
	}
	return false
}

// HelloPayloadOS is part of the generated contract types.
type HelloPayloadOS string

const (
	HelloPayloadOSLinux   HelloPayloadOS = "linux"
	HelloPayloadOSDarwin  HelloPayloadOS = "darwin"
	HelloPayloadOSWindows HelloPayloadOS = "windows"
)

// HelloPayloadOSValues lists every member this build knows about, in schema order.
var HelloPayloadOSValues = []HelloPayloadOS{HelloPayloadOSLinux, HelloPayloadOSDarwin, HelloPayloadOSWindows}

// IsValid reports whether v is a member this build knows about. A value that
// is not must be rejected with an error: quietly treating it as a default is
// how an unimplemented action turns into a passing test.
func (v HelloPayloadOS) IsValid() bool {
	for _, candidate := range HelloPayloadOSValues {
		if v == candidate {
			return true
		}
	}
	return false
}

// HoverStep is part of the generated contract types.
type HoverStep struct {
	Action      string     `json:"action"`
	Description *string    `json:"description,omitempty"`
	Target      Target     `json:"target"`
	TimeoutMs   *TimeoutMs `json:"timeoutMs,omitempty"`
}

// HTTPStatusNotAssertion is part of the generated contract types.
type HTTPStatusNotAssertion struct {
	Type    string  `json:"type"`
	Message *string `json:"message,omitempty"`
	Value   int     `json:"value"`
}

// Locator is part of the generated contract types.
type Locator struct {
	Kind  LocatorKind `json:"kind"`
	Value string      `json:"value"`

	// Name — Accessible name. Required when kind is role.
	Name *string `json:"name,omitempty"`
}

// LocatorKind is part of the generated contract types.
type LocatorKind string

const (
	LocatorKindTestID      LocatorKind = "testId"
	LocatorKindRole        LocatorKind = "role"
	LocatorKindLabel       LocatorKind = "label"
	LocatorKindPlaceholder LocatorKind = "placeholder"
	LocatorKindText        LocatorKind = "text"
	LocatorKindAltText     LocatorKind = "altText"
	LocatorKindTitle       LocatorKind = "title"
	LocatorKindCss         LocatorKind = "css"
)

// LocatorKindValues lists every member this build knows about, in schema order.
var LocatorKindValues = []LocatorKind{LocatorKindTestID, LocatorKindRole, LocatorKindLabel, LocatorKindPlaceholder, LocatorKindText, LocatorKindAltText, LocatorKindTitle, LocatorKindCss}

// IsValid reports whether v is a member this build knows about. A value that
// is not must be rejected with an error: quietly treating it as a default is
// how an unimplemented action turns into a passing test.
func (v LocatorKind) IsValid() bool {
	for _, candidate := range LocatorKindValues {
		if v == candidate {
			return true
		}
	}
	return false
}

// NavigateStep is part of the generated contract types.
type NavigateStep struct {
	Action      string  `json:"action"`
	Description *string `json:"description,omitempty"`

	// URL — Absolute http(s) URL or a path relative to the project baseUrl.
	URL       string                 `json:"url"`
	WaitUntil *NavigateStepWaitUntil `json:"waitUntil,omitempty"`
	TimeoutMs *TimeoutMs             `json:"timeoutMs,omitempty"`
}

// NavigateStepWaitUntil is part of the generated contract types.
type NavigateStepWaitUntil string

const (
	NavigateStepWaitUntilLoad             NavigateStepWaitUntil = "load"
	NavigateStepWaitUntilDomcontentloaded NavigateStepWaitUntil = "domcontentloaded"
	NavigateStepWaitUntilNetworkidle      NavigateStepWaitUntil = "networkidle"
)

// NavigateStepWaitUntilValues lists every member this build knows about, in schema order.
var NavigateStepWaitUntilValues = []NavigateStepWaitUntil{NavigateStepWaitUntilLoad, NavigateStepWaitUntilDomcontentloaded, NavigateStepWaitUntilNetworkidle}

// IsValid reports whether v is a member this build knows about. A value that
// is not must be rejected with an error: quietly treating it as a default is
// how an unimplemented action turns into a passing test.
func (v NavigateStepWaitUntil) IsValid() bool {
	for _, candidate := range NavigateStepWaitUntilValues {
		if v == candidate {
			return true
		}
	}
	return false
}

// NoConsoleErrorAssertion is part of the generated contract types.
type NoConsoleErrorAssertion struct {
	Type           string   `json:"type"`
	Message        *string  `json:"message,omitempty"`
	IgnorePatterns []string `json:"ignorePatterns,omitempty"`
}

// Outcome — fail is the application disagreeing with an assertion; error is
// the harness not getting far enough to have an opinion.
type Outcome string

const (
	OutcomePass    Outcome = "pass"
	OutcomeFail    Outcome = "fail"
	OutcomeSkipped Outcome = "skipped"
	OutcomeError   Outcome = "error"
)

// OutcomeValues lists every member this build knows about, in schema order.
var OutcomeValues = []Outcome{OutcomePass, OutcomeFail, OutcomeSkipped, OutcomeError}

// IsValid reports whether v is a member this build knows about. A value that
// is not must be rejected with an error: quietly treating it as a default is
// how an unimplemented action turns into a passing test.
func (v Outcome) IsValid() bool {
	for _, candidate := range OutcomeValues {
		if v == candidate {
			return true
		}
	}
	return false
}

// Page is part of the generated contract types.
type Page struct {
	ID Ref `json:"id"`

	// Path — Path relative to baseUrl, always starting with /.
	Path  string `json:"path"`
	Title string `json:"title"`

	// AuthRequired — Absent means false.
	AuthRequired  *bool     `json:"authRequired,omitempty"`
	Description   *string   `json:"description,omitempty"`
	LastSeenRunID *RunID    `json:"lastSeenRunId,omitempty"`
	Elements      []Element `json:"elements"`
}

// Precondition — A named fixture the runtime knows how to establish, e.g.
// fixture:logged_in_as_admin. Free prose is rejected on purpose: a
// precondition an executor cannot establish is not a precondition, and this is
// also what keeps target-app credentials out of AI-authored JSON.
type Precondition = string

// PressStep is part of the generated contract types.
type PressStep struct {
	Action      string  `json:"action"`
	Description *string `json:"description,omitempty"`
	Target      *Target `json:"target,omitempty"`

	// Key — Playwright key syntax, e.g. Enter or Control+A.
	Key       string     `json:"key"`
	TimeoutMs *TimeoutMs `json:"timeoutMs,omitempty"`
}

// Ref is part of the generated contract types.
type Ref = string

// RunAssignPayload is part of the generated contract types.
type RunAssignPayload struct {
	RunID          string                 `json:"runId"`
	Mode           RunAssignPayloadMode   `json:"mode"`
	ProjectID      string                 `json:"projectId"`
	BaseURL        string                 `json:"baseUrl"`
	Agent          *RunAssignPayloadAgent `json:"agent,omitempty"`
	AppMap         *ApplicationMap        `json:"appMap,omitempty"`
	TestCases      []TestCase             `json:"testCases,omitempty"`
	ArtifactUpload ArtifactUpload         `json:"artifactUpload"`
}

// RunAssignPayloadAgent is part of the generated contract types.
type RunAssignPayloadAgent string

const (
	RunAssignPayloadAgentClaude      RunAssignPayloadAgent = "claude"
	RunAssignPayloadAgentOpencode    RunAssignPayloadAgent = "opencode"
	RunAssignPayloadAgentAntigravity RunAssignPayloadAgent = "antigravity"
)

// RunAssignPayloadAgentValues lists every member this build knows about, in schema order.
var RunAssignPayloadAgentValues = []RunAssignPayloadAgent{RunAssignPayloadAgentClaude, RunAssignPayloadAgentOpencode, RunAssignPayloadAgentAntigravity}

// IsValid reports whether v is a member this build knows about. A value that
// is not must be rejected with an error: quietly treating it as a default is
// how an unimplemented action turns into a passing test.
func (v RunAssignPayloadAgent) IsValid() bool {
	for _, candidate := range RunAssignPayloadAgentValues {
		if v == candidate {
			return true
		}
	}
	return false
}

// RunAssignPayloadMode is part of the generated contract types.
type RunAssignPayloadMode string

const (
	RunAssignPayloadModeDiscover RunAssignPayloadMode = "discover"
	RunAssignPayloadModePlan     RunAssignPayloadMode = "plan"
	RunAssignPayloadModeExecute  RunAssignPayloadMode = "execute"
	RunAssignPayloadModeFull     RunAssignPayloadMode = "full"
)

// RunAssignPayloadModeValues lists every member this build knows about, in schema order.
var RunAssignPayloadModeValues = []RunAssignPayloadMode{RunAssignPayloadModeDiscover, RunAssignPayloadModePlan, RunAssignPayloadModeExecute, RunAssignPayloadModeFull}

// IsValid reports whether v is a member this build knows about. A value that
// is not must be rejected with an error: quietly treating it as a default is
// how an unimplemented action turns into a passing test.
func (v RunAssignPayloadMode) IsValid() bool {
	for _, candidate := range RunAssignPayloadModeValues {
		if v == candidate {
			return true
		}
	}
	return false
}

// RunCancelPayload is part of the generated contract types.
type RunCancelPayload struct {
	Reason  RunCancelPayloadReason `json:"reason"`
	Message *string                `json:"message,omitempty"`
}

// RunCancelPayloadReason is part of the generated contract types.
type RunCancelPayloadReason string

const (
	RunCancelPayloadReasonUserRequested RunCancelPayloadReason = "user_requested"
	RunCancelPayloadReasonTimeout       RunCancelPayloadReason = "timeout"
	RunCancelPayloadReasonSuperseded    RunCancelPayloadReason = "superseded"
	RunCancelPayloadReasonShutdown      RunCancelPayloadReason = "shutdown"
)

// RunCancelPayloadReasonValues lists every member this build knows about, in schema order.
var RunCancelPayloadReasonValues = []RunCancelPayloadReason{RunCancelPayloadReasonUserRequested, RunCancelPayloadReasonTimeout, RunCancelPayloadReasonSuperseded, RunCancelPayloadReasonShutdown}

// IsValid reports whether v is a member this build knows about. A value that
// is not must be rejected with an error: quietly treating it as a default is
// how an unimplemented action turns into a passing test.
func (v RunCancelPayloadReason) IsValid() bool {
	for _, candidate := range RunCancelPayloadReasonValues {
		if v == candidate {
			return true
		}
	}
	return false
}

// RunError is part of the generated contract types.
type RunError struct {
	Code    RunErrorCode `json:"code"`
	Message string       `json:"message"`
}

// RunErrorCode is part of the generated contract types.
type RunErrorCode string

const (
	RunErrorCodeAgentOutputInvalid   RunErrorCode = "agent_output_invalid"
	RunErrorCodeAgentNotAvailable    RunErrorCode = "agent_not_available"
	RunErrorCodeBrowserLaunchFailed  RunErrorCode = "browser_launch_failed"
	RunErrorCodeTargetUnreachable    RunErrorCode = "target_unreachable"
	RunErrorCodeArtifactUploadFailed RunErrorCode = "artifact_upload_failed"
	RunErrorCodeInternal             RunErrorCode = "internal"
)

// RunErrorCodeValues lists every member this build knows about, in schema order.
var RunErrorCodeValues = []RunErrorCode{RunErrorCodeAgentOutputInvalid, RunErrorCodeAgentNotAvailable, RunErrorCodeBrowserLaunchFailed, RunErrorCodeTargetUnreachable, RunErrorCodeArtifactUploadFailed, RunErrorCodeInternal}

// IsValid reports whether v is a member this build knows about. A value that
// is not must be rejected with an error: quietly treating it as a default is
// how an unimplemented action turns into a passing test.
func (v RunErrorCode) IsValid() bool {
	for _, candidate := range RunErrorCodeValues {
		if v == candidate {
			return true
		}
	}
	return false
}

// RunEventPayload is part of the generated contract types.
type RunEventPayload struct {
	Phase RunEventPayloadPhase `json:"phase"`
	Level RunEventPayloadLevel `json:"level"`

	// Code — Machine-readable event code, e.g. page_discovered or
	// agent_output_invalid. The UI switches on this, never on message.
	Code       string  `json:"code"`
	Message    string  `json:"message"`
	TestCaseID *string `json:"testCaseId,omitempty"`

	// Data — Free-form structured detail for this code. Anything lifted off the
	// page under test lands here as data, never as message.
	Data map[string]any `json:"data,omitempty"`
}

// RunEventPayloadLevel is part of the generated contract types.
type RunEventPayloadLevel string

const (
	RunEventPayloadLevelDebug RunEventPayloadLevel = "debug"
	RunEventPayloadLevelInfo  RunEventPayloadLevel = "info"
	RunEventPayloadLevelWarn  RunEventPayloadLevel = "warn"
	RunEventPayloadLevelError RunEventPayloadLevel = "error"
)

// RunEventPayloadLevelValues lists every member this build knows about, in schema order.
var RunEventPayloadLevelValues = []RunEventPayloadLevel{RunEventPayloadLevelDebug, RunEventPayloadLevelInfo, RunEventPayloadLevelWarn, RunEventPayloadLevelError}

// IsValid reports whether v is a member this build knows about. A value that
// is not must be rejected with an error: quietly treating it as a default is
// how an unimplemented action turns into a passing test.
func (v RunEventPayloadLevel) IsValid() bool {
	for _, candidate := range RunEventPayloadLevelValues {
		if v == candidate {
			return true
		}
	}
	return false
}

// RunEventPayloadPhase is part of the generated contract types.
type RunEventPayloadPhase string

const (
	RunEventPayloadPhaseDiscover RunEventPayloadPhase = "discover"
	RunEventPayloadPhasePlan     RunEventPayloadPhase = "plan"
	RunEventPayloadPhaseExecute  RunEventPayloadPhase = "execute"
	RunEventPayloadPhaseAnalyze  RunEventPayloadPhase = "analyze"
	RunEventPayloadPhaseReport   RunEventPayloadPhase = "report"
)

// RunEventPayloadPhaseValues lists every member this build knows about, in schema order.
var RunEventPayloadPhaseValues = []RunEventPayloadPhase{RunEventPayloadPhaseDiscover, RunEventPayloadPhasePlan, RunEventPayloadPhaseExecute, RunEventPayloadPhaseAnalyze, RunEventPayloadPhaseReport}

// IsValid reports whether v is a member this build knows about. A value that
// is not must be rejected with an error: quietly treating it as a default is
// how an unimplemented action turns into a passing test.
func (v RunEventPayloadPhase) IsValid() bool {
	for _, candidate := range RunEventPayloadPhaseValues {
		if v == candidate {
			return true
		}
	}
	return false
}

// RunID is part of the generated contract types.
type RunID = string

// RunResultPayload is part of the generated contract types.
type RunResultPayload struct {
	Status     RunResultPayloadStatus `json:"status"`
	Error      *RunError              `json:"error,omitempty"`
	AppMap     *ApplicationMap        `json:"appMap,omitempty"`
	TestPlan   *TestPlan              `json:"testPlan,omitempty"`
	Executions []ExecutionResult      `json:"executions,omitempty"`
	Findings   []Finding              `json:"findings,omitempty"`
	Artifacts  []Artifact             `json:"artifacts,omitempty"`
}

// RunResultPayloadStatus is part of the generated contract types.
type RunResultPayloadStatus string

const (
	RunResultPayloadStatusCompleted RunResultPayloadStatus = "completed"
	RunResultPayloadStatusFailed    RunResultPayloadStatus = "failed"
	RunResultPayloadStatusCancelled RunResultPayloadStatus = "cancelled"
)

// RunResultPayloadStatusValues lists every member this build knows about, in schema order.
var RunResultPayloadStatusValues = []RunResultPayloadStatus{RunResultPayloadStatusCompleted, RunResultPayloadStatusFailed, RunResultPayloadStatusCancelled}

// IsValid reports whether v is a member this build knows about. A value that
// is not must be rejected with an error: quietly treating it as a default is
// how an unimplemented action turns into a passing test.
func (v RunResultPayloadStatus) IsValid() bool {
	for _, candidate := range RunResultPayloadStatusValues {
		if v == candidate {
			return true
		}
	}
	return false
}

// ScreenshotStep is part of the generated contract types.
type ScreenshotStep struct {
	Action      string     `json:"action"`
	Description *string    `json:"description,omitempty"`
	Name        *string    `json:"name,omitempty"`
	FullPage    *bool      `json:"fullPage,omitempty"`
	TimeoutMs   *TimeoutMs `json:"timeoutMs,omitempty"`
}

// SelectStep is part of the generated contract types.
type SelectStep struct {
	Action      string        `json:"action"`
	Description *string       `json:"description,omitempty"`
	Target      Target        `json:"target"`
	Value       string        `json:"value"`
	By          *SelectStepBy `json:"by,omitempty"`
	TimeoutMs   *TimeoutMs    `json:"timeoutMs,omitempty"`
}

// SelectStepBy is part of the generated contract types.
type SelectStepBy string

const (
	SelectStepByValue SelectStepBy = "value"
	SelectStepByLabel SelectStepBy = "label"
	SelectStepByIndex SelectStepBy = "index"
)

// SelectStepByValues lists every member this build knows about, in schema order.
var SelectStepByValues = []SelectStepBy{SelectStepByValue, SelectStepByLabel, SelectStepByIndex}

// IsValid reports whether v is a member this build knows about. A value that
// is not must be rejected with an error: quietly treating it as a default is
// how an unimplemented action turns into a passing test.
func (v SelectStepBy) IsValid() bool {
	for _, candidate := range SelectStepByValues {
		if v == candidate {
			return true
		}
	}
	return false
}

// Step — Go has no sum type, so this struct carries the fields of every
// variant (NavigateStep, ClickStep, FillStep, SelectStep, CheckStep,
// HoverStep, PressStep, WaitForStep, ScreenshotStep), all optional except the
// discriminator. Switch on it, then read the fields that variant defines; the
// schema is what guarantees they are present.
type Step struct {
	Action      StepAction `json:"action"`
	Description *string    `json:"description,omitempty"`

	// URL — Absolute http(s) URL or a path relative to the project baseUrl.
	URL        *string                `json:"url,omitempty"`
	WaitUntil  *NavigateStepWaitUntil `json:"waitUntil,omitempty"`
	TimeoutMs  *TimeoutMs             `json:"timeoutMs,omitempty"`
	Target     *Target                `json:"target,omitempty"`
	Button     *ClickStepButton       `json:"button,omitempty"`
	ClickCount *int                   `json:"clickCount,omitempty"`
	Value      *string                `json:"value,omitempty"`
	By         *SelectStepBy          `json:"by,omitempty"`

	// Checked — Absent means true.
	Checked *bool `json:"checked,omitempty"`

	// Key — Playwright key syntax, e.g. Enter or Control+A.
	Key      *string           `json:"key,omitempty"`
	State    *WaitForStepState `json:"state,omitempty"`
	Name     *string           `json:"name,omitempty"`
	FullPage *bool             `json:"fullPage,omitempty"`
}

// StepAction — Frozen at v1. Adding a member is a new minor version; an
// executor that meets an action it does not know must fail the step, never
// skip it.
type StepAction string

const (
	StepActionNavigate   StepAction = "navigate"
	StepActionClick      StepAction = "click"
	StepActionFill       StepAction = "fill"
	StepActionSelect     StepAction = "select"
	StepActionCheck      StepAction = "check"
	StepActionHover      StepAction = "hover"
	StepActionPress      StepAction = "press"
	StepActionWaitFor    StepAction = "waitFor"
	StepActionScreenshot StepAction = "screenshot"
)

// StepActionValues lists every member this build knows about, in schema order.
var StepActionValues = []StepAction{StepActionNavigate, StepActionClick, StepActionFill, StepActionSelect, StepActionCheck, StepActionHover, StepActionPress, StepActionWaitFor, StepActionScreenshot}

// IsValid reports whether v is a member this build knows about. A value that
// is not must be rejected with an error: quietly treating it as a default is
// how an unimplemented action turns into a passing test.
func (v StepAction) IsValid() bool {
	for _, candidate := range StepActionValues {
		if v == candidate {
			return true
		}
	}
	return false
}

// StepResult is part of the generated contract types.
type StepResult struct {
	// Index — Position in the test case steps array.
	Index  int        `json:"index"`
	Action StepAction `json:"action"`
	Status Outcome    `json:"status"`

	// ResolvedLocator — Which locator in the element fallback chain actually
	// matched.
	ResolvedLocator *string `json:"resolvedLocator,omitempty"`

	// UnstableTarget — True when the step used a raw locator instead of an
	// application-map ref.
	UnstableTarget *bool        `json:"unstableTarget,omitempty"`
	Message        *string      `json:"message,omitempty"`
	StartedAt      *string      `json:"startedAt,omitempty"`
	EndedAt        *string      `json:"endedAt,omitempty"`
	DurationMs     *int         `json:"durationMs,omitempty"`
	ArtifactIDs    []ArtifactID `json:"artifactIds,omitempty"`
}

// Target — How a step or assertion points at an element. Go has no sum type,
// so this struct carries the fields of every variant (TargetByRef,
// TargetByLocator), all optional except the discriminator. Switch on it, then
// read the fields that variant defines; the schema is what guarantees they are
// present.
type Target struct {
	Ref      *ElementRef `json:"ref,omitempty"`
	Locator  *string     `json:"locator,omitempty"`
	Unstable *bool       `json:"unstable,omitempty"`
}

// TargetAssertion is part of the generated contract types.
type TargetAssertion struct {
	Type      TargetAssertionType `json:"type"`
	Message   *string             `json:"message,omitempty"`
	Target    Target              `json:"target"`
	TimeoutMs *TimeoutMs          `json:"timeoutMs,omitempty"`
}

// TargetAssertionType is part of the generated contract types.
type TargetAssertionType string

const (
	TargetAssertionTypeVisible TargetAssertionType = "visible"
	TargetAssertionTypeHidden  TargetAssertionType = "hidden"
)

// TargetAssertionTypeValues lists every member this build knows about, in schema order.
var TargetAssertionTypeValues = []TargetAssertionType{TargetAssertionTypeVisible, TargetAssertionTypeHidden}

// IsValid reports whether v is a member this build knows about. A value that
// is not must be rejected with an error: quietly treating it as a default is
// how an unimplemented action turns into a passing test.
func (v TargetAssertionType) IsValid() bool {
	for _, candidate := range TargetAssertionTypeValues {
		if v == candidate {
			return true
		}
	}
	return false
}

// TargetByLocator — Escape hatch for a selector the planner invented. unstable
// must be true: a run that used one is reportable as non-deterministic rather
// than quietly equivalent.
type TargetByLocator struct {
	Locator  string `json:"locator"`
	Unstable bool   `json:"unstable"`
}

// TargetByRef — The contract form: point at an element the application map
// already named.
type TargetByRef struct {
	Ref ElementRef `json:"ref"`
}

// TestCase is part of the generated contract types.
type TestCase struct {
	// Version — Which contract wrote this case. A test case outlives the run that
	// produced it — it is stored as jsonb and replayed as regression — so the row
	// has to say what it is without the reader guessing from its shape.
	Version int `json:"version"`

	// ID — Stable identifier the planner assigns, e.g. TC-001. Reused across runs
	// so results can be compared run over run.
	ID          string           `json:"id"`
	Name        string           `json:"name"`
	Description *string          `json:"description,omitempty"`
	Priority    TestCasePriority `json:"priority"`
	Category    TestCaseCategory `json:"category"`

	// Status — Review state. Absent means draft; only an approved case is reused
	// as regression.
	Status        *TestCaseStatus `json:"status,omitempty"`
	Preconditions []Precondition  `json:"preconditions,omitempty"`
	Tags          []string        `json:"tags,omitempty"`
	Steps         []Step          `json:"steps"`
	Assertions    []Assertion     `json:"assertions"`
}

// TestCaseCategory is part of the generated contract types.
type TestCaseCategory string

const (
	TestCaseCategoryFunctional    TestCaseCategory = "functional"
	TestCaseCategoryValidation    TestCaseCategory = "validation"
	TestCaseCategoryNavigation    TestCaseCategory = "navigation"
	TestCaseCategoryUIBehavior    TestCaseCategory = "ui_behavior"
	TestCaseCategoryErrorHandling TestCaseCategory = "error_handling"
)

// TestCaseCategoryValues lists every member this build knows about, in schema order.
var TestCaseCategoryValues = []TestCaseCategory{TestCaseCategoryFunctional, TestCaseCategoryValidation, TestCaseCategoryNavigation, TestCaseCategoryUIBehavior, TestCaseCategoryErrorHandling}

// IsValid reports whether v is a member this build knows about. A value that
// is not must be rejected with an error: quietly treating it as a default is
// how an unimplemented action turns into a passing test.
func (v TestCaseCategory) IsValid() bool {
	for _, candidate := range TestCaseCategoryValues {
		if v == candidate {
			return true
		}
	}
	return false
}

// TestCasePriority is part of the generated contract types.
type TestCasePriority string

const (
	TestCasePriorityCritical TestCasePriority = "critical"
	TestCasePriorityHigh     TestCasePriority = "high"
	TestCasePriorityMedium   TestCasePriority = "medium"
	TestCasePriorityLow      TestCasePriority = "low"
)

// TestCasePriorityValues lists every member this build knows about, in schema order.
var TestCasePriorityValues = []TestCasePriority{TestCasePriorityCritical, TestCasePriorityHigh, TestCasePriorityMedium, TestCasePriorityLow}

// IsValid reports whether v is a member this build knows about. A value that
// is not must be rejected with an error: quietly treating it as a default is
// how an unimplemented action turns into a passing test.
func (v TestCasePriority) IsValid() bool {
	for _, candidate := range TestCasePriorityValues {
		if v == candidate {
			return true
		}
	}
	return false
}

// TestCaseStatus — Review state. Absent means draft; only an approved case is
// reused as regression.
type TestCaseStatus string

const (
	TestCaseStatusDraft    TestCaseStatus = "draft"
	TestCaseStatusApproved TestCaseStatus = "approved"
	TestCaseStatusArchived TestCaseStatus = "archived"
)

// TestCaseStatusValues lists every member this build knows about, in schema order.
var TestCaseStatusValues = []TestCaseStatus{TestCaseStatusDraft, TestCaseStatusApproved, TestCaseStatusArchived}

// IsValid reports whether v is a member this build knows about. A value that
// is not must be rejected with an error: quietly treating it as a default is
// how an unimplemented action turns into a passing test.
func (v TestCaseStatus) IsValid() bool {
	for _, candidate := range TestCaseStatusValues {
		if v == candidate {
			return true
		}
	}
	return false
}

// TestPlan is part of the generated contract types.
type TestPlan struct {
	Version   int     `json:"version"`
	ProjectID *string `json:"projectId,omitempty"`

	// SourceAppMapRunID — Which run produced the application map this plan was
	// written against. A plan built on a stale map is still reproducible, but it
	// is knowably stale.
	SourceAppMapRunID *string    `json:"sourceAppMapRunId,omitempty"`
	TestCases         []TestCase `json:"testCases"`

	// Rationale — Why these cases and not others. Model prose, shown to a human
	// reviewer, never parsed.
	Rationale string `json:"rationale"`

	// CoverageNotes — What the plan does not cover, and why.
	CoverageNotes string `json:"coverageNotes"`
}

// TextAssertion is part of the generated contract types.
type TextAssertion struct {
	Type      TextAssertionType `json:"type"`
	Message   *string           `json:"message,omitempty"`
	Target    Target            `json:"target"`
	Value     string            `json:"value"`
	TimeoutMs *TimeoutMs        `json:"timeoutMs,omitempty"`
}

// TextAssertionType is part of the generated contract types.
type TextAssertionType string

const (
	TextAssertionTypeTextEquals   TextAssertionType = "textEquals"
	TextAssertionTypeTextContains TextAssertionType = "textContains"
)

// TextAssertionTypeValues lists every member this build knows about, in schema order.
var TextAssertionTypeValues = []TextAssertionType{TextAssertionTypeTextEquals, TextAssertionTypeTextContains}

// IsValid reports whether v is a member this build knows about. A value that
// is not must be rejected with an error: quietly treating it as a default is
// how an unimplemented action turns into a passing test.
func (v TextAssertionType) IsValid() bool {
	for _, candidate := range TextAssertionTypeValues {
		if v == candidate {
			return true
		}
	}
	return false
}

// TimeoutMs is part of the generated contract types.
type TimeoutMs = int

// URLMatchesAssertion is part of the generated contract types.
type URLMatchesAssertion struct {
	Type      string     `json:"type"`
	Message   *string    `json:"message,omitempty"`
	Value     string     `json:"value"`
	TimeoutMs *TimeoutMs `json:"timeoutMs,omitempty"`
}

// WaitForStep is part of the generated contract types.
type WaitForStep struct {
	Action      string           `json:"action"`
	Description *string          `json:"description,omitempty"`
	Target      Target           `json:"target"`
	State       WaitForStepState `json:"state"`
	TimeoutMs   *TimeoutMs       `json:"timeoutMs,omitempty"`
}

// WaitForStepState is part of the generated contract types.
type WaitForStepState string

const (
	WaitForStepStateVisible  WaitForStepState = "visible"
	WaitForStepStateHidden   WaitForStepState = "hidden"
	WaitForStepStateAttached WaitForStepState = "attached"
	WaitForStepStateDetached WaitForStepState = "detached"
)

// WaitForStepStateValues lists every member this build knows about, in schema order.
var WaitForStepStateValues = []WaitForStepState{WaitForStepStateVisible, WaitForStepStateHidden, WaitForStepStateAttached, WaitForStepStateDetached}

// IsValid reports whether v is a member this build knows about. A value that
// is not must be rejected with an error: quietly treating it as a default is
// how an unimplemented action turns into a passing test.
func (v WaitForStepState) IsValid() bool {
	for _, candidate := range WaitForStepStateValues {
		if v == candidate {
			return true
		}
	}
	return false
}

// Workflow is part of the generated contract types.
type Workflow struct {
	ID   Ref    `json:"id"`
	Name string `json:"name"`

	// Path — Alternating page and element refs describing one traversal through
	// the app.
	Path            []Ref  `json:"path"`
	ExpectedOutcome string `json:"expectedOutcome"`
	AuthRequired    *bool  `json:"authRequired,omitempty"`
	LastSeenRunID   *RunID `json:"lastSeenRunId,omitempty"`
}
