package security

import (
	"fmt"
	"net/url"
	"regexp"
	"sort"
	"strings"

	"github.com/ChinnakornP/longtest/daemon/pkg/qaschema"
)

// PlanGate validates what a model produced before any of it is executed.
//
// The prompt boundary in [Wrap] lowers the odds that a page talks the planner
// into something; it cannot make them zero, and a control whose failure mode
// is "the model was persuaded" is not a control. This gate is the part that
// holds when the boundary does not: whatever the model returns, a step that
// leaves the allowlisted origin, carries a credential, or does something
// irreversible without a human does not run.
//
// It is deliberately dumb. Every rule is a property of the JSON, checkable
// without knowing what the test is supposed to do, so the gate cannot itself
// be argued out of a decision.
type PlanGate struct {
	// Egress bounds where a navigate step may point.
	Egress *EgressPolicy
	// BaseURL resolves relative navigate targets before the egress check.
	BaseURL string
	// KnownFixtures are the precondition names the daemon can establish. A
	// plan naming anything else is rejected rather than skipped, so a page
	// cannot invent `fixture:logged_in_as_root`.
	KnownFixtures map[string]struct{}
	// Scrubber knows the run's credentials. A step value containing one means
	// the planner was handed a secret it should never have seen, or produced
	// one from the page — either way the plan does not run.
	Scrubber *Scrubber
	// MaxSteps and MaxCases bound a plan. An injected "test every link on
	// every page a thousand times" is a denial-of-service against the
	// customer's own staging environment.
	MaxSteps int
	MaxCases int
}

// Violation is one reason a plan was refused.
type Violation struct {
	// TestCaseID is the case at fault, empty for a plan-level problem.
	TestCaseID string
	// StepIndex is the offending step, or -1.
	StepIndex int
	// Rule names the check, stable enough to alert on.
	Rule string
	// Detail is the human-readable reason. It may quote model output, so it
	// is scrubbed before it is stored.
	Detail string
}

func (v Violation) String() string {
	loc := v.TestCaseID
	if loc == "" {
		loc = "plan"
	}
	if v.StepIndex >= 0 {
		loc = fmt.Sprintf("%s step %d", loc, v.StepIndex)
	}
	return fmt.Sprintf("%s: %s: %s", loc, v.Rule, v.Detail)
}

// Rule identifiers. They are constants because they end up in events and
// alerts, where a renamed string is a broken dashboard.
//
// is the name of the rule that rejects one.
//
//nolint:gosec // G101 flags RuleCredentialInPlan as a hardcoded credential. It
const (
	RuleEgress            = "egress_not_allowed"
	RuleCredentialInPlan  = "credential_in_plan"
	RuleUnknownFixture    = "unknown_fixture"
	RulePreconditionShape = "precondition_not_a_fixture_ref"
	RuleUnstableLocator   = "unstable_locator_not_flagged"
	RulePlanTooLarge      = "plan_too_large"
	RuleUnknownAction     = "unknown_action"
	RuleSuspiciousValue   = "value_looks_like_an_instruction"
	RuleBadVersion        = "wrong_contract_version"
)

// DefaultMaxSteps and DefaultMaxCases match the schema's own ceilings, so the
// gate agrees with the validator rather than second-guessing it.
const (
	DefaultMaxSteps = 100
	DefaultMaxCases = 200
)

// Check returns every violation in a plan. An empty slice means the plan may
// be executed.
//
// It reports all of them rather than stopping at the first: a plan is
// regenerated by asking the model again, and a retry that fixes one problem
// and hits the next is a slow, expensive loop.
func (g *PlanGate) Check(plan *qaschema.TestPlan) []Violation {
	var out []Violation
	add := func(v Violation) { out = append(out, v) }

	if plan == nil {
		return []Violation{{StepIndex: -1, Rule: RuleBadVersion, Detail: "plan is absent"}}
	}
	if plan.Version != 1 {
		add(Violation{StepIndex: -1, Rule: RuleBadVersion,
			Detail: fmt.Sprintf("plan version %d, expected 1", plan.Version)})
	}

	maxCases := g.MaxCases
	if maxCases <= 0 {
		maxCases = DefaultMaxCases
	}
	if len(plan.TestCases) > maxCases {
		add(Violation{StepIndex: -1, Rule: RulePlanTooLarge,
			Detail: fmt.Sprintf("%d test cases, limit %d", len(plan.TestCases), maxCases)})
	}

	// Model prose is shown to a human but never executed, so it only has to
	// be free of credentials.
	g.checkCredential(&out, "", -1, "rationale", plan.Rationale)
	g.checkCredential(&out, "", -1, "coverageNotes", plan.CoverageNotes)

	for i := range plan.TestCases {
		g.checkCase(&out, &plan.TestCases[i])
	}

	sort.SliceStable(out, func(i, j int) bool {
		if out[i].TestCaseID != out[j].TestCaseID {
			return out[i].TestCaseID < out[j].TestCaseID
		}
		return out[i].StepIndex < out[j].StepIndex
	})
	return out
}

func (g *PlanGate) checkCase(out *[]Violation, tc *qaschema.TestCase) {
	add := func(v Violation) { *out = append(*out, v) }

	maxSteps := g.MaxSteps
	if maxSteps <= 0 {
		maxSteps = DefaultMaxSteps
	}
	if len(tc.Steps) > maxSteps {
		add(Violation{TestCaseID: tc.ID, StepIndex: -1, Rule: RulePlanTooLarge,
			Detail: fmt.Sprintf("%d steps, limit %d", len(tc.Steps), maxSteps)})
	}

	g.checkCredential(out, tc.ID, -1, "name", tc.Name)
	if tc.Description != nil {
		g.checkCredential(out, tc.ID, -1, "description", *tc.Description)
	}

	for _, p := range tc.Preconditions {
		name, ok := strings.CutPrefix(p, "fixture:")
		if !ok {
			add(Violation{TestCaseID: tc.ID, StepIndex: -1, Rule: RulePreconditionShape,
				Detail: fmt.Sprintf("precondition %q is not a fixture reference", p)})
			continue
		}
		if g.KnownFixtures != nil {
			if _, known := g.KnownFixtures[name]; !known {
				add(Violation{TestCaseID: tc.ID, StepIndex: -1, Rule: RuleUnknownFixture,
					Detail: fmt.Sprintf("no fixture named %q is registered for this run", name)})
			}
		}
	}

	for i := range tc.Steps {
		g.checkStep(out, tc.ID, i, &tc.Steps[i])
	}
	for i := range tc.Assertions {
		a := &tc.Assertions[i]
		if a.Target != nil {
			g.checkTarget(out, tc.ID, -1, a.Target)
		}
		if len(a.Value) > 0 {
			g.checkCredential(out, tc.ID, -1, "assertion value", string(a.Value))
		}
	}
}

func (g *PlanGate) checkStep(out *[]Violation, caseID string, idx int, s *qaschema.Step) {
	add := func(v Violation) { *out = append(*out, v) }

	if !knownAction(s.Action) {
		add(Violation{TestCaseID: caseID, StepIndex: idx, Rule: RuleUnknownAction,
			Detail: fmt.Sprintf("action %q is not in the v1 vocabulary", s.Action)})
	}

	if s.Action == qaschema.StepActionNavigate && s.URL != nil {
		g.checkNavigate(out, caseID, idx, *s.URL)
	}
	if s.Value != nil {
		g.checkCredential(out, caseID, idx, "value", *s.Value)
		g.checkInstructionShaped(out, caseID, idx, *s.Value)
	}
	if s.Key != nil {
		g.checkCredential(out, caseID, idx, "key", *s.Key)
	}
	if s.Description != nil {
		g.checkCredential(out, caseID, idx, "description", *s.Description)
	}
	if s.Target != nil {
		g.checkTarget(out, caseID, idx, s.Target)
	}
}

func (g *PlanGate) checkNavigate(out *[]Violation, caseID string, idx int, raw string) {
	add := func(v Violation) { *out = append(*out, v) }

	target := raw
	if strings.HasPrefix(raw, "/") {
		if g.BaseURL == "" {
			add(Violation{TestCaseID: caseID, StepIndex: idx, Rule: RuleEgress,
				Detail: "relative navigate target with no base url to resolve against"})
			return
		}
		base, err := url.Parse(g.BaseURL)
		if err != nil {
			add(Violation{TestCaseID: caseID, StepIndex: idx, Rule: RuleEgress,
				Detail: fmt.Sprintf("base url is unparseable: %v", err)})
			return
		}
		ref, err := url.Parse(raw)
		if err != nil {
			add(Violation{TestCaseID: caseID, StepIndex: idx, Rule: RuleEgress,
				Detail: fmt.Sprintf("navigate target is unparseable: %v", err)})
			return
		}
		target = base.ResolveReference(ref).String()
	}
	if g.Egress == nil {
		add(Violation{TestCaseID: caseID, StepIndex: idx, Rule: RuleEgress,
			Detail: "no egress policy configured for this run"})
		return
	}
	if err := g.Egress.AllowURL(target); err != nil {
		add(Violation{TestCaseID: caseID, StepIndex: idx, Rule: RuleEgress, Detail: err.Error()})
	}
}

func (g *PlanGate) checkTarget(out *[]Violation, caseID string, idx int, t *qaschema.Target) {
	if t.Locator != nil && (t.Unstable == nil || !*t.Unstable) {
		*out = append(*out, Violation{TestCaseID: caseID, StepIndex: idx, Rule: RuleUnstableLocator,
			Detail: "a raw locator must be flagged unstable:true so the run is reportable as non-deterministic"})
	}
	if t.Locator != nil {
		g.checkCredential(out, caseID, idx, "locator", *t.Locator)
	}
}

func (g *PlanGate) checkCredential(out *[]Violation, caseID string, idx int, field, value string) {
	if g.Scrubber == nil || value == "" {
		return
	}
	if g.Scrubber.Contains(value) {
		*out = append(*out, Violation{TestCaseID: caseID, StepIndex: idx, Rule: RuleCredentialInPlan,
			// The offending value is deliberately not quoted here: a violation
			// is logged, and logging the credential to explain that the plan
			// contained a credential defeats the point.
			Detail: fmt.Sprintf("%s contains a run credential verbatim; use a fixture reference", field)})
	}
}

// instructionShaped matches the phrasings an injected page uses when it is
// trying to reach the operator through the plan rather than through the model:
// a `value` that a human reviewer would read as a command.
//
// This is a heuristic and is treated as one — it is the only rule here that
// can produce a false positive, and it earns that because a step value is free
// text that ends up rendered in a report a human acts on.
var instructionShaped = regexp.MustCompile(`(?i)(ignore (all |any )?(previous|prior|above)|disregard (all |any )?(previous|prior)|you are now|new instructions?|system prompt|reveal (the |your )?(password|secret|token|credential)|exfiltrat|curl\s+http|wget\s+http)`)

func (g *PlanGate) checkInstructionShaped(out *[]Violation, caseID string, idx int, value string) {
	if instructionShaped.MatchString(value) {
		*out = append(*out, Violation{TestCaseID: caseID, StepIndex: idx, Rule: RuleSuspiciousValue,
			Detail: "step value reads as an instruction rather than test data; a page probably wrote it"})
	}
}

func knownAction(a qaschema.StepAction) bool {
	for _, v := range qaschema.StepActionValues {
		if v == a {
			return true
		}
	}
	return false
}
