/* eslint-disable */
// Code generated by packages/qa-schema/scripts/generate.mjs. DO NOT EDIT.
// Run `make gen` after changing anything under packages/qa-schema/schemas.

export const SCHEMA_IDS = [
  'application-map@1',
  'daemon-envelope@1',
  'execution-result@1',
  'finding@1',
  'test-case@1',
  'test-plan@1',
] as const;

export type SchemaId = (typeof SCHEMA_IDS)[number];

export const SCHEMA_URIS: Record<SchemaId, string> = {
  'application-map@1': 'https://qa.local/schema/application-map/1',
  'daemon-envelope@1': 'https://qa.local/schema/daemon-envelope/1',
  'execution-result@1': 'https://qa.local/schema/execution-result/1',
  'finding@1': 'https://qa.local/schema/finding/1',
  'test-case@1': 'https://qa.local/schema/test-case/1',
  'test-plan@1': 'https://qa.local/schema/test-plan/1',
};

export const CONTRACT_VERSIONS: Record<SchemaId, string> = {
  'application-map@1': '1.0.0',
  'daemon-envelope@1': '1.0.0',
  'execution-result@1': '1.0.0',
  'finding@1': '1.0.0',
  'test-case@1': '1.0.0',
  'test-plan@1': '1.0.0',
};

export const SCHEMA_DOCUMENTS: Record<SchemaId, unknown> = {
  'application-map@1': {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://qa.local/schema/application-map/1",
    "x-contract-version": "1.0.0",
    "title": "Application map",
    "description": "Contract B. The knowledge graph the Discovery pipeline builds and the Planner reads. Every locator the executor will ever use is named here, so a test case can point at an element by ref instead of inventing a CSS selector.",
    "$ref": "#/$defs/ApplicationMap",
    "$defs": {
      "ApplicationMap": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "version",
          "baseUrl",
          "pages",
          "workflows"
        ],
        "properties": {
          "version": {
            "const": 1
          },
          "baseUrl": {
            "type": "string",
            "format": "uri",
            "maxLength": 2048
          },
          "projectId": {
            "type": "string",
            "format": "uuid"
          },
          "generatedAtRunId": {
            "$ref": "#/$defs/RunId"
          },
          "pages": {
            "type": "array",
            "minItems": 1,
            "maxItems": 500,
            "items": {
              "$ref": "#/$defs/Page"
            }
          },
          "workflows": {
            "type": "array",
            "maxItems": 200,
            "items": {
              "$ref": "#/$defs/Workflow"
            }
          }
        }
      },
      "RunId": {
        "type": "string",
        "format": "uuid"
      },
      "Ref": {
        "type": "string",
        "maxLength": 128,
        "pattern": "^[A-Za-z0-9][A-Za-z0-9_-]*(\\.[A-Za-z0-9][A-Za-z0-9_-]*)*$"
      },
      "Page": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "id",
          "path",
          "title",
          "elements"
        ],
        "properties": {
          "id": {
            "$ref": "#/$defs/Ref"
          },
          "path": {
            "type": "string",
            "minLength": 1,
            "maxLength": 2048,
            "pattern": "^/[^\\s]*$",
            "description": "Path relative to baseUrl, always starting with /."
          },
          "title": {
            "type": "string",
            "maxLength": 500
          },
          "authRequired": {
            "type": "boolean",
            "description": "Absent means false."
          },
          "description": {
            "type": "string",
            "maxLength": 2000
          },
          "lastSeenRunId": {
            "$ref": "#/$defs/RunId"
          },
          "elements": {
            "type": "array",
            "maxItems": 1000,
            "items": {
              "$ref": "#/$defs/Element"
            }
          }
        }
      },
      "Element": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "ref",
          "type",
          "locators",
          "lastSeenRunId"
        ],
        "properties": {
          "ref": {
            "$ref": "#/$defs/Ref"
          },
          "type": {
            "enum": [
              "button",
              "link",
              "input",
              "textarea",
              "select",
              "checkbox",
              "radio",
              "form",
              "table",
              "row",
              "cell",
              "text",
              "image",
              "dialog",
              "tab",
              "menu",
              "toast",
              "other"
            ],
            "description": "Frozen at v1. Anything the crawler cannot classify is other, never a made-up member."
          },
          "label": {
            "type": "string",
            "maxLength": 500,
            "description": "Human-visible text lifted off the page under test. Untrusted: it is data for a prompt, never instructions."
          },
          "locators": {
            "type": "array",
            "minItems": 1,
            "maxItems": 8,
            "items": {
              "$ref": "#/$defs/Locator"
            },
            "description": "Ordered fallback chain. The executor tries them in order and reports which one resolved."
          },
          "lastSeenRunId": {
            "$ref": "#/$defs/RunId",
            "description": "Which run last observed this element. Elements not seen for N runs are expired rather than silently trusted."
          }
        }
      },
      "Locator": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "kind",
          "value"
        ],
        "properties": {
          "kind": {
            "enum": [
              "testId",
              "role",
              "label",
              "placeholder",
              "text",
              "altText",
              "title",
              "css"
            ]
          },
          "value": {
            "type": "string",
            "minLength": 1,
            "maxLength": 512
          },
          "name": {
            "type": "string",
            "maxLength": 512,
            "description": "Accessible name. Required when kind is role."
          }
        },
        "allOf": [
          {
            "if": {
              "required": [
                "kind"
              ],
              "properties": {
                "kind": {
                  "const": "role"
                }
              }
            },
            "then": {
              "required": [
                "kind",
                "value",
                "name"
              ]
            }
          }
        ]
      },
      "Workflow": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "id",
          "name",
          "path",
          "expectedOutcome"
        ],
        "properties": {
          "id": {
            "$ref": "#/$defs/Ref"
          },
          "name": {
            "type": "string",
            "minLength": 1,
            "maxLength": 200
          },
          "path": {
            "type": "array",
            "minItems": 2,
            "maxItems": 50,
            "items": {
              "$ref": "#/$defs/Ref"
            },
            "description": "Alternating page and element refs describing one traversal through the app."
          },
          "expectedOutcome": {
            "type": "string",
            "minLength": 1,
            "maxLength": 1000
          },
          "authRequired": {
            "type": "boolean"
          },
          "lastSeenRunId": {
            "$ref": "#/$defs/RunId"
          }
        }
      }
    }
  },
  'daemon-envelope@1': {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://qa.local/schema/daemon-envelope/1",
    "x-contract-version": "1.0.0",
    "title": "Daemon control-plane envelope",
    "description": "Contract D. Every frame on the single outbound WebSocket between a runtime daemon and the backend. Delivery is at-least-once and the server deduplicates on (runId, seq), so seq is part of the envelope rather than the payload.",
    "$ref": "#/$defs/Envelope",
    "$defs": {
      "Envelope": {
        "type": "object",
        "required": [
          "v",
          "type",
          "msgId",
          "seq",
          "ts",
          "payload"
        ],
        "properties": {
          "v": {
            "const": 1
          },
          "type": {
            "enum": [
              "hello",
              "heartbeat",
              "run.assign",
              "run.cancel",
              "run.event",
              "run.result"
            ]
          },
          "msgId": {
            "type": "string",
            "format": "uuid"
          },
          "runId": {
            "type": [
              "string",
              "null"
            ],
            "format": "uuid",
            "description": "Required for every run.* frame, null or absent for hello and heartbeat."
          },
          "seq": {
            "type": "integer",
            "minimum": 0,
            "description": "Monotonic per (connection, runId). The server deduplicates on (runId, seq)."
          },
          "ts": {
            "type": "string",
            "format": "date-time"
          },
          "payload": {
            "type": "object",
            "x-go-type": "json.RawMessage",
            "x-ts-type": "unknown",
            "$comment": "Kept raw by the generated types: decode type first, then decode payload into the matching *Payload type."
          }
        },
        "allOf": [
          {
            "if": {
              "required": [
                "type"
              ],
              "properties": {
                "type": {
                  "const": "hello"
                }
              }
            },
            "then": {
              "$ref": "#/$defs/HelloFrame"
            }
          },
          {
            "if": {
              "required": [
                "type"
              ],
              "properties": {
                "type": {
                  "const": "heartbeat"
                }
              }
            },
            "then": {
              "$ref": "#/$defs/HeartbeatFrame"
            }
          },
          {
            "if": {
              "required": [
                "type"
              ],
              "properties": {
                "type": {
                  "const": "run.assign"
                }
              }
            },
            "then": {
              "$ref": "#/$defs/RunAssignFrame"
            }
          },
          {
            "if": {
              "required": [
                "type"
              ],
              "properties": {
                "type": {
                  "const": "run.cancel"
                }
              }
            },
            "then": {
              "$ref": "#/$defs/RunCancelFrame"
            }
          },
          {
            "if": {
              "required": [
                "type"
              ],
              "properties": {
                "type": {
                  "const": "run.event"
                }
              }
            },
            "then": {
              "$ref": "#/$defs/RunEventFrame"
            }
          },
          {
            "if": {
              "required": [
                "type"
              ],
              "properties": {
                "type": {
                  "const": "run.result"
                }
              }
            },
            "then": {
              "$ref": "#/$defs/RunResultFrame"
            }
          }
        ]
      },
      "RunScopedFrame": {
        "x-codegen": "skip",
        "type": "object",
        "required": [
          "runId"
        ],
        "properties": {
          "runId": {
            "type": "string",
            "format": "uuid"
          }
        }
      },
      "RuntimeScopedFrame": {
        "x-codegen": "skip",
        "type": "object",
        "properties": {
          "runId": {
            "type": "null"
          }
        }
      },
      "HelloFrame": {
        "x-codegen": "skip",
        "allOf": [
          {
            "$ref": "#/$defs/RuntimeScopedFrame"
          },
          {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "v": true,
              "type": true,
              "msgId": true,
              "runId": true,
              "seq": true,
              "ts": true,
              "payload": {
                "$ref": "#/$defs/HelloPayload"
              }
            }
          }
        ]
      },
      "HeartbeatFrame": {
        "x-codegen": "skip",
        "allOf": [
          {
            "$ref": "#/$defs/RuntimeScopedFrame"
          },
          {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "v": true,
              "type": true,
              "msgId": true,
              "runId": true,
              "seq": true,
              "ts": true,
              "payload": {
                "$ref": "#/$defs/HeartbeatPayload"
              }
            }
          }
        ]
      },
      "RunAssignFrame": {
        "x-codegen": "skip",
        "allOf": [
          {
            "$ref": "#/$defs/RunScopedFrame"
          },
          {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "v": true,
              "type": true,
              "msgId": true,
              "runId": true,
              "seq": true,
              "ts": true,
              "payload": {
                "$ref": "#/$defs/RunAssignPayload"
              }
            }
          }
        ]
      },
      "RunCancelFrame": {
        "x-codegen": "skip",
        "allOf": [
          {
            "$ref": "#/$defs/RunScopedFrame"
          },
          {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "v": true,
              "type": true,
              "msgId": true,
              "runId": true,
              "seq": true,
              "ts": true,
              "payload": {
                "$ref": "#/$defs/RunCancelPayload"
              }
            }
          }
        ]
      },
      "RunEventFrame": {
        "x-codegen": "skip",
        "allOf": [
          {
            "$ref": "#/$defs/RunScopedFrame"
          },
          {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "v": true,
              "type": true,
              "msgId": true,
              "runId": true,
              "seq": true,
              "ts": true,
              "payload": {
                "$ref": "#/$defs/RunEventPayload"
              }
            }
          }
        ]
      },
      "RunResultFrame": {
        "x-codegen": "skip",
        "allOf": [
          {
            "$ref": "#/$defs/RunScopedFrame"
          },
          {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "v": true,
              "type": true,
              "msgId": true,
              "runId": true,
              "seq": true,
              "ts": true,
              "payload": {
                "$ref": "#/$defs/RunResultPayload"
              }
            }
          }
        ]
      },
      "HelloPayload": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "runtimeId",
          "version",
          "browsers",
          "agents"
        ],
        "properties": {
          "runtimeId": {
            "type": "string",
            "format": "uuid"
          },
          "version": {
            "type": "string",
            "minLength": 1,
            "maxLength": 64
          },
          "hostname": {
            "type": "string",
            "maxLength": 255
          },
          "os": {
            "enum": [
              "linux",
              "darwin",
              "windows"
            ]
          },
          "browsers": {
            "type": "array",
            "minItems": 1,
            "maxItems": 3,
            "uniqueItems": true,
            "items": {
              "enum": [
                "chromium",
                "firefox",
                "webkit"
              ]
            }
          },
          "agents": {
            "type": "array",
            "maxItems": 10,
            "items": {
              "$ref": "#/$defs/AgentCapability"
            }
          }
        },
        "$comment": "The org a daemon belongs to is derived from its runtime token, never from this payload."
      },
      "AgentCapability": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "name",
          "ok"
        ],
        "properties": {
          "name": {
            "enum": [
              "claude",
              "opencode",
              "antigravity"
            ]
          },
          "version": {
            "type": "string",
            "maxLength": 64
          },
          "ok": {
            "type": "boolean"
          },
          "error": {
            "type": "string",
            "maxLength": 1000
          }
        }
      },
      "HeartbeatPayload": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "uptimeSec"
        ],
        "properties": {
          "uptimeSec": {
            "type": "integer",
            "minimum": 0
          },
          "activeRuns": {
            "type": "array",
            "maxItems": 50,
            "uniqueItems": true,
            "items": {
              "type": "string",
              "format": "uuid"
            }
          }
        }
      },
      "RunAssignPayload": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "runId",
          "mode",
          "projectId",
          "baseUrl",
          "artifactUpload"
        ],
        "properties": {
          "runId": {
            "type": "string",
            "format": "uuid"
          },
          "mode": {
            "enum": [
              "discover",
              "plan",
              "execute",
              "full"
            ]
          },
          "projectId": {
            "type": "string",
            "format": "uuid"
          },
          "baseUrl": {
            "type": "string",
            "format": "uri",
            "maxLength": 2048
          },
          "agent": {
            "enum": [
              "claude",
              "opencode",
              "antigravity"
            ]
          },
          "appMap": {
            "$ref": "https://qa.local/schema/application-map/1#/$defs/ApplicationMap"
          },
          "testCases": {
            "type": "array",
            "maxItems": 500,
            "items": {
              "$ref": "https://qa.local/schema/test-case/1#/$defs/TestCase"
            }
          },
          "artifactUpload": {
            "$ref": "#/$defs/ArtifactUpload"
          }
        }
      },
      "ArtifactUpload": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "presignedPutBase",
          "keyPrefix",
          "expiresAt"
        ],
        "properties": {
          "presignedPutBase": {
            "type": "string",
            "format": "uri",
            "maxLength": 2048
          },
          "keyPrefix": {
            "type": "string",
            "maxLength": 512,
            "pattern": "^orgs/[A-Za-z0-9][A-Za-z0-9._-]{0,199}/runs/[0-9]{4}-[0-9]{2}-[0-9]{2}/[A-Za-z0-9][A-Za-z0-9._-]{0,199}/$",
            "description": "The daemon may only write below this prefix; the presigned policy enforces the same bound server-side. Segments are anchored the same way as Artifact.key: a prefix whose run segment could be \"..\" is not a bound."
          },
          "expiresAt": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "RunCancelPayload": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "reason"
        ],
        "properties": {
          "reason": {
            "enum": [
              "user_requested",
              "timeout",
              "superseded",
              "shutdown"
            ]
          },
          "message": {
            "type": "string",
            "maxLength": 1000
          }
        }
      },
      "RunEventPayload": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "phase",
          "level",
          "code",
          "message"
        ],
        "properties": {
          "phase": {
            "enum": [
              "discover",
              "plan",
              "execute",
              "analyze",
              "report"
            ]
          },
          "level": {
            "enum": [
              "debug",
              "info",
              "warn",
              "error"
            ]
          },
          "code": {
            "type": "string",
            "pattern": "^[a-z][a-z0-9_]{0,63}$",
            "description": "Machine-readable event code, e.g. page_discovered or agent_output_invalid. The UI switches on this, never on message."
          },
          "message": {
            "type": "string",
            "maxLength": 4000
          },
          "testCaseId": {
            "type": "string",
            "pattern": "^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$"
          },
          "data": {
            "type": "object",
            "description": "Free-form structured detail for this code. Anything lifted off the page under test lands here as data, never as message."
          }
        }
      },
      "RunResultPayload": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "status"
        ],
        "properties": {
          "status": {
            "enum": [
              "completed",
              "failed",
              "cancelled"
            ]
          },
          "error": {
            "$ref": "#/$defs/RunError"
          },
          "appMap": {
            "$ref": "https://qa.local/schema/application-map/1#/$defs/ApplicationMap"
          },
          "testPlan": {
            "$ref": "https://qa.local/schema/test-plan/1#/$defs/TestPlan"
          },
          "executions": {
            "type": "array",
            "maxItems": 500,
            "items": {
              "$ref": "https://qa.local/schema/execution-result/1#/$defs/ExecutionResult"
            }
          },
          "findings": {
            "type": "array",
            "maxItems": 500,
            "items": {
              "$ref": "https://qa.local/schema/finding/1#/$defs/Finding"
            }
          },
          "artifacts": {
            "type": "array",
            "maxItems": 2000,
            "items": {
              "$ref": "https://qa.local/schema/execution-result/1#/$defs/Artifact"
            }
          }
        }
      },
      "RunError": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "enum": [
              "agent_output_invalid",
              "agent_not_available",
              "browser_launch_failed",
              "target_unreachable",
              "artifact_upload_failed",
              "internal"
            ]
          },
          "message": {
            "type": "string",
            "maxLength": 4000
          }
        }
      }
    }
  },
  'execution-result@1': {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://qa.local/schema/execution-result/1",
    "x-contract-version": "1.0.0",
    "title": "Execution result",
    "description": "What the Node executor reports back for one test case: per-step outcome, per-assertion outcome and the artifact keys that back them. This is the only evidence the Failure Analyst is allowed to reason from.",
    "$ref": "#/$defs/ExecutionResult",
    "$defs": {
      "ExecutionResult": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "version",
          "testCaseId",
          "result",
          "steps",
          "artifacts",
          "startedAt",
          "endedAt"
        ],
        "properties": {
          "version": {
            "const": 1
          },
          "testCaseId": {
            "type": "string",
            "pattern": "^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$"
          },
          "runId": {
            "type": "string",
            "format": "uuid"
          },
          "attempt": {
            "type": "integer",
            "minimum": 1,
            "maximum": 10
          },
          "result": {
            "$ref": "#/$defs/Outcome"
          },
          "failureClass": {
            "$ref": "https://qa.local/schema/finding/1#/$defs/FailureClass"
          },
          "message": {
            "type": "string",
            "maxLength": 4000,
            "description": "Executor-authored summary. Never the raw page text."
          },
          "steps": {
            "type": "array",
            "maxItems": 100,
            "items": {
              "$ref": "#/$defs/StepResult"
            }
          },
          "assertions": {
            "type": "array",
            "maxItems": 50,
            "items": {
              "$ref": "#/$defs/AssertionResult"
            }
          },
          "artifacts": {
            "type": "array",
            "maxItems": 200,
            "items": {
              "$ref": "#/$defs/Artifact"
            }
          },
          "startedAt": {
            "type": "string",
            "format": "date-time"
          },
          "endedAt": {
            "type": "string",
            "format": "date-time"
          },
          "durationMs": {
            "type": "integer",
            "minimum": 0
          }
        }
      },
      "Outcome": {
        "enum": [
          "pass",
          "fail",
          "skipped",
          "error"
        ],
        "description": "fail is the application disagreeing with an assertion; error is the harness not getting far enough to have an opinion."
      },
      "StepResult": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "index",
          "action",
          "status"
        ],
        "properties": {
          "index": {
            "type": "integer",
            "minimum": 0,
            "description": "Position in the test case steps array."
          },
          "action": {
            "$ref": "https://qa.local/schema/test-case/1#/$defs/StepAction"
          },
          "status": {
            "$ref": "#/$defs/Outcome"
          },
          "resolvedLocator": {
            "type": "string",
            "maxLength": 512,
            "description": "Which locator in the element fallback chain actually matched."
          },
          "unstableTarget": {
            "type": "boolean",
            "description": "True when the step used a raw locator instead of an application-map ref."
          },
          "message": {
            "type": "string",
            "maxLength": 4000
          },
          "startedAt": {
            "type": "string",
            "format": "date-time"
          },
          "endedAt": {
            "type": "string",
            "format": "date-time"
          },
          "durationMs": {
            "type": "integer",
            "minimum": 0
          },
          "artifactIds": {
            "type": "array",
            "maxItems": 20,
            "items": {
              "$ref": "#/$defs/ArtifactId"
            }
          }
        }
      },
      "AssertionResult": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "index",
          "type",
          "status"
        ],
        "properties": {
          "index": {
            "type": "integer",
            "minimum": 0
          },
          "type": {
            "$ref": "https://qa.local/schema/test-case/1#/$defs/AssertionType"
          },
          "status": {
            "$ref": "#/$defs/Outcome"
          },
          "expected": {
            "type": "string",
            "maxLength": 4000
          },
          "actual": {
            "type": "string",
            "maxLength": 4000,
            "description": "Observed value, lifted off the page under test. Untrusted text."
          },
          "message": {
            "type": "string",
            "maxLength": 4000
          },
          "artifactIds": {
            "type": "array",
            "maxItems": 20,
            "items": {
              "$ref": "#/$defs/ArtifactId"
            }
          }
        }
      },
      "ArtifactId": {
        "type": "string",
        "pattern": "^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$",
        "description": "Run-local handle the daemon makes up so that steps, assertions and findings can point at the same evidence before anything has been stored. It is NOT the database id.",
        "$comment": "Two invariants JSON Schema cannot express, and that ingest therefore has to enforce (LONG-10): these ids must be unique within one run, and ingest must build a wireId -> artifacts.id (uuid) map from run.result.artifacts[] before writing finding_evidence. A duplicate id must be rejected, never last-write-wins."
      },
      "Artifact": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "id",
          "kind",
          "key"
        ],
        "properties": {
          "id": {
            "$ref": "#/$defs/ArtifactId"
          },
          "kind": {
            "enum": [
              "screenshot",
              "trace",
              "video",
              "network",
              "console",
              "dom",
              "report"
            ]
          },
          "key": {
            "type": "string",
            "maxLength": 1024,
            "pattern": "^orgs/[A-Za-z0-9][A-Za-z0-9._-]{0,199}/runs/[0-9]{4}-[0-9]{2}-[0-9]{2}/[A-Za-z0-9][A-Za-z0-9._-]{0,199}/([A-Za-z0-9][A-Za-z0-9._-]{0,99}/)?[A-Za-z0-9][A-Za-z0-9._-]{0,199}$",
            "description": "Object storage key: orgs/{orgId}/runs/{YYYY-MM-DD}/{runId}/{testCaseId}/{filename}, with the {testCaseId} segment omitted for a run-level artifact such as a discovery HAR. That segment is a test case *ref* (TC-001), not the database uuid: the daemon builds the key from the test-case document it was handed and never sees the uuid the backend assigns. What carries the tenant boundary is the orgs/{orgId}/runs/{runId}/ prefix, which is the same prefix the presigned PUT policy is scoped to — so every segment is anchored to start with an alphanumeric, exactly as the artifacts_storage_key_layout CHECK does. A segment that could be \"..\" would make that prefix bound nothing, and the upload happens before the row is ever inserted: the database is the last gate here, not the first."
          },
          "contentType": {
            "type": "string",
            "maxLength": 128
          },
          "sizeBytes": {
            "type": "integer",
            "minimum": 0
          },
          "sha256": {
            "type": "string",
            "pattern": "^[0-9a-f]{64}$"
          }
        }
      }
    }
  },
  'finding@1': {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://qa.local/schema/finding/1",
    "x-contract-version": "1.0.0",
    "title": "Finding",
    "description": "Contract F. The Failure Analyst's verdict on one failed execution. Every failure gets a class: '23 tests failed' with no classification is the outcome this schema exists to prevent.",
    "$ref": "#/$defs/Finding",
    "$defs": {
      "Finding": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "version",
          "testCaseId",
          "stepIndex",
          "failureClass",
          "rootCause",
          "confidence",
          "evidence"
        ],
        "properties": {
          "version": {
            "const": 1
          },
          "testCaseId": {
            "type": "string",
            "pattern": "^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$"
          },
          "executionId": {
            "type": "string",
            "format": "uuid"
          },
          "stepIndex": {
            "type": [
              "integer",
              "null"
            ],
            "minimum": 0,
            "description": "Which step the analyst blames. null when the failure is not attributable to a single step."
          },
          "failureClass": {
            "$ref": "#/$defs/FailureClass"
          },
          "summary": {
            "type": "string",
            "maxLength": 500
          },
          "rootCause": {
            "type": "string",
            "minLength": 1,
            "maxLength": 8000
          },
          "confidence": {
            "type": "number",
            "minimum": 0,
            "maximum": 1,
            "description": "The analyst's own confidence. Shown to the user; never used to silently drop a finding."
          },
          "evidence": {
            "type": "array",
            "minItems": 1,
            "maxItems": 50,
            "items": {
              "$ref": "https://qa.local/schema/execution-result/1#/$defs/ArtifactId"
            },
            "description": "Artifact ids from the execution result. A finding with no evidence is a guess, so at least one is required."
          },
          "suggestedFix": {
            "type": "string",
            "maxLength": 8000
          },
          "analyzedBy": {
            "$ref": "#/$defs/AnalyzedBy"
          }
        }
      },
      "FailureClass": {
        "enum": [
          "PRODUCT_BUG",
          "TEST_BUG",
          "ENVIRONMENT_ERROR",
          "NETWORK_ERROR",
          "AUTHENTICATION_ERROR",
          "TIMEOUT",
          "UNKNOWN"
        ],
        "description": "Frozen at v1. UNKNOWN is the honest answer; a consumer that meets a class it does not recognise must fail loudly rather than bucket it as UNKNOWN."
      },
      "AnalyzedBy": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "provider"
        ],
        "properties": {
          "provider": {
            "enum": [
              "claude",
              "opencode",
              "antigravity"
            ]
          },
          "version": {
            "type": "string",
            "maxLength": 64
          }
        }
      }
    }
  },
  'test-case@1': {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://qa.local/schema/test-case/1",
    "x-contract-version": "1.0.0",
    "title": "Test case",
    "description": "Contract A. Produced by the Test Planner agent, consumed by the Node executor. A test case is data, never code: every step and assertion has to be expressible here or the executor rejects the case.",
    "$ref": "#/$defs/TestCase",
    "$defs": {
      "TestCase": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "version",
          "id",
          "name",
          "priority",
          "category",
          "steps",
          "assertions"
        ],
        "properties": {
          "version": {
            "const": 1,
            "description": "Which contract wrote this case. A test case outlives the run that produced it — it is stored as jsonb and replayed as regression — so the row has to say what it is without the reader guessing from its shape."
          },
          "id": {
            "type": "string",
            "pattern": "^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$",
            "description": "Stable identifier the planner assigns, e.g. TC-001. Reused across runs so results can be compared run over run."
          },
          "name": {
            "type": "string",
            "minLength": 1,
            "maxLength": 200
          },
          "description": {
            "type": "string",
            "maxLength": 4000
          },
          "priority": {
            "enum": [
              "critical",
              "high",
              "medium",
              "low"
            ]
          },
          "category": {
            "enum": [
              "functional",
              "validation",
              "navigation",
              "ui_behavior",
              "error_handling"
            ]
          },
          "status": {
            "enum": [
              "draft",
              "approved",
              "archived"
            ],
            "description": "Review state. Absent means draft; only an approved case is reused as regression."
          },
          "preconditions": {
            "type": "array",
            "maxItems": 20,
            "items": {
              "$ref": "#/$defs/Precondition"
            }
          },
          "tags": {
            "type": "array",
            "maxItems": 20,
            "uniqueItems": true,
            "items": {
              "type": "string",
              "minLength": 1,
              "maxLength": 64
            }
          },
          "steps": {
            "type": "array",
            "minItems": 1,
            "maxItems": 100,
            "items": {
              "$ref": "#/$defs/Step"
            }
          },
          "assertions": {
            "type": "array",
            "minItems": 1,
            "maxItems": 50,
            "items": {
              "$ref": "#/$defs/Assertion"
            }
          }
        }
      },
      "Precondition": {
        "type": "string",
        "pattern": "^fixture:[a-z][a-z0-9_]{0,63}$",
        "description": "A named fixture the runtime knows how to establish, e.g. fixture:logged_in_as_admin. Free prose is rejected on purpose: a precondition an executor cannot establish is not a precondition, and this is also what keeps target-app credentials out of AI-authored JSON."
      },
      "ElementRef": {
        "type": "string",
        "maxLength": 128,
        "pattern": "^[A-Za-z0-9][A-Za-z0-9_-]*(\\.[A-Za-z0-9][A-Za-z0-9_-]*)*$",
        "description": "Reference into application-map@1 elements[].ref."
      },
      "TargetByRef": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "ref"
        ],
        "properties": {
          "ref": {
            "$ref": "#/$defs/ElementRef"
          }
        },
        "description": "The contract form: point at an element the application map already named."
      },
      "TargetByLocator": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "locator",
          "unstable"
        ],
        "properties": {
          "locator": {
            "type": "string",
            "minLength": 1,
            "maxLength": 512
          },
          "unstable": {
            "const": true
          }
        },
        "description": "Escape hatch for a selector the planner invented. unstable must be true: a run that used one is reportable as non-deterministic rather than quietly equivalent."
      },
      "Target": {
        "description": "How a step or assertion points at an element.",
        "oneOf": [
          {
            "$ref": "#/$defs/TargetByRef"
          },
          {
            "$ref": "#/$defs/TargetByLocator"
          }
        ]
      },
      "TimeoutMs": {
        "type": "integer",
        "minimum": 1,
        "maximum": 600000
      },
      "StepAction": {
        "enum": [
          "navigate",
          "click",
          "fill",
          "select",
          "check",
          "hover",
          "press",
          "waitFor",
          "screenshot"
        ],
        "description": "Frozen at v1. Adding a member is a new minor version; an executor that meets an action it does not know must fail the step, never skip it."
      },
      "Step": {
        "type": "object",
        "required": [
          "action"
        ],
        "x-codegen": {
          "union": {
            "discriminator": "action",
            "variants": {
              "navigate": "NavigateStep",
              "click": "ClickStep",
              "fill": "FillStep",
              "select": "SelectStep",
              "check": "CheckStep",
              "hover": "HoverStep",
              "press": "PressStep",
              "waitFor": "WaitForStep",
              "screenshot": "ScreenshotStep"
            }
          }
        },
        "properties": {
          "action": {
            "$ref": "#/$defs/StepAction"
          }
        },
        "allOf": [
          {
            "if": {
              "required": [
                "action"
              ],
              "properties": {
                "action": {
                  "const": "navigate"
                }
              }
            },
            "then": {
              "$ref": "#/$defs/NavigateStep"
            }
          },
          {
            "if": {
              "required": [
                "action"
              ],
              "properties": {
                "action": {
                  "const": "click"
                }
              }
            },
            "then": {
              "$ref": "#/$defs/ClickStep"
            }
          },
          {
            "if": {
              "required": [
                "action"
              ],
              "properties": {
                "action": {
                  "const": "fill"
                }
              }
            },
            "then": {
              "$ref": "#/$defs/FillStep"
            }
          },
          {
            "if": {
              "required": [
                "action"
              ],
              "properties": {
                "action": {
                  "const": "select"
                }
              }
            },
            "then": {
              "$ref": "#/$defs/SelectStep"
            }
          },
          {
            "if": {
              "required": [
                "action"
              ],
              "properties": {
                "action": {
                  "const": "check"
                }
              }
            },
            "then": {
              "$ref": "#/$defs/CheckStep"
            }
          },
          {
            "if": {
              "required": [
                "action"
              ],
              "properties": {
                "action": {
                  "const": "hover"
                }
              }
            },
            "then": {
              "$ref": "#/$defs/HoverStep"
            }
          },
          {
            "if": {
              "required": [
                "action"
              ],
              "properties": {
                "action": {
                  "const": "press"
                }
              }
            },
            "then": {
              "$ref": "#/$defs/PressStep"
            }
          },
          {
            "if": {
              "required": [
                "action"
              ],
              "properties": {
                "action": {
                  "const": "waitFor"
                }
              }
            },
            "then": {
              "$ref": "#/$defs/WaitForStep"
            }
          },
          {
            "if": {
              "required": [
                "action"
              ],
              "properties": {
                "action": {
                  "const": "screenshot"
                }
              }
            },
            "then": {
              "$ref": "#/$defs/ScreenshotStep"
            }
          }
        ]
      },
      "NavigateStep": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "action",
          "url"
        ],
        "properties": {
          "action": {
            "const": "navigate"
          },
          "description": {
            "type": "string",
            "maxLength": 500
          },
          "url": {
            "type": "string",
            "minLength": 1,
            "maxLength": 2048,
            "pattern": "^(/[^\\s]*|https?://[^\\s]+)$",
            "description": "Absolute http(s) URL or a path relative to the project baseUrl."
          },
          "waitUntil": {
            "enum": [
              "load",
              "domcontentloaded",
              "networkidle"
            ]
          },
          "timeoutMs": {
            "$ref": "#/$defs/TimeoutMs"
          }
        }
      },
      "ClickStep": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "action",
          "target"
        ],
        "properties": {
          "action": {
            "const": "click"
          },
          "description": {
            "type": "string",
            "maxLength": 500
          },
          "target": {
            "$ref": "#/$defs/Target"
          },
          "button": {
            "enum": [
              "left",
              "right",
              "middle"
            ]
          },
          "clickCount": {
            "type": "integer",
            "minimum": 1,
            "maximum": 3
          },
          "timeoutMs": {
            "$ref": "#/$defs/TimeoutMs"
          }
        }
      },
      "FillStep": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "action",
          "target",
          "value"
        ],
        "properties": {
          "action": {
            "const": "fill"
          },
          "description": {
            "type": "string",
            "maxLength": 500
          },
          "target": {
            "$ref": "#/$defs/Target"
          },
          "value": {
            "type": "string",
            "maxLength": 4096
          },
          "timeoutMs": {
            "$ref": "#/$defs/TimeoutMs"
          }
        }
      },
      "SelectStep": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "action",
          "target",
          "value"
        ],
        "properties": {
          "action": {
            "const": "select"
          },
          "description": {
            "type": "string",
            "maxLength": 500
          },
          "target": {
            "$ref": "#/$defs/Target"
          },
          "value": {
            "type": "string",
            "maxLength": 1024
          },
          "by": {
            "enum": [
              "value",
              "label",
              "index"
            ]
          },
          "timeoutMs": {
            "$ref": "#/$defs/TimeoutMs"
          }
        }
      },
      "CheckStep": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "action",
          "target"
        ],
        "properties": {
          "action": {
            "const": "check"
          },
          "description": {
            "type": "string",
            "maxLength": 500
          },
          "target": {
            "$ref": "#/$defs/Target"
          },
          "checked": {
            "type": "boolean",
            "description": "Absent means true."
          },
          "timeoutMs": {
            "$ref": "#/$defs/TimeoutMs"
          }
        }
      },
      "HoverStep": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "action",
          "target"
        ],
        "properties": {
          "action": {
            "const": "hover"
          },
          "description": {
            "type": "string",
            "maxLength": 500
          },
          "target": {
            "$ref": "#/$defs/Target"
          },
          "timeoutMs": {
            "$ref": "#/$defs/TimeoutMs"
          }
        }
      },
      "PressStep": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "action",
          "key"
        ],
        "properties": {
          "action": {
            "const": "press"
          },
          "description": {
            "type": "string",
            "maxLength": 500
          },
          "target": {
            "$ref": "#/$defs/Target"
          },
          "key": {
            "type": "string",
            "minLength": 1,
            "maxLength": 64,
            "description": "Playwright key syntax, e.g. Enter or Control+A."
          },
          "timeoutMs": {
            "$ref": "#/$defs/TimeoutMs"
          }
        }
      },
      "WaitForStep": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "action",
          "target",
          "state"
        ],
        "properties": {
          "action": {
            "const": "waitFor"
          },
          "description": {
            "type": "string",
            "maxLength": 500
          },
          "target": {
            "$ref": "#/$defs/Target"
          },
          "state": {
            "enum": [
              "visible",
              "hidden",
              "attached",
              "detached"
            ]
          },
          "timeoutMs": {
            "$ref": "#/$defs/TimeoutMs"
          }
        }
      },
      "ScreenshotStep": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "action"
        ],
        "properties": {
          "action": {
            "const": "screenshot"
          },
          "description": {
            "type": "string",
            "maxLength": 500
          },
          "name": {
            "type": "string",
            "pattern": "^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$"
          },
          "fullPage": {
            "type": "boolean"
          },
          "timeoutMs": {
            "$ref": "#/$defs/TimeoutMs"
          }
        }
      },
      "AssertionType": {
        "enum": [
          "visible",
          "hidden",
          "textEquals",
          "textContains",
          "urlMatches",
          "elementCount",
          "httpStatusNot",
          "noConsoleError"
        ],
        "description": "Frozen at v1. Same rule as steps: an unknown assertion type fails the case, it is never skipped."
      },
      "Assertion": {
        "type": "object",
        "required": [
          "type"
        ],
        "x-codegen": {
          "union": {
            "discriminator": "type",
            "variants": {
              "visible": "TargetAssertion",
              "hidden": "TargetAssertion",
              "textEquals": "TextAssertion",
              "textContains": "TextAssertion",
              "urlMatches": "UrlMatchesAssertion",
              "elementCount": "ElementCountAssertion",
              "httpStatusNot": "HttpStatusNotAssertion",
              "noConsoleError": "NoConsoleErrorAssertion"
            }
          }
        },
        "properties": {
          "type": {
            "$ref": "#/$defs/AssertionType"
          }
        },
        "allOf": [
          {
            "if": {
              "required": [
                "type"
              ],
              "properties": {
                "type": {
                  "const": "visible"
                }
              }
            },
            "then": {
              "$ref": "#/$defs/TargetAssertion"
            }
          },
          {
            "if": {
              "required": [
                "type"
              ],
              "properties": {
                "type": {
                  "const": "hidden"
                }
              }
            },
            "then": {
              "$ref": "#/$defs/TargetAssertion"
            }
          },
          {
            "if": {
              "required": [
                "type"
              ],
              "properties": {
                "type": {
                  "const": "textEquals"
                }
              }
            },
            "then": {
              "$ref": "#/$defs/TextAssertion"
            }
          },
          {
            "if": {
              "required": [
                "type"
              ],
              "properties": {
                "type": {
                  "const": "textContains"
                }
              }
            },
            "then": {
              "$ref": "#/$defs/TextAssertion"
            }
          },
          {
            "if": {
              "required": [
                "type"
              ],
              "properties": {
                "type": {
                  "const": "urlMatches"
                }
              }
            },
            "then": {
              "$ref": "#/$defs/UrlMatchesAssertion"
            }
          },
          {
            "if": {
              "required": [
                "type"
              ],
              "properties": {
                "type": {
                  "const": "elementCount"
                }
              }
            },
            "then": {
              "$ref": "#/$defs/ElementCountAssertion"
            }
          },
          {
            "if": {
              "required": [
                "type"
              ],
              "properties": {
                "type": {
                  "const": "httpStatusNot"
                }
              }
            },
            "then": {
              "$ref": "#/$defs/HttpStatusNotAssertion"
            }
          },
          {
            "if": {
              "required": [
                "type"
              ],
              "properties": {
                "type": {
                  "const": "noConsoleError"
                }
              }
            },
            "then": {
              "$ref": "#/$defs/NoConsoleErrorAssertion"
            }
          }
        ]
      },
      "TargetAssertion": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "type",
          "target"
        ],
        "properties": {
          "type": {
            "enum": [
              "visible",
              "hidden"
            ]
          },
          "message": {
            "type": "string",
            "maxLength": 500
          },
          "target": {
            "$ref": "#/$defs/Target"
          },
          "timeoutMs": {
            "$ref": "#/$defs/TimeoutMs"
          }
        }
      },
      "TextAssertion": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "type",
          "target",
          "value"
        ],
        "properties": {
          "type": {
            "enum": [
              "textEquals",
              "textContains"
            ]
          },
          "message": {
            "type": "string",
            "maxLength": 500
          },
          "target": {
            "$ref": "#/$defs/Target"
          },
          "value": {
            "type": "string",
            "maxLength": 4096
          },
          "timeoutMs": {
            "$ref": "#/$defs/TimeoutMs"
          }
        }
      },
      "UrlMatchesAssertion": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "type",
          "value"
        ],
        "properties": {
          "type": {
            "const": "urlMatches"
          },
          "message": {
            "type": "string",
            "maxLength": 500
          },
          "value": {
            "type": "string",
            "format": "regex",
            "maxLength": 512
          },
          "timeoutMs": {
            "$ref": "#/$defs/TimeoutMs"
          }
        }
      },
      "ElementCountAssertion": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "type",
          "target",
          "value"
        ],
        "properties": {
          "type": {
            "const": "elementCount"
          },
          "message": {
            "type": "string",
            "maxLength": 500
          },
          "target": {
            "$ref": "#/$defs/Target"
          },
          "value": {
            "type": "integer",
            "minimum": 0,
            "maximum": 100000
          },
          "operator": {
            "enum": [
              "eq",
              "gte",
              "lte"
            ],
            "description": "Absent means eq."
          },
          "timeoutMs": {
            "$ref": "#/$defs/TimeoutMs"
          }
        }
      },
      "HttpStatusNotAssertion": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "type",
          "value"
        ],
        "properties": {
          "type": {
            "const": "httpStatusNot"
          },
          "message": {
            "type": "string",
            "maxLength": 500
          },
          "value": {
            "type": "integer",
            "minimum": 100,
            "maximum": 599
          }
        }
      },
      "NoConsoleErrorAssertion": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "type"
        ],
        "properties": {
          "type": {
            "const": "noConsoleError"
          },
          "message": {
            "type": "string",
            "maxLength": 500
          },
          "ignorePatterns": {
            "type": "array",
            "maxItems": 20,
            "items": {
              "type": "string",
              "format": "regex",
              "maxLength": 512
            }
          }
        }
      }
    }
  },
  'test-plan@1': {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://qa.local/schema/test-plan/1",
    "x-contract-version": "1.0.0",
    "title": "Test plan",
    "description": "The out.json an AI Planner writes into its run workspace. Validated before anything else reads it, so a malformed model response fails at the boundary with a field path instead of halfway through execution.",
    "$ref": "#/$defs/TestPlan",
    "$defs": {
      "TestPlan": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "version",
          "testCases",
          "rationale",
          "coverageNotes"
        ],
        "properties": {
          "version": {
            "const": 1
          },
          "projectId": {
            "type": "string",
            "format": "uuid"
          },
          "sourceAppMapRunId": {
            "type": "string",
            "format": "uuid",
            "description": "Which run produced the application map this plan was written against. A plan built on a stale map is still reproducible, but it is knowably stale."
          },
          "testCases": {
            "type": "array",
            "minItems": 1,
            "maxItems": 500,
            "items": {
              "$ref": "https://qa.local/schema/test-case/1#/$defs/TestCase"
            }
          },
          "rationale": {
            "type": "string",
            "minLength": 1,
            "maxLength": 20000,
            "description": "Why these cases and not others. Model prose, shown to a human reviewer, never parsed."
          },
          "coverageNotes": {
            "type": "string",
            "minLength": 1,
            "maxLength": 20000,
            "description": "What the plan does not cover, and why."
          }
        }
      }
    }
  },
};
