/* eslint-disable */
// Code generated by packages/qa-schema/scripts/generate.mjs. DO NOT EDIT.
// Run `make gen` after changing anything under packages/qa-schema/schemas.

export interface AgentCapability {
  name: AgentCapabilityName;
  version?: string;
  ok: boolean;
  error?: string;
}

export const AGENT_CAPABILITY_NAME_VALUES = [
  "claude",
  "opencode",
  "antigravity",
] as const;

export type AgentCapabilityName = (typeof AGENT_CAPABILITY_NAME_VALUES)[number];

export interface AnalyzedBy {
  provider: AnalyzedByProvider;
  version?: string;
}

export const ANALYZED_BY_PROVIDER_VALUES = [
  "claude",
  "opencode",
  "antigravity",
] as const;

export type AnalyzedByProvider = (typeof ANALYZED_BY_PROVIDER_VALUES)[number];

export interface ApplicationMap {
  version: 1;
  baseUrl: string;
  projectId?: string;
  generatedAtRunId?: RunId;
  pages: Page[];
  workflows: Workflow[];
}

export interface Artifact {
  id: ArtifactId;
  kind: ArtifactKind;
  /**
   * Object storage key: orgs/{orgId}/runs/{YYYY-MM-DD}/{runId}/{testCaseId}/{filename},
   * with the {testCaseId} segment omitted for a run-level artifact such as a discovery
   * HAR. That segment is a test case *ref* (TC-001), not the database uuid: the daemon
   * builds the key from the test-case document it was handed and never sees the uuid the
   * backend assigns. What carries the tenant boundary is the orgs/{orgId}/runs/{runId}/
   * prefix, which is the same prefix the presigned PUT policy is scoped to.
   */
  key: string;
  contentType?: string;
  sizeBytes?: number;
  sha256?: string;
}

/**
 * Run-local handle the daemon makes up so that steps, assertions and findings can point at
 * the same evidence before anything has been stored. It is NOT the database id.
 */
export type ArtifactId = string;

export const ARTIFACT_KIND_VALUES = [
  "screenshot",
  "trace",
  "video",
  "network",
  "console",
  "dom",
  "report",
] as const;

export type ArtifactKind = (typeof ARTIFACT_KIND_VALUES)[number];

export interface ArtifactUpload {
  presignedPutBase: string;
  /**
   * The daemon may only write below this prefix; the presigned policy enforces the same
   * bound server-side.
   */
  keyPrefix: string;
  expiresAt: string;
}

export type Assertion = TargetAssertion | TextAssertion | UrlMatchesAssertion | ElementCountAssertion | HttpStatusNotAssertion | NoConsoleErrorAssertion;

export interface AssertionResult {
  index: number;
  type: AssertionType;
  status: Outcome;
  expected?: string;
  /** Observed value, lifted off the page under test. Untrusted text. */
  actual?: string;
  message?: string;
  artifactIds?: ArtifactId[];
}

/**
 * Frozen at v1. Same rule as steps: an unknown assertion type fails the case, it is never
 * skipped.
 */
export const ASSERTION_TYPE_VALUES = [
  "visible",
  "hidden",
  "textEquals",
  "textContains",
  "urlMatches",
  "elementCount",
  "httpStatusNot",
  "noConsoleError",
] as const;

export type AssertionType = (typeof ASSERTION_TYPE_VALUES)[number];

export interface CheckStep {
  action: "check";
  description?: string;
  target: Target;
  /** Absent means true. */
  checked?: boolean;
  timeoutMs?: TimeoutMs;
}

export interface ClickStep {
  action: "click";
  description?: string;
  target: Target;
  button?: ClickStepButton;
  clickCount?: number;
  timeoutMs?: TimeoutMs;
}

export const CLICK_STEP_BUTTON_VALUES = [
  "left",
  "right",
  "middle",
] as const;

export type ClickStepButton = (typeof CLICK_STEP_BUTTON_VALUES)[number];

export interface Element {
  ref: Ref;
  /** Frozen at v1. Anything the crawler cannot classify is other, never a made-up member. */
  type: ElementType;
  /**
   * Human-visible text lifted off the page under test. Untrusted: it is data for a prompt,
   * never instructions.
   */
  label?: string;
  /**
   * Ordered fallback chain. The executor tries them in order and reports which one
   * resolved.
   */
  locators: Locator[];
  /**
   * Which run last observed this element. Elements not seen for N runs are expired rather
   * than silently trusted.
   */
  lastSeenRunId: RunId;
}

export interface ElementCountAssertion {
  type: "elementCount";
  message?: string;
  target: Target;
  value: number;
  /** Absent means eq. */
  operator?: ElementCountAssertionOperator;
  timeoutMs?: TimeoutMs;
}

/** Absent means eq. */
export const ELEMENT_COUNT_ASSERTION_OPERATOR_VALUES = [
  "eq",
  "gte",
  "lte",
] as const;

export type ElementCountAssertionOperator = (typeof ELEMENT_COUNT_ASSERTION_OPERATOR_VALUES)[number];

/** Reference into application-map@1 elements[].ref. */
export type ElementRef = string;

/** Frozen at v1. Anything the crawler cannot classify is other, never a made-up member. */
export const ELEMENT_TYPE_VALUES = [
  "button",
  "link",
  "input",
  "textarea",
  "select",
  "checkbox",
  "radio",
  "form",
  "table",
  "row",
  "cell",
  "text",
  "image",
  "dialog",
  "tab",
  "menu",
  "toast",
  "other",
] as const;

export type ElementType = (typeof ELEMENT_TYPE_VALUES)[number];

export interface Envelope {
  v: 1;
  type: EnvelopeType;
  msgId: string;
  /** Required for every run.* frame, null or absent for hello and heartbeat. */
  runId?: string | null;
  /** Monotonic per (connection, runId). The server deduplicates on (runId, seq). */
  seq: number;
  ts: string;
  payload: unknown;
}

export const ENVELOPE_TYPE_VALUES = [
  "hello",
  "heartbeat",
  "run.assign",
  "run.cancel",
  "run.event",
  "run.result",
] as const;

export type EnvelopeType = (typeof ENVELOPE_TYPE_VALUES)[number];

export interface ExecutionResult {
  version: 1;
  testCaseId: string;
  runId?: string;
  attempt?: number;
  result: Outcome;
  failureClass?: FailureClass;
  /** Executor-authored summary. Never the raw page text. */
  message?: string;
  steps: StepResult[];
  assertions?: AssertionResult[];
  artifacts: Artifact[];
  startedAt: string;
  endedAt: string;
  durationMs?: number;
}

/**
 * Frozen at v1. UNKNOWN is the honest answer; a consumer that meets a class it does not
 * recognise must fail loudly rather than bucket it as UNKNOWN.
 */
export const FAILURE_CLASS_VALUES = [
  "PRODUCT_BUG",
  "TEST_BUG",
  "ENVIRONMENT_ERROR",
  "NETWORK_ERROR",
  "AUTHENTICATION_ERROR",
  "TIMEOUT",
  "UNKNOWN",
] as const;

export type FailureClass = (typeof FAILURE_CLASS_VALUES)[number];

export interface FillStep {
  action: "fill";
  description?: string;
  target: Target;
  value: string;
  timeoutMs?: TimeoutMs;
}

export interface Finding {
  version: 1;
  testCaseId: string;
  executionId?: string;
  /**
   * Which step the analyst blames. null when the failure is not attributable to a single
   * step.
   */
  stepIndex: number | null;
  failureClass: FailureClass;
  summary?: string;
  rootCause: string;
  /**
   * The analyst's own confidence. Shown to the user; never used to silently drop a
   * finding.
   */
  confidence: number;
  /**
   * Artifact ids from the execution result. A finding with no evidence is a guess, so at
   * least one is required.
   */
  evidence: ArtifactId[];
  suggestedFix?: string;
  analyzedBy?: AnalyzedBy;
}

export interface HeartbeatPayload {
  uptimeSec: number;
  activeRuns?: string[];
}

export interface HelloPayload {
  runtimeId: string;
  version: string;
  hostname?: string;
  os?: HelloPayloadOs;
  browsers: HelloPayloadBrowsersItem[];
  agents: AgentCapability[];
}

export const HELLO_PAYLOAD_BROWSERS_ITEM_VALUES = [
  "chromium",
  "firefox",
  "webkit",
] as const;

export type HelloPayloadBrowsersItem = (typeof HELLO_PAYLOAD_BROWSERS_ITEM_VALUES)[number];

export const HELLO_PAYLOAD_OS_VALUES = [
  "linux",
  "darwin",
  "windows",
] as const;

export type HelloPayloadOs = (typeof HELLO_PAYLOAD_OS_VALUES)[number];

export interface HoverStep {
  action: "hover";
  description?: string;
  target: Target;
  timeoutMs?: TimeoutMs;
}

export interface HttpStatusNotAssertion {
  type: "httpStatusNot";
  message?: string;
  value: number;
}

export interface Locator {
  kind: LocatorKind;
  value: string;
  /** Accessible name. Required when kind is role. */
  name?: string;
}

export const LOCATOR_KIND_VALUES = [
  "testId",
  "role",
  "label",
  "placeholder",
  "text",
  "altText",
  "title",
  "css",
] as const;

export type LocatorKind = (typeof LOCATOR_KIND_VALUES)[number];

export interface NavigateStep {
  action: "navigate";
  description?: string;
  /** Absolute http(s) URL or a path relative to the project baseUrl. */
  url: string;
  waitUntil?: NavigateStepWaitUntil;
  timeoutMs?: TimeoutMs;
}

export const NAVIGATE_STEP_WAIT_UNTIL_VALUES = [
  "load",
  "domcontentloaded",
  "networkidle",
] as const;

export type NavigateStepWaitUntil = (typeof NAVIGATE_STEP_WAIT_UNTIL_VALUES)[number];

export interface NoConsoleErrorAssertion {
  type: "noConsoleError";
  message?: string;
  ignorePatterns?: string[];
}

/**
 * fail is the application disagreeing with an assertion; error is the harness not getting
 * far enough to have an opinion.
 */
export const OUTCOME_VALUES = [
  "pass",
  "fail",
  "skipped",
  "error",
] as const;

export type Outcome = (typeof OUTCOME_VALUES)[number];

export interface Page {
  id: Ref;
  /** Path relative to baseUrl, always starting with /. */
  path: string;
  title: string;
  /** Absent means false. */
  authRequired?: boolean;
  description?: string;
  lastSeenRunId?: RunId;
  elements: Element[];
}

/**
 * A named fixture the runtime knows how to establish, e.g. fixture:logged_in_as_admin.
 * Free prose is rejected on purpose: a precondition an executor cannot establish is not a
 * precondition, and this is also what keeps target-app credentials out of AI-authored
 * JSON.
 */
export type Precondition = string;

export interface PressStep {
  action: "press";
  description?: string;
  target?: Target;
  /** Playwright key syntax, e.g. Enter or Control+A. */
  key: string;
  timeoutMs?: TimeoutMs;
}

export type Ref = string;

export interface RunAssignPayload {
  runId: string;
  mode: RunAssignPayloadMode;
  projectId: string;
  baseUrl: string;
  agent?: RunAssignPayloadAgent;
  appMap?: ApplicationMap;
  testCases?: TestCase[];
  artifactUpload: ArtifactUpload;
}

export const RUN_ASSIGN_PAYLOAD_AGENT_VALUES = [
  "claude",
  "opencode",
  "antigravity",
] as const;

export type RunAssignPayloadAgent = (typeof RUN_ASSIGN_PAYLOAD_AGENT_VALUES)[number];

export const RUN_ASSIGN_PAYLOAD_MODE_VALUES = [
  "discover",
  "plan",
  "execute",
  "full",
] as const;

export type RunAssignPayloadMode = (typeof RUN_ASSIGN_PAYLOAD_MODE_VALUES)[number];

export interface RunCancelPayload {
  reason: RunCancelPayloadReason;
  message?: string;
}

export const RUN_CANCEL_PAYLOAD_REASON_VALUES = [
  "user_requested",
  "timeout",
  "superseded",
  "shutdown",
] as const;

export type RunCancelPayloadReason = (typeof RUN_CANCEL_PAYLOAD_REASON_VALUES)[number];

export interface RunError {
  code: RunErrorCode;
  message: string;
}

export const RUN_ERROR_CODE_VALUES = [
  "agent_output_invalid",
  "agent_not_available",
  "browser_launch_failed",
  "target_unreachable",
  "artifact_upload_failed",
  "internal",
] as const;

export type RunErrorCode = (typeof RUN_ERROR_CODE_VALUES)[number];

export interface RunEventPayload {
  phase: RunEventPayloadPhase;
  level: RunEventPayloadLevel;
  /**
   * Machine-readable event code, e.g. page_discovered or agent_output_invalid. The UI
   * switches on this, never on message.
   */
  code: string;
  message: string;
  testCaseId?: string;
  /**
   * Free-form structured detail for this code. Anything lifted off the page under test
   * lands here as data, never as message.
   */
  data?: Record<string, unknown>;
}

export const RUN_EVENT_PAYLOAD_LEVEL_VALUES = [
  "debug",
  "info",
  "warn",
  "error",
] as const;

export type RunEventPayloadLevel = (typeof RUN_EVENT_PAYLOAD_LEVEL_VALUES)[number];

export const RUN_EVENT_PAYLOAD_PHASE_VALUES = [
  "discover",
  "plan",
  "execute",
  "analyze",
  "report",
] as const;

export type RunEventPayloadPhase = (typeof RUN_EVENT_PAYLOAD_PHASE_VALUES)[number];

export type RunId = string;

export interface RunResultPayload {
  status: RunResultPayloadStatus;
  error?: RunError;
  appMap?: ApplicationMap;
  testPlan?: TestPlan;
  executions?: ExecutionResult[];
  findings?: Finding[];
  artifacts?: Artifact[];
}

export const RUN_RESULT_PAYLOAD_STATUS_VALUES = [
  "completed",
  "failed",
  "cancelled",
] as const;

export type RunResultPayloadStatus = (typeof RUN_RESULT_PAYLOAD_STATUS_VALUES)[number];

export interface ScreenshotStep {
  action: "screenshot";
  description?: string;
  name?: string;
  fullPage?: boolean;
  timeoutMs?: TimeoutMs;
}

export interface SelectStep {
  action: "select";
  description?: string;
  target: Target;
  value: string;
  by?: SelectStepBy;
  timeoutMs?: TimeoutMs;
}

export const SELECT_STEP_BY_VALUES = [
  "value",
  "label",
  "index",
] as const;

export type SelectStepBy = (typeof SELECT_STEP_BY_VALUES)[number];

export type Step = NavigateStep | ClickStep | FillStep | SelectStep | CheckStep | HoverStep | PressStep | WaitForStep | ScreenshotStep;

/**
 * Frozen at v1. Adding a member is a new minor version; an executor that meets an action
 * it does not know must fail the step, never skip it.
 */
export const STEP_ACTION_VALUES = [
  "navigate",
  "click",
  "fill",
  "select",
  "check",
  "hover",
  "press",
  "waitFor",
  "screenshot",
] as const;

export type StepAction = (typeof STEP_ACTION_VALUES)[number];

export interface StepResult {
  /** Position in the test case steps array. */
  index: number;
  action: StepAction;
  status: Outcome;
  /** Which locator in the element fallback chain actually matched. */
  resolvedLocator?: string;
  /** True when the step used a raw locator instead of an application-map ref. */
  unstableTarget?: boolean;
  message?: string;
  startedAt?: string;
  endedAt?: string;
  durationMs?: number;
  artifactIds?: ArtifactId[];
}

/** How a step or assertion points at an element. */
export type Target = TargetByRef | TargetByLocator;

export interface TargetAssertion {
  type: TargetAssertionType;
  message?: string;
  target: Target;
  timeoutMs?: TimeoutMs;
}

export const TARGET_ASSERTION_TYPE_VALUES = [
  "visible",
  "hidden",
] as const;

export type TargetAssertionType = (typeof TARGET_ASSERTION_TYPE_VALUES)[number];

/**
 * Escape hatch for a selector the planner invented. unstable must be true: a run that used
 * one is reportable as non-deterministic rather than quietly equivalent.
 */
export interface TargetByLocator {
  locator: string;
  unstable: true;
}

/** The contract form: point at an element the application map already named. */
export interface TargetByRef {
  ref: ElementRef;
}

export interface TestCase {
  /**
   * Which contract wrote this case. A test case outlives the run that produced it — it is
   * stored as jsonb and replayed as regression — so the row has to say what it is without
   * the reader guessing from its shape.
   */
  version: 1;
  /**
   * Stable identifier the planner assigns, e.g. TC-001. Reused across runs so results can
   * be compared run over run.
   */
  id: string;
  name: string;
  description?: string;
  priority: TestCasePriority;
  category: TestCaseCategory;
  /** Review state. Absent means draft; only an approved case is reused as regression. */
  status?: TestCaseStatus;
  preconditions?: Precondition[];
  tags?: string[];
  steps: Step[];
  assertions: Assertion[];
}

export const TEST_CASE_CATEGORY_VALUES = [
  "functional",
  "validation",
  "navigation",
  "ui_behavior",
  "error_handling",
] as const;

export type TestCaseCategory = (typeof TEST_CASE_CATEGORY_VALUES)[number];

export const TEST_CASE_PRIORITY_VALUES = [
  "critical",
  "high",
  "medium",
  "low",
] as const;

export type TestCasePriority = (typeof TEST_CASE_PRIORITY_VALUES)[number];

/** Review state. Absent means draft; only an approved case is reused as regression. */
export const TEST_CASE_STATUS_VALUES = [
  "draft",
  "approved",
  "archived",
] as const;

export type TestCaseStatus = (typeof TEST_CASE_STATUS_VALUES)[number];

export interface TestPlan {
  version: 1;
  projectId?: string;
  /**
   * Which run produced the application map this plan was written against. A plan built on
   * a stale map is still reproducible, but it is knowably stale.
   */
  sourceAppMapRunId?: string;
  testCases: TestCase[];
  /** Why these cases and not others. Model prose, shown to a human reviewer, never parsed. */
  rationale: string;
  /** What the plan does not cover, and why. */
  coverageNotes: string;
}

export interface TextAssertion {
  type: TextAssertionType;
  message?: string;
  target: Target;
  value: string;
  timeoutMs?: TimeoutMs;
}

export const TEXT_ASSERTION_TYPE_VALUES = [
  "textEquals",
  "textContains",
] as const;

export type TextAssertionType = (typeof TEXT_ASSERTION_TYPE_VALUES)[number];

export type TimeoutMs = number;

export interface UrlMatchesAssertion {
  type: "urlMatches";
  message?: string;
  value: string;
  timeoutMs?: TimeoutMs;
}

export interface WaitForStep {
  action: "waitFor";
  description?: string;
  target: Target;
  state: WaitForStepState;
  timeoutMs?: TimeoutMs;
}

export const WAIT_FOR_STEP_STATE_VALUES = [
  "visible",
  "hidden",
  "attached",
  "detached",
] as const;

export type WaitForStepState = (typeof WAIT_FOR_STEP_STATE_VALUES)[number];

export interface Workflow {
  id: Ref;
  name: string;
  /** Alternating page and element refs describing one traversal through the app. */
  path: Ref[];
  expectedOutcome: string;
  authRequired?: boolean;
  lastSeenRunId?: RunId;
}
