// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artifacts.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteArtifact = `-- name: DeleteArtifact :execrows
DELETE FROM artifacts WHERE org_id = $1 AND id = $2
`

type DeleteArtifactParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) DeleteArtifact(ctx context.Context, arg DeleteArtifactParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteArtifact, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getArtifact = `-- name: GetArtifact :one
SELECT id, org_id, run_id, execution_id, test_case_id, kind, name, storage_key, content_type, size_bytes, sha256, created_at FROM artifacts WHERE org_id = $1 AND id = $2
`

type GetArtifactParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) GetArtifact(ctx context.Context, arg GetArtifactParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, getArtifact, arg.OrgID, arg.ID)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RunID,
		&i.ExecutionID,
		&i.TestCaseID,
		&i.Kind,
		&i.Name,
		&i.StorageKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Sha256,
		&i.CreatedAt,
	)
	return i, err
}

const listArtifactsForExecution = `-- name: ListArtifactsForExecution :many
SELECT id, org_id, run_id, execution_id, test_case_id, kind, name, storage_key, content_type, size_bytes, sha256, created_at FROM artifacts
WHERE org_id = $1 AND execution_id = $2
ORDER BY created_at
`

type ListArtifactsForExecutionParams struct {
	OrgID       uuid.UUID
	ExecutionID uuid.NullUUID
}

func (q *Queries) ListArtifactsForExecution(ctx context.Context, arg ListArtifactsForExecutionParams) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, listArtifactsForExecution, arg.OrgID, arg.ExecutionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artifact{}
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.RunID,
			&i.ExecutionID,
			&i.TestCaseID,
			&i.Kind,
			&i.Name,
			&i.StorageKey,
			&i.ContentType,
			&i.SizeBytes,
			&i.Sha256,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactsForRun = `-- name: ListArtifactsForRun :many
SELECT id, org_id, run_id, execution_id, test_case_id, kind, name, storage_key, content_type, size_bytes, sha256, created_at FROM artifacts
WHERE org_id = $1 AND run_id = $2
ORDER BY created_at
`

type ListArtifactsForRunParams struct {
	OrgID uuid.UUID
	RunID uuid.UUID
}

func (q *Queries) ListArtifactsForRun(ctx context.Context, arg ListArtifactsForRunParams) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, listArtifactsForRun, arg.OrgID, arg.RunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artifact{}
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.RunID,
			&i.ExecutionID,
			&i.TestCaseID,
			&i.Kind,
			&i.Name,
			&i.StorageKey,
			&i.ContentType,
			&i.SizeBytes,
			&i.Sha256,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertArtifact = `-- name: UpsertArtifact :one

INSERT INTO artifacts (org_id, run_id, execution_id, test_case_id, kind, name,
                       storage_key, content_type, size_bytes, sha256)
VALUES ($1, $2, $7, $8, $3, $4, $5, $6,
        $9, $10)
ON CONFLICT (storage_key) DO UPDATE
SET content_type = EXCLUDED.content_type,
    size_bytes = EXCLUDED.size_bytes,
    sha256 = EXCLUDED.sha256
RETURNING id, org_id, run_id, execution_id, test_case_id, kind, name, storage_key, content_type, size_bytes, sha256, created_at
`

type UpsertArtifactParams struct {
	OrgID       uuid.UUID
	RunID       uuid.UUID
	Kind        ArtifactKind
	Name        string
	StorageKey  string
	ContentType string
	ExecutionID uuid.NullUUID
	TestCaseID  uuid.NullUUID
	SizeBytes   pgtype.Int8
	Sha256      []byte
}

// Artifact metadata. The bytes go straight from the daemon to object storage
// with a presigned PUT; the storage_key layout is enforced by a CHECK on the
// table, so a key pointing outside this row's own org/run is rejected here.
// Re-registering the same object after a daemon reconnect updates the row
// rather than failing: the upload itself is idempotent on the same key.
func (q *Queries) UpsertArtifact(ctx context.Context, arg UpsertArtifactParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, upsertArtifact,
		arg.OrgID,
		arg.RunID,
		arg.Kind,
		arg.Name,
		arg.StorageKey,
		arg.ContentType,
		arg.ExecutionID,
		arg.TestCaseID,
		arg.SizeBytes,
		arg.Sha256,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RunID,
		&i.ExecutionID,
		&i.TestCaseID,
		&i.Kind,
		&i.Name,
		&i.StorageKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Sha256,
		&i.CreatedAt,
	)
	return i, err
}
