// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.go

package dbgen

import (
	"context"
	"encoding/json"
	"errors"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const appendRunEventBatch = `-- name: AppendRunEventBatch :batchexec
INSERT INTO run_events (org_id, run_id, seq, phase, level, code, message, data, ts)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (run_id, seq) DO NOTHING
`

type AppendRunEventBatchBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type AppendRunEventBatchParams struct {
	OrgID   uuid.UUID
	RunID   uuid.UUID
	Seq     int64
	Phase   string
	Level   RunEventLevel
	Code    string
	Message string
	Data    json.RawMessage
	Ts      pgtype.Timestamptz
}

// Bulk form for a daemon flushing its backlog after a reconnect: one pgx
// batch instead of a round trip per event, deduped by the same unique index.
func (q *Queries) AppendRunEventBatch(ctx context.Context, arg []AppendRunEventBatchParams) *AppendRunEventBatchBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.OrgID,
			a.RunID,
			a.Seq,
			a.Phase,
			a.Level,
			a.Code,
			a.Message,
			a.Data,
			a.Ts,
		}
		batch.Queue(appendRunEventBatch, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &AppendRunEventBatchBatchResults{br, len(arg), false}
}

func (b *AppendRunEventBatchBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *AppendRunEventBatchBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const upsertElementBatch = `-- name: UpsertElementBatch :batchone
INSERT INTO elements (org_id, page_id, ref, kind, label, locators, last_seen_run_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (page_id, ref) DO UPDATE
SET kind = EXCLUDED.kind,
    label = EXCLUDED.label,
    locators = EXCLUDED.locators,
    last_seen_run_id = coalesce(EXCLUDED.last_seen_run_id, elements.last_seen_run_id)
RETURNING id, org_id, page_id, ref, kind, label, locators, last_seen_run_id, created_at, updated_at
`

type UpsertElementBatchBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertElementBatchParams struct {
	OrgID    uuid.UUID
	PageID   uuid.UUID
	Ref      string
	Kind     string
	Label    string
	Locators json.RawMessage
	RunID    uuid.NullUUID
}

// Bulk form for the discovery ingest; see the note on UpsertPageBatch.
func (q *Queries) UpsertElementBatch(ctx context.Context, arg []UpsertElementBatchParams) *UpsertElementBatchBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.OrgID,
			a.PageID,
			a.Ref,
			a.Kind,
			a.Label,
			a.Locators,
			a.RunID,
		}
		batch.Queue(upsertElementBatch, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertElementBatchBatchResults{br, len(arg), false}
}

func (b *UpsertElementBatchBatchResults) QueryRow(f func(int, Element, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var i Element
		if b.closed {
			if f != nil {
				f(t, i, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(
			&i.ID,
			&i.OrgID,
			&i.PageID,
			&i.Ref,
			&i.Kind,
			&i.Label,
			&i.Locators,
			&i.LastSeenRunID,
			&i.CreatedAt,
			&i.UpdatedAt,
		)
		if f != nil {
			f(t, i, err)
		}
	}
}

func (b *UpsertElementBatchBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const upsertPageBatch = `-- name: UpsertPageBatch :batchone
INSERT INTO pages (org_id, project_id, ref, path, title, auth_required,
                   first_seen_run_id, last_seen_run_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $7)
ON CONFLICT (project_id, ref) DO UPDATE
SET path = EXCLUDED.path,
    title = EXCLUDED.title,
    auth_required = EXCLUDED.auth_required,
    last_seen_run_id = coalesce(EXCLUDED.last_seen_run_id, pages.last_seen_run_id)
RETURNING id, org_id, project_id, ref, path, title, auth_required, first_seen_run_id, last_seen_run_id, created_at, updated_at
`

type UpsertPageBatchBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertPageBatchParams struct {
	OrgID        uuid.UUID
	ProjectID    uuid.UUID
	Ref          string
	Path         string
	Title        string
	AuthRequired bool
	RunID        uuid.NullUUID
}

// Bulk form for the discovery ingest, issued as a single pgx batch: one
// network round trip for the whole map instead of one per page. Fetching or
// writing the map page by page is the N+1 this replaces.
func (q *Queries) UpsertPageBatch(ctx context.Context, arg []UpsertPageBatchParams) *UpsertPageBatchBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.OrgID,
			a.ProjectID,
			a.Ref,
			a.Path,
			a.Title,
			a.AuthRequired,
			a.RunID,
		}
		batch.Queue(upsertPageBatch, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertPageBatchBatchResults{br, len(arg), false}
}

func (b *UpsertPageBatchBatchResults) QueryRow(f func(int, Page, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var i Page
		if b.closed {
			if f != nil {
				f(t, i, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.Ref,
			&i.Path,
			&i.Title,
			&i.AuthRequired,
			&i.FirstSeenRunID,
			&i.LastSeenRunID,
			&i.CreatedAt,
			&i.UpdatedAt,
		)
		if f != nil {
			f(t, i, err)
		}
	}
}

func (b *UpsertPageBatchBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
