// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: elements.sql

package dbgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const deleteElement = `-- name: DeleteElement :execrows
DELETE FROM elements WHERE org_id = $1 AND id = $2
`

type DeleteElementParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) DeleteElement(ctx context.Context, arg DeleteElementParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteElement, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getElement = `-- name: GetElement :one
SELECT id, org_id, page_id, ref, kind, label, locators, last_seen_run_id, created_at, updated_at FROM elements WHERE org_id = $1 AND id = $2
`

type GetElementParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) GetElement(ctx context.Context, arg GetElementParams) (Element, error) {
	row := q.db.QueryRow(ctx, getElement, arg.OrgID, arg.ID)
	var i Element
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.PageID,
		&i.Ref,
		&i.Kind,
		&i.Label,
		&i.Locators,
		&i.LastSeenRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listElementsForPage = `-- name: ListElementsForPage :many
SELECT id, org_id, page_id, ref, kind, label, locators, last_seen_run_id, created_at, updated_at FROM elements
WHERE org_id = $1 AND page_id = $2
ORDER BY ref
`

type ListElementsForPageParams struct {
	OrgID  uuid.UUID
	PageID uuid.UUID
}

func (q *Queries) ListElementsForPage(ctx context.Context, arg ListElementsForPageParams) ([]Element, error) {
	rows, err := q.db.Query(ctx, listElementsForPage, arg.OrgID, arg.PageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Element{}
	for rows.Next() {
		var i Element
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.PageID,
			&i.Ref,
			&i.Kind,
			&i.Label,
			&i.Locators,
			&i.LastSeenRunID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listElementsForProject = `-- name: ListElementsForProject :many
SELECT e.id, e.org_id, e.page_id, e.ref, e.kind, e.label, e.locators, e.last_seen_run_id, e.created_at, e.updated_at
FROM elements e
JOIN pages p ON p.id = e.page_id AND p.org_id = e.org_id
WHERE e.org_id = $1 AND p.project_id = $2
ORDER BY p.path, e.ref
`

type ListElementsForProjectParams struct {
	OrgID     uuid.UUID
	ProjectID uuid.UUID
}

// Every element of a project in one query. Assembling the Application Map is
// then: pages + this + workflows = three statements, whatever the map's size.
// Fetching elements per page would be the N+1 this replaces.
func (q *Queries) ListElementsForProject(ctx context.Context, arg ListElementsForProjectParams) ([]Element, error) {
	rows, err := q.db.Query(ctx, listElementsForProject, arg.OrgID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Element{}
	for rows.Next() {
		var i Element
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.PageID,
			&i.Ref,
			&i.Kind,
			&i.Label,
			&i.Locators,
			&i.LastSeenRunID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertElement = `-- name: UpsertElement :one
INSERT INTO elements (org_id, page_id, ref, kind, label, locators, last_seen_run_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (page_id, ref) DO UPDATE
SET kind = EXCLUDED.kind,
    label = EXCLUDED.label,
    locators = EXCLUDED.locators,
    last_seen_run_id = coalesce(EXCLUDED.last_seen_run_id, elements.last_seen_run_id)
RETURNING id, org_id, page_id, ref, kind, label, locators, last_seen_run_id, created_at, updated_at
`

type UpsertElementParams struct {
	OrgID    uuid.UUID
	PageID   uuid.UUID
	Ref      string
	Kind     string
	Label    string
	Locators json.RawMessage
	RunID    uuid.NullUUID
}

func (q *Queries) UpsertElement(ctx context.Context, arg UpsertElementParams) (Element, error) {
	row := q.db.QueryRow(ctx, upsertElement,
		arg.OrgID,
		arg.PageID,
		arg.Ref,
		arg.Kind,
		arg.Label,
		arg.Locators,
		arg.RunID,
	)
	var i Element
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.PageID,
		&i.Ref,
		&i.Kind,
		&i.Label,
		&i.Locators,
		&i.LastSeenRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
