// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: executions.sql

package dbgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createExecution = `-- name: CreateExecution :one
INSERT INTO executions (org_id, run_id, test_case_id, test_case_version)
VALUES ($1, $2, $3, $4)
ON CONFLICT (run_id, test_case_id) DO NOTHING
RETURNING id, org_id, run_id, test_case_id, test_case_version, result, failure_class, error_message, duration_ms, started_at, finished_at, created_at, updated_at
`

type CreateExecutionParams struct {
	OrgID           uuid.UUID
	RunID           uuid.UUID
	TestCaseID      uuid.UUID
	TestCaseVersion int32
}

func (q *Queries) CreateExecution(ctx context.Context, arg CreateExecutionParams) (Execution, error) {
	row := q.db.QueryRow(ctx, createExecution,
		arg.OrgID,
		arg.RunID,
		arg.TestCaseID,
		arg.TestCaseVersion,
	)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RunID,
		&i.TestCaseID,
		&i.TestCaseVersion,
		&i.Result,
		&i.FailureClass,
		&i.ErrorMessage,
		&i.DurationMs,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createExecutionsForRun = `-- name: CreateExecutionsForRun :many
INSERT INTO executions (org_id, run_id, test_case_id, test_case_version)
SELECT tc.org_id, $1::uuid, tc.id, tc.current_version
FROM test_cases tc
WHERE tc.org_id = $2
  AND tc.id = ANY ($3::uuid[])
ON CONFLICT (run_id, test_case_id) DO NOTHING
RETURNING id, org_id, run_id, test_case_id, test_case_version, result, failure_class, error_message, duration_ms, started_at, finished_at, created_at, updated_at
`

type CreateExecutionsForRunParams struct {
	RunID       uuid.UUID
	OrgID       uuid.UUID
	TestCaseIds []uuid.UUID
}

// Seeds a run's whole work list in one statement from the cases it selected,
// pinning each to the version that is current right now.
func (q *Queries) CreateExecutionsForRun(ctx context.Context, arg CreateExecutionsForRunParams) ([]Execution, error) {
	rows, err := q.db.Query(ctx, createExecutionsForRun, arg.RunID, arg.OrgID, arg.TestCaseIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Execution{}
	for rows.Next() {
		var i Execution
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.RunID,
			&i.TestCaseID,
			&i.TestCaseVersion,
			&i.Result,
			&i.FailureClass,
			&i.ErrorMessage,
			&i.DurationMs,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishExecution = `-- name: FinishExecution :one
UPDATE executions
SET result = $1,
    failure_class = $2,
    error_message = $3,
    duration_ms = $4,
    finished_at = now()
WHERE org_id = $5
  AND id = $6
  AND result IN ('pending', 'running')
RETURNING id, org_id, run_id, test_case_id, test_case_version, result, failure_class, error_message, duration_ms, started_at, finished_at, created_at, updated_at
`

type FinishExecutionParams struct {
	Result       ExecutionResult
	FailureClass NullFailureClass
	ErrorMessage string
	DurationMs   pgtype.Int4
	OrgID        uuid.UUID
	ID           uuid.UUID
}

// Terminal write, guarded on the current result so a redelivered result frame
// is a no-op rather than a rewrite.
func (q *Queries) FinishExecution(ctx context.Context, arg FinishExecutionParams) (Execution, error) {
	row := q.db.QueryRow(ctx, finishExecution,
		arg.Result,
		arg.FailureClass,
		arg.ErrorMessage,
		arg.DurationMs,
		arg.OrgID,
		arg.ID,
	)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RunID,
		&i.TestCaseID,
		&i.TestCaseVersion,
		&i.Result,
		&i.FailureClass,
		&i.ErrorMessage,
		&i.DurationMs,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExecution = `-- name: GetExecution :one
SELECT id, org_id, run_id, test_case_id, test_case_version, result, failure_class, error_message, duration_ms, started_at, finished_at, created_at, updated_at FROM executions WHERE org_id = $1 AND id = $2
`

type GetExecutionParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) GetExecution(ctx context.Context, arg GetExecutionParams) (Execution, error) {
	row := q.db.QueryRow(ctx, getExecution, arg.OrgID, arg.ID)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RunID,
		&i.TestCaseID,
		&i.TestCaseVersion,
		&i.Result,
		&i.FailureClass,
		&i.ErrorMessage,
		&i.DurationMs,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExecutionByRunAndCase = `-- name: GetExecutionByRunAndCase :one
SELECT id, org_id, run_id, test_case_id, test_case_version, result, failure_class, error_message, duration_ms, started_at, finished_at, created_at, updated_at FROM executions WHERE org_id = $1 AND run_id = $2 AND test_case_id = $3
`

type GetExecutionByRunAndCaseParams struct {
	OrgID      uuid.UUID
	RunID      uuid.UUID
	TestCaseID uuid.UUID
}

func (q *Queries) GetExecutionByRunAndCase(ctx context.Context, arg GetExecutionByRunAndCaseParams) (Execution, error) {
	row := q.db.QueryRow(ctx, getExecutionByRunAndCase, arg.OrgID, arg.RunID, arg.TestCaseID)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RunID,
		&i.TestCaseID,
		&i.TestCaseVersion,
		&i.Result,
		&i.FailureClass,
		&i.ErrorMessage,
		&i.DurationMs,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExecutionAssertions = `-- name: ListExecutionAssertions :many
SELECT id, org_id, execution_id, assertion_index, type, status, expected, actual, message, created_at FROM execution_assertions
WHERE org_id = $1 AND execution_id = $2
ORDER BY assertion_index
`

type ListExecutionAssertionsParams struct {
	OrgID       uuid.UUID
	ExecutionID uuid.UUID
}

func (q *Queries) ListExecutionAssertions(ctx context.Context, arg ListExecutionAssertionsParams) ([]ExecutionAssertion, error) {
	rows, err := q.db.Query(ctx, listExecutionAssertions, arg.OrgID, arg.ExecutionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExecutionAssertion{}
	for rows.Next() {
		var i ExecutionAssertion
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ExecutionID,
			&i.AssertionIndex,
			&i.Type,
			&i.Status,
			&i.Expected,
			&i.Actual,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExecutionAssertionsForRun = `-- name: ListExecutionAssertionsForRun :many
SELECT a.id, a.org_id, a.execution_id, a.assertion_index, a.type, a.status, a.expected, a.actual, a.message, a.created_at
FROM execution_assertions a
JOIN executions e ON e.id = a.execution_id AND e.org_id = a.org_id
WHERE a.org_id = $1 AND e.run_id = $2
ORDER BY a.execution_id, a.assertion_index
`

type ListExecutionAssertionsForRunParams struct {
	OrgID uuid.UUID
	RunID uuid.UUID
}

// Every assertion of a run in one query. The analyst needs the failing
// assertion's expected/actual pair to classify a failure at all, and fetching
// them per execution would be the N+1 this replaces.
func (q *Queries) ListExecutionAssertionsForRun(ctx context.Context, arg ListExecutionAssertionsForRunParams) ([]ExecutionAssertion, error) {
	rows, err := q.db.Query(ctx, listExecutionAssertionsForRun, arg.OrgID, arg.RunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExecutionAssertion{}
	for rows.Next() {
		var i ExecutionAssertion
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ExecutionID,
			&i.AssertionIndex,
			&i.Type,
			&i.Status,
			&i.Expected,
			&i.Actual,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExecutionSteps = `-- name: ListExecutionSteps :many
SELECT id, org_id, execution_id, step_index, action, target, result, unstable, error_message, duration_ms, started_at, finished_at, created_at FROM execution_steps
WHERE org_id = $1 AND execution_id = $2
ORDER BY step_index
`

type ListExecutionStepsParams struct {
	OrgID       uuid.UUID
	ExecutionID uuid.UUID
}

func (q *Queries) ListExecutionSteps(ctx context.Context, arg ListExecutionStepsParams) ([]ExecutionStep, error) {
	rows, err := q.db.Query(ctx, listExecutionSteps, arg.OrgID, arg.ExecutionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExecutionStep{}
	for rows.Next() {
		var i ExecutionStep
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ExecutionID,
			&i.StepIndex,
			&i.Action,
			&i.Target,
			&i.Result,
			&i.Unstable,
			&i.ErrorMessage,
			&i.DurationMs,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExecutionStepsForRun = `-- name: ListExecutionStepsForRun :many
SELECT s.id, s.org_id, s.execution_id, s.step_index, s.action, s.target, s.result, s.unstable, s.error_message, s.duration_ms, s.started_at, s.finished_at, s.created_at
FROM execution_steps s
JOIN executions e ON e.id = s.execution_id AND e.org_id = s.org_id
WHERE s.org_id = $1 AND e.run_id = $2
ORDER BY s.execution_id, s.step_index
`

type ListExecutionStepsForRunParams struct {
	OrgID uuid.UUID
	RunID uuid.UUID
}

// Every step of a run in one query, for the report view.
func (q *Queries) ListExecutionStepsForRun(ctx context.Context, arg ListExecutionStepsForRunParams) ([]ExecutionStep, error) {
	rows, err := q.db.Query(ctx, listExecutionStepsForRun, arg.OrgID, arg.RunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExecutionStep{}
	for rows.Next() {
		var i ExecutionStep
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ExecutionID,
			&i.StepIndex,
			&i.Action,
			&i.Target,
			&i.Result,
			&i.Unstable,
			&i.ErrorMessage,
			&i.DurationMs,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExecutionsForRun = `-- name: ListExecutionsForRun :many
SELECT e.id, e.org_id, e.run_id, e.test_case_id, e.test_case_version, e.result, e.failure_class, e.error_message, e.duration_ms, e.started_at, e.finished_at, e.created_at, e.updated_at, tc.ref, tc.name, tc.priority, tc.category
FROM executions e
JOIN test_cases tc ON tc.id = e.test_case_id AND tc.org_id = e.org_id
WHERE e.org_id = $1 AND e.run_id = $2
ORDER BY tc.priority, tc.ref
`

type ListExecutionsForRunParams struct {
	OrgID uuid.UUID
	RunID uuid.UUID
}

type ListExecutionsForRunRow struct {
	Execution Execution
	Ref       string
	Name      string
	Priority  TestPriority
	Category  TestCategory
}

// The report read: executions plus the case they ran, in one join. Fetching
// the test case per execution would be the N+1 this replaces.
func (q *Queries) ListExecutionsForRun(ctx context.Context, arg ListExecutionsForRunParams) ([]ListExecutionsForRunRow, error) {
	rows, err := q.db.Query(ctx, listExecutionsForRun, arg.OrgID, arg.RunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExecutionsForRunRow{}
	for rows.Next() {
		var i ListExecutionsForRunRow
		if err := rows.Scan(
			&i.Execution.ID,
			&i.Execution.OrgID,
			&i.Execution.RunID,
			&i.Execution.TestCaseID,
			&i.Execution.TestCaseVersion,
			&i.Execution.Result,
			&i.Execution.FailureClass,
			&i.Execution.ErrorMessage,
			&i.Execution.DurationMs,
			&i.Execution.StartedAt,
			&i.Execution.FinishedAt,
			&i.Execution.CreatedAt,
			&i.Execution.UpdatedAt,
			&i.Ref,
			&i.Name,
			&i.Priority,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentExecutionsForTestCase = `-- name: ListRecentExecutionsForTestCase :many
SELECT id, org_id, run_id, test_case_id, test_case_version, result, failure_class, error_message, duration_ms, started_at, finished_at, created_at, updated_at FROM executions
WHERE org_id = $1 AND test_case_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListRecentExecutionsForTestCaseParams struct {
	OrgID      uuid.UUID
	TestCaseID uuid.UUID
	Limit      int32
}

// Phase 6 input: how one case has behaved over its recent runs.
func (q *Queries) ListRecentExecutionsForTestCase(ctx context.Context, arg ListRecentExecutionsForTestCaseParams) ([]Execution, error) {
	rows, err := q.db.Query(ctx, listRecentExecutionsForTestCase, arg.OrgID, arg.TestCaseID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Execution{}
	for rows.Next() {
		var i Execution
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.RunID,
			&i.TestCaseID,
			&i.TestCaseVersion,
			&i.Result,
			&i.FailureClass,
			&i.ErrorMessage,
			&i.DurationMs,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markExecutionRunning = `-- name: MarkExecutionRunning :one
UPDATE executions
SET result = 'running', started_at = coalesce(started_at, now())
WHERE org_id = $1 AND id = $2 AND result IN ('pending', 'running')
RETURNING id, org_id, run_id, test_case_id, test_case_version, result, failure_class, error_message, duration_ms, started_at, finished_at, created_at, updated_at
`

type MarkExecutionRunningParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) MarkExecutionRunning(ctx context.Context, arg MarkExecutionRunningParams) (Execution, error) {
	row := q.db.QueryRow(ctx, markExecutionRunning, arg.OrgID, arg.ID)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RunID,
		&i.TestCaseID,
		&i.TestCaseVersion,
		&i.Result,
		&i.FailureClass,
		&i.ErrorMessage,
		&i.DurationMs,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertExecutionAssertion = `-- name: UpsertExecutionAssertion :one
INSERT INTO execution_assertions (org_id, execution_id, assertion_index, type,
                                  status, expected, actual, message)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (execution_id, assertion_index) DO UPDATE
SET type = EXCLUDED.type,
    status = EXCLUDED.status,
    expected = EXCLUDED.expected,
    actual = EXCLUDED.actual,
    message = EXCLUDED.message
RETURNING id, org_id, execution_id, assertion_index, type, status, expected, actual, message, created_at
`

type UpsertExecutionAssertionParams struct {
	OrgID          uuid.UUID
	ExecutionID    uuid.UUID
	AssertionIndex int32
	Type           string
	Status         ExecutionResult
	Expected       string
	Actual         string
	Message        string
}

func (q *Queries) UpsertExecutionAssertion(ctx context.Context, arg UpsertExecutionAssertionParams) (ExecutionAssertion, error) {
	row := q.db.QueryRow(ctx, upsertExecutionAssertion,
		arg.OrgID,
		arg.ExecutionID,
		arg.AssertionIndex,
		arg.Type,
		arg.Status,
		arg.Expected,
		arg.Actual,
		arg.Message,
	)
	var i ExecutionAssertion
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ExecutionID,
		&i.AssertionIndex,
		&i.Type,
		&i.Status,
		&i.Expected,
		&i.Actual,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const upsertExecutionStep = `-- name: UpsertExecutionStep :one
INSERT INTO execution_steps (org_id, execution_id, step_index, action, target,
                             result, unstable, error_message, duration_ms,
                             started_at, finished_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9,
        $10, $11)
ON CONFLICT (execution_id, step_index) DO UPDATE
SET action = EXCLUDED.action,
    target = EXCLUDED.target,
    result = EXCLUDED.result,
    unstable = EXCLUDED.unstable,
    error_message = EXCLUDED.error_message,
    duration_ms = EXCLUDED.duration_ms,
    started_at = EXCLUDED.started_at,
    finished_at = EXCLUDED.finished_at
RETURNING id, org_id, execution_id, step_index, action, target, result, unstable, error_message, duration_ms, started_at, finished_at, created_at
`

type UpsertExecutionStepParams struct {
	OrgID        uuid.UUID
	ExecutionID  uuid.UUID
	StepIndex    int32
	Action       string
	Target       json.RawMessage
	Result       ExecutionResult
	Unstable     bool
	ErrorMessage string
	DurationMs   pgtype.Int4
	StartedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
}

func (q *Queries) UpsertExecutionStep(ctx context.Context, arg UpsertExecutionStepParams) (ExecutionStep, error) {
	row := q.db.QueryRow(ctx, upsertExecutionStep,
		arg.OrgID,
		arg.ExecutionID,
		arg.StepIndex,
		arg.Action,
		arg.Target,
		arg.Result,
		arg.Unstable,
		arg.ErrorMessage,
		arg.DurationMs,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i ExecutionStep
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ExecutionID,
		&i.StepIndex,
		&i.Action,
		&i.Target,
		&i.Result,
		&i.Unstable,
		&i.ErrorMessage,
		&i.DurationMs,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}
