// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: findings.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteFinding = `-- name: DeleteFinding :execrows
DELETE FROM findings WHERE org_id = $1 AND id = $2
`

type DeleteFindingParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) DeleteFinding(ctx context.Context, arg DeleteFindingParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFinding, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFinding = `-- name: GetFinding :one
SELECT id, org_id, run_id, execution_id, test_case_id, step_index, failure_class, root_cause, confidence, suggested_fix, created_at, updated_at FROM findings WHERE org_id = $1 AND id = $2
`

type GetFindingParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) GetFinding(ctx context.Context, arg GetFindingParams) (Finding, error) {
	row := q.db.QueryRow(ctx, getFinding, arg.OrgID, arg.ID)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RunID,
		&i.ExecutionID,
		&i.TestCaseID,
		&i.StepIndex,
		&i.FailureClass,
		&i.RootCause,
		&i.Confidence,
		&i.SuggestedFix,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkFindingEvidence = `-- name: LinkFindingEvidence :execrows
INSERT INTO finding_evidence (org_id, finding_id, artifact_id)
SELECT $1::uuid, $2::uuid, a.id
FROM unnest($3::uuid[]) AS a(id)
ON CONFLICT (finding_id, artifact_id) DO NOTHING
`

type LinkFindingEvidenceParams struct {
	OrgID       uuid.UUID
	FindingID   uuid.UUID
	ArtifactIds []uuid.UUID
}

func (q *Queries) LinkFindingEvidence(ctx context.Context, arg LinkFindingEvidenceParams) (int64, error) {
	result, err := q.db.Exec(ctx, linkFindingEvidence, arg.OrgID, arg.FindingID, arg.ArtifactIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listFindingEvidenceForRun = `-- name: ListFindingEvidenceForRun :many
SELECT fe.finding_id, a.id, a.org_id, a.run_id, a.execution_id, a.test_case_id, a.kind, a.name, a.storage_key, a.content_type, a.size_bytes, a.sha256, a.created_at
FROM finding_evidence fe
JOIN findings f ON f.id = fe.finding_id AND f.org_id = fe.org_id
JOIN artifacts a ON a.id = fe.artifact_id AND a.org_id = fe.org_id
WHERE fe.org_id = $1 AND f.run_id = $2
ORDER BY fe.finding_id, a.created_at
`

type ListFindingEvidenceForRunParams struct {
	OrgID uuid.UUID
	RunID uuid.UUID
}

type ListFindingEvidenceForRunRow struct {
	FindingID uuid.UUID
	Artifact  Artifact
}

// Findings with their evidence for a whole run in one query. Fetching evidence
// per finding would be the N+1 the join table exists to avoid.
func (q *Queries) ListFindingEvidenceForRun(ctx context.Context, arg ListFindingEvidenceForRunParams) ([]ListFindingEvidenceForRunRow, error) {
	rows, err := q.db.Query(ctx, listFindingEvidenceForRun, arg.OrgID, arg.RunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFindingEvidenceForRunRow{}
	for rows.Next() {
		var i ListFindingEvidenceForRunRow
		if err := rows.Scan(
			&i.FindingID,
			&i.Artifact.ID,
			&i.Artifact.OrgID,
			&i.Artifact.RunID,
			&i.Artifact.ExecutionID,
			&i.Artifact.TestCaseID,
			&i.Artifact.Kind,
			&i.Artifact.Name,
			&i.Artifact.StorageKey,
			&i.Artifact.ContentType,
			&i.Artifact.SizeBytes,
			&i.Artifact.Sha256,
			&i.Artifact.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFindingsForRun = `-- name: ListFindingsForRun :many
SELECT id, org_id, run_id, execution_id, test_case_id, step_index, failure_class, root_cause, confidence, suggested_fix, created_at, updated_at FROM findings
WHERE org_id = $1 AND run_id = $2
ORDER BY confidence DESC, created_at
`

type ListFindingsForRunParams struct {
	OrgID uuid.UUID
	RunID uuid.UUID
}

func (q *Queries) ListFindingsForRun(ctx context.Context, arg ListFindingsForRunParams) ([]Finding, error) {
	rows, err := q.db.Query(ctx, listFindingsForRun, arg.OrgID, arg.RunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Finding{}
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.RunID,
			&i.ExecutionID,
			&i.TestCaseID,
			&i.StepIndex,
			&i.FailureClass,
			&i.RootCause,
			&i.Confidence,
			&i.SuggestedFix,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summarizeFindingsByClass = `-- name: SummarizeFindingsByClass :many
SELECT f.failure_class, count(*) AS total
FROM findings f
JOIN runs r ON r.id = f.run_id AND r.org_id = f.org_id
WHERE f.org_id = $1
  AND r.project_id = $2
  AND f.created_at >= now() - $3::interval
GROUP BY f.failure_class
ORDER BY total DESC
`

type SummarizeFindingsByClassParams struct {
	OrgID      uuid.UUID
	ProjectID  uuid.UUID
	WindowSize pgtype.Interval
}

type SummarizeFindingsByClassRow struct {
	FailureClass FailureClass
	Total        int64
}

// Failure-class breakdown for a project's recent runs.
func (q *Queries) SummarizeFindingsByClass(ctx context.Context, arg SummarizeFindingsByClassParams) ([]SummarizeFindingsByClassRow, error) {
	rows, err := q.db.Query(ctx, summarizeFindingsByClass, arg.OrgID, arg.ProjectID, arg.WindowSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SummarizeFindingsByClassRow{}
	for rows.Next() {
		var i SummarizeFindingsByClassRow
		if err := rows.Scan(&i.FailureClass, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkFindingEvidence = `-- name: UnlinkFindingEvidence :execrows
DELETE FROM finding_evidence
WHERE org_id = $1 AND finding_id = $2 AND artifact_id = $3
`

type UnlinkFindingEvidenceParams struct {
	OrgID      uuid.UUID
	FindingID  uuid.UUID
	ArtifactID uuid.UUID
}

func (q *Queries) UnlinkFindingEvidence(ctx context.Context, arg UnlinkFindingEvidenceParams) (int64, error) {
	result, err := q.db.Exec(ctx, unlinkFindingEvidence, arg.OrgID, arg.FindingID, arg.ArtifactID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertFinding = `-- name: UpsertFinding :one

INSERT INTO findings (org_id, run_id, execution_id, test_case_id, step_index,
                      failure_class, root_cause, confidence, suggested_fix)
VALUES ($1, $2, $7, $8,
        $9, $3, $4, $5, $6)
ON CONFLICT (execution_id) DO UPDATE
SET failure_class = EXCLUDED.failure_class,
    root_cause = EXCLUDED.root_cause,
    confidence = EXCLUDED.confidence,
    suggested_fix = EXCLUDED.suggested_fix,
    step_index = EXCLUDED.step_index
RETURNING id, org_id, run_id, execution_id, test_case_id, step_index, failure_class, root_cause, confidence, suggested_fix, created_at, updated_at
`

type UpsertFindingParams struct {
	OrgID        uuid.UUID
	RunID        uuid.UUID
	FailureClass FailureClass
	RootCause    string
	Confidence   float64
	SuggestedFix string
	ExecutionID  uuid.NullUUID
	TestCaseID   uuid.NullUUID
	StepIndex    pgtype.Int4
}

// What the failure analyst concluded, and the evidence it cited.
// One finding per execution; re-analysis updates in place so regenerating a
// report does not stack duplicates.
func (q *Queries) UpsertFinding(ctx context.Context, arg UpsertFindingParams) (Finding, error) {
	row := q.db.QueryRow(ctx, upsertFinding,
		arg.OrgID,
		arg.RunID,
		arg.FailureClass,
		arg.RootCause,
		arg.Confidence,
		arg.SuggestedFix,
		arg.ExecutionID,
		arg.TestCaseID,
		arg.StepIndex,
	)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RunID,
		&i.ExecutionID,
		&i.TestCaseID,
		&i.StepIndex,
		&i.FailureClass,
		&i.RootCause,
		&i.Confidence,
		&i.SuggestedFix,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
