// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invites.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvite = `-- name: AcceptInvite :one
UPDATE invites
SET accepted_at = now(), accepted_by = $1
WHERE token_hash = $2
  AND accepted_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > now()
RETURNING id, org_id, email, role, token_hash, invited_by, expires_at, accepted_at, accepted_by, revoked_at, created_at, updated_at
`

type AcceptInviteParams struct {
	AcceptedBy uuid.NullUUID
	TokenHash  []byte
}

// The claim. `accepted_at IS NULL` in the predicate plus the row lock the
// UPDATE takes means two concurrent accepts of the same token produce exactly
// one winner, with no read-then-write window in between.
func (q *Queries) AcceptInvite(ctx context.Context, arg AcceptInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, acceptInvite, arg.AcceptedBy, arg.TokenHash)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createInvite = `-- name: CreateInvite :one

INSERT INTO invites (org_id, email, role, token_hash, invited_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, org_id, email, role, token_hash, invited_by, expires_at, accepted_at, accepted_by, revoked_at, created_at, updated_at
`

type CreateInviteParams struct {
	OrgID     uuid.UUID
	Email     string
	Role      MembershipRole
	TokenHash []byte
	InvitedBy uuid.NullUUID
	ExpiresAt pgtype.Timestamptz
}

// Organization invites. Tenancy layer, like sessions and runtime_tokens: the
// accept path is how an org_id is established for the invitee, so it looks the
// row up by token hash and cannot take an org_id parameter.
func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.OrgID,
		arg.Email,
		arg.Role,
		arg.TokenHash,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredInvites = `-- name: DeleteExpiredInvites :execrows
DELETE FROM invites
WHERE accepted_at IS NULL AND expires_at < now() - $1::interval
`

// Housekeeping: an expired invite can never be accepted again.
func (q *Queries) DeleteExpiredInvites(ctx context.Context, grace pgtype.Interval) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredInvites, grace)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLiveInviteByTokenHash = `-- name: GetLiveInviteByTokenHash :one
SELECT id, org_id, email, role, token_hash, invited_by, expires_at, accepted_at, accepted_by, revoked_at, created_at, updated_at FROM invites
WHERE token_hash = $1
  AND accepted_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > now()
`

// The acceptance read. Expiry, revocation and prior acceptance are filtered
// here rather than in Go so no caller can forget one of the three.
func (q *Queries) GetLiveInviteByTokenHash(ctx context.Context, tokenHash []byte) (Invite, error) {
	row := q.db.QueryRow(ctx, getLiveInviteByTokenHash, tokenHash)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInvites = `-- name: ListInvites :many
SELECT id, org_id, email, role, token_hash, invited_by, expires_at, accepted_at, accepted_by, revoked_at, created_at, updated_at FROM invites
WHERE org_id = $1
  AND accepted_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > now()
ORDER BY created_at DESC
`

func (q *Queries) ListInvites(ctx context.Context, orgID uuid.UUID) ([]Invite, error) {
	rows, err := q.db.Query(ctx, listInvites, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invite{}
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Email,
			&i.Role,
			&i.TokenHash,
			&i.InvitedBy,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.AcceptedBy,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeInvite = `-- name: RevokeInvite :execrows
UPDATE invites
SET revoked_at = now()
WHERE org_id = $1 AND id = $2 AND accepted_at IS NULL AND revoked_at IS NULL
`

type RevokeInviteParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) RevokeInvite(ctx context.Context, arg RevokeInviteParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeInvite, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeLiveInvitesForEmail = `-- name: RevokeLiveInvitesForEmail :execrows
UPDATE invites
SET revoked_at = now()
WHERE org_id = $1
  AND email = $2
  AND accepted_at IS NULL
  AND revoked_at IS NULL
`

type RevokeLiveInvitesForEmailParams struct {
	OrgID uuid.UUID
	Email string
}

// Re-inviting somebody rotates the token instead of leaving two valid ones
// outstanding. Run inside the same transaction as CreateInvite, otherwise the
// partial unique index rejects the new row.
func (q *Queries) RevokeLiveInvitesForEmail(ctx context.Context, arg RevokeLiveInvitesForEmailParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeLiveInvitesForEmail, arg.OrgID, arg.Email)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
