// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AgentProvider string

const (
	AgentProviderClaude      AgentProvider = "claude"
	AgentProviderOpencode    AgentProvider = "opencode"
	AgentProviderAntigravity AgentProvider = "antigravity"
)

func (e *AgentProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AgentProvider(s)
	case string:
		*e = AgentProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for AgentProvider: %T", src)
	}
	return nil
}

type NullAgentProvider struct {
	AgentProvider AgentProvider
	Valid         bool // Valid is true if AgentProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAgentProvider) Scan(value interface{}) error {
	if value == nil {
		ns.AgentProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AgentProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAgentProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AgentProvider), nil
}

type ArtifactKind string

const (
	ArtifactKindScreenshot ArtifactKind = "screenshot"
	ArtifactKindVideo      ArtifactKind = "video"
	ArtifactKindTrace      ArtifactKind = "trace"
	ArtifactKindNetwork    ArtifactKind = "network"
	ArtifactKindConsole    ArtifactKind = "console"
	ArtifactKindDom        ArtifactKind = "dom"
	ArtifactKindReport     ArtifactKind = "report"
)

func (e *ArtifactKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ArtifactKind(s)
	case string:
		*e = ArtifactKind(s)
	default:
		return fmt.Errorf("unsupported scan type for ArtifactKind: %T", src)
	}
	return nil
}

type NullArtifactKind struct {
	ArtifactKind ArtifactKind
	Valid        bool // Valid is true if ArtifactKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullArtifactKind) Scan(value interface{}) error {
	if value == nil {
		ns.ArtifactKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ArtifactKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullArtifactKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ArtifactKind), nil
}

type ExecutionResult string

const (
	ExecutionResultPending ExecutionResult = "pending"
	ExecutionResultRunning ExecutionResult = "running"
	ExecutionResultPass    ExecutionResult = "pass"
	ExecutionResultFail    ExecutionResult = "fail"
	ExecutionResultSkipped ExecutionResult = "skipped"
	ExecutionResultError   ExecutionResult = "error"
)

func (e *ExecutionResult) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExecutionResult(s)
	case string:
		*e = ExecutionResult(s)
	default:
		return fmt.Errorf("unsupported scan type for ExecutionResult: %T", src)
	}
	return nil
}

type NullExecutionResult struct {
	ExecutionResult ExecutionResult
	Valid           bool // Valid is true if ExecutionResult is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExecutionResult) Scan(value interface{}) error {
	if value == nil {
		ns.ExecutionResult, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExecutionResult.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExecutionResult) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExecutionResult), nil
}

type FailureClass string

const (
	FailureClassPRODUCTBUG          FailureClass = "PRODUCT_BUG"
	FailureClassTESTBUG             FailureClass = "TEST_BUG"
	FailureClassENVIRONMENTERROR    FailureClass = "ENVIRONMENT_ERROR"
	FailureClassNETWORKERROR        FailureClass = "NETWORK_ERROR"
	FailureClassAUTHENTICATIONERROR FailureClass = "AUTHENTICATION_ERROR"
	FailureClassTIMEOUT             FailureClass = "TIMEOUT"
	FailureClassUNKNOWN             FailureClass = "UNKNOWN"
)

func (e *FailureClass) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FailureClass(s)
	case string:
		*e = FailureClass(s)
	default:
		return fmt.Errorf("unsupported scan type for FailureClass: %T", src)
	}
	return nil
}

type NullFailureClass struct {
	FailureClass FailureClass
	Valid        bool // Valid is true if FailureClass is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFailureClass) Scan(value interface{}) error {
	if value == nil {
		ns.FailureClass, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FailureClass.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFailureClass) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FailureClass), nil
}

type MembershipRole string

const (
	MembershipRoleOwner  MembershipRole = "owner"
	MembershipRoleAdmin  MembershipRole = "admin"
	MembershipRoleMember MembershipRole = "member"
	MembershipRoleViewer MembershipRole = "viewer"
)

func (e *MembershipRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MembershipRole(s)
	case string:
		*e = MembershipRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MembershipRole: %T", src)
	}
	return nil
}

type NullMembershipRole struct {
	MembershipRole MembershipRole
	Valid          bool // Valid is true if MembershipRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMembershipRole) Scan(value interface{}) error {
	if value == nil {
		ns.MembershipRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MembershipRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMembershipRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MembershipRole), nil
}

type RunEventLevel string

const (
	RunEventLevelDebug RunEventLevel = "debug"
	RunEventLevelInfo  RunEventLevel = "info"
	RunEventLevelWarn  RunEventLevel = "warn"
	RunEventLevelError RunEventLevel = "error"
)

func (e *RunEventLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RunEventLevel(s)
	case string:
		*e = RunEventLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for RunEventLevel: %T", src)
	}
	return nil
}

type NullRunEventLevel struct {
	RunEventLevel RunEventLevel
	Valid         bool // Valid is true if RunEventLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRunEventLevel) Scan(value interface{}) error {
	if value == nil {
		ns.RunEventLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RunEventLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRunEventLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RunEventLevel), nil
}

type RunMode string

const (
	RunModeDiscover RunMode = "discover"
	RunModePlan     RunMode = "plan"
	RunModeExecute  RunMode = "execute"
	RunModeFull     RunMode = "full"
)

func (e *RunMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RunMode(s)
	case string:
		*e = RunMode(s)
	default:
		return fmt.Errorf("unsupported scan type for RunMode: %T", src)
	}
	return nil
}

type NullRunMode struct {
	RunMode RunMode
	Valid   bool // Valid is true if RunMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRunMode) Scan(value interface{}) error {
	if value == nil {
		ns.RunMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RunMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRunMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RunMode), nil
}

type RunStatus string

const (
	RunStatusQueued    RunStatus = "queued"
	RunStatusAssigned  RunStatus = "assigned"
	RunStatusRunning   RunStatus = "running"
	RunStatusPassed    RunStatus = "passed"
	RunStatusFailed    RunStatus = "failed"
	RunStatusCancelled RunStatus = "cancelled"
	RunStatusError     RunStatus = "error"
)

func (e *RunStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RunStatus(s)
	case string:
		*e = RunStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RunStatus: %T", src)
	}
	return nil
}

type NullRunStatus struct {
	RunStatus RunStatus
	Valid     bool // Valid is true if RunStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRunStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RunStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RunStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRunStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RunStatus), nil
}

type TestCaseStatus string

const (
	TestCaseStatusDraft    TestCaseStatus = "draft"
	TestCaseStatusApproved TestCaseStatus = "approved"
	TestCaseStatusArchived TestCaseStatus = "archived"
)

func (e *TestCaseStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TestCaseStatus(s)
	case string:
		*e = TestCaseStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TestCaseStatus: %T", src)
	}
	return nil
}

type NullTestCaseStatus struct {
	TestCaseStatus TestCaseStatus
	Valid          bool // Valid is true if TestCaseStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTestCaseStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TestCaseStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TestCaseStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTestCaseStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TestCaseStatus), nil
}

type TestCategory string

const (
	TestCategoryFunctional    TestCategory = "functional"
	TestCategoryValidation    TestCategory = "validation"
	TestCategoryNavigation    TestCategory = "navigation"
	TestCategoryUiBehavior    TestCategory = "ui_behavior"
	TestCategoryErrorHandling TestCategory = "error_handling"
)

func (e *TestCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TestCategory(s)
	case string:
		*e = TestCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for TestCategory: %T", src)
	}
	return nil
}

type NullTestCategory struct {
	TestCategory TestCategory
	Valid        bool // Valid is true if TestCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTestCategory) Scan(value interface{}) error {
	if value == nil {
		ns.TestCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TestCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTestCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TestCategory), nil
}

type TestPriority string

const (
	TestPriorityCritical TestPriority = "critical"
	TestPriorityHigh     TestPriority = "high"
	TestPriorityMedium   TestPriority = "medium"
	TestPriorityLow      TestPriority = "low"
)

func (e *TestPriority) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TestPriority(s)
	case string:
		*e = TestPriority(s)
	default:
		return fmt.Errorf("unsupported scan type for TestPriority: %T", src)
	}
	return nil
}

type NullTestPriority struct {
	TestPriority TestPriority
	Valid        bool // Valid is true if TestPriority is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTestPriority) Scan(value interface{}) error {
	if value == nil {
		ns.TestPriority, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TestPriority.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTestPriority) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TestPriority), nil
}

type Artifact struct {
	ID          uuid.UUID
	OrgID       uuid.UUID
	RunID       uuid.UUID
	ExecutionID uuid.NullUUID
	TestCaseID  uuid.NullUUID
	Kind        ArtifactKind
	Name        string
	StorageKey  string
	ContentType string
	SizeBytes   pgtype.Int8
	Sha256      []byte
	CreatedAt   pgtype.Timestamptz
}

type Element struct {
	ID            uuid.UUID
	OrgID         uuid.UUID
	PageID        uuid.UUID
	Ref           string
	Kind          string
	Label         string
	Locators      json.RawMessage
	LastSeenRunID uuid.NullUUID
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type Execution struct {
	ID              uuid.UUID
	OrgID           uuid.UUID
	RunID           uuid.UUID
	TestCaseID      uuid.UUID
	TestCaseVersion int32
	Result          ExecutionResult
	FailureClass    NullFailureClass
	ErrorMessage    string
	DurationMs      pgtype.Int4
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type ExecutionAssertion struct {
	ID             uuid.UUID
	OrgID          uuid.UUID
	ExecutionID    uuid.UUID
	AssertionIndex int32
	Type           string
	Status         ExecutionResult
	Expected       string
	Actual         string
	Message        string
	CreatedAt      pgtype.Timestamptz
}

type ExecutionStep struct {
	ID           uuid.UUID
	OrgID        uuid.UUID
	ExecutionID  uuid.UUID
	StepIndex    int32
	Action       string
	Target       json.RawMessage
	Result       ExecutionResult
	Unstable     bool
	ErrorMessage string
	DurationMs   pgtype.Int4
	StartedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

type Finding struct {
	ID                 uuid.UUID
	OrgID              uuid.UUID
	RunID              uuid.UUID
	ExecutionID        uuid.NullUUID
	TestCaseID         uuid.NullUUID
	StepIndex          pgtype.Int4
	FailureClass       FailureClass
	Summary            string
	RootCause          string
	Confidence         float64
	SuggestedFix       string
	AnalyzedByProvider NullAgentProvider
	AnalyzedByVersion  string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type FindingEvidence struct {
	OrgID      uuid.UUID
	FindingID  uuid.UUID
	ArtifactID uuid.UUID
	CreatedAt  pgtype.Timestamptz
}

type Invite struct {
	ID         uuid.UUID
	OrgID      uuid.UUID
	Email      string
	Role       MembershipRole
	TokenHash  []byte
	InvitedBy  uuid.NullUUID
	ExpiresAt  pgtype.Timestamptz
	AcceptedAt pgtype.Timestamptz
	AcceptedBy uuid.NullUUID
	RevokedAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Membership struct {
	OrgID     uuid.UUID
	UserID    uuid.UUID
	Role      MembershipRole
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Organization struct {
	ID        uuid.UUID
	Name      string
	Slug      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Page struct {
	ID             uuid.UUID
	OrgID          uuid.UUID
	ProjectID      uuid.UUID
	Ref            string
	Path           string
	Title          string
	AuthRequired   bool
	FirstSeenRunID uuid.NullUUID
	LastSeenRunID  uuid.NullUUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type PairingCode struct {
	ID         uuid.UUID
	OrgID      uuid.UUID
	CodeHash   []byte
	RuntimeID  uuid.NullUUID
	CreatedBy  uuid.NullUUID
	ExpiresAt  pgtype.Timestamptz
	ConsumedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type Project struct {
	ID         uuid.UUID
	OrgID      uuid.UUID
	Name       string
	BaseURL    string
	ArchivedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type ProjectFixture struct {
	ID          uuid.UUID
	OrgID       uuid.UUID
	ProjectID   uuid.UUID
	Name        string
	Description string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Run struct {
	ID             uuid.UUID
	OrgID          uuid.UUID
	ProjectID      uuid.UUID
	RuntimeID      uuid.NullUUID
	Mode           RunMode
	Status         RunStatus
	Phase          string
	IdempotencyKey pgtype.Text
	Attempts       int32
	HeartbeatAt    pgtype.Timestamptz
	TotalCount     int32
	PassedCount    int32
	FailedCount    int32
	SkippedCount   int32
	ErrorCount     int32
	ErrorCode      string
	ErrorMessage   string
	CreatedBy      uuid.NullUUID
	AssignedAt     pgtype.Timestamptz
	StartedAt      pgtype.Timestamptz
	FinishedAt     pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type RunEvent struct {
	ID        int64
	OrgID     uuid.UUID
	RunID     uuid.UUID
	Seq       int64
	Phase     string
	Level     RunEventLevel
	Code      string
	Message   string
	Data      json.RawMessage
	Ts        pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Runtime struct {
	ID         uuid.UUID
	OrgID      uuid.UUID
	Name       string
	Version    string
	Browsers   json.RawMessage
	Agents     json.RawMessage
	LastSeenAt pgtype.Timestamptz
	DisabledAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	// Machine facts reported at pairing time (hostname, os, arch). Rendered, never queried into.
	HostInfo json.RawMessage
}

type RuntimeToken struct {
	ID         uuid.UUID
	OrgID      uuid.UUID
	RuntimeID  uuid.UUID
	TokenHash  []byte
	CreatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

type Session struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	TokenHash  []byte
	ExpiresAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type TestCase struct {
	ID             uuid.UUID
	OrgID          uuid.UUID
	ProjectID      uuid.UUID
	Ref            string
	Name           string
	Priority       TestPriority
	Category       TestCategory
	Status         TestCaseStatus
	Payload        json.RawMessage
	CurrentVersion int32
	SourceRunID    uuid.NullUUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type TestCaseVersion struct {
	ID         uuid.UUID
	OrgID      uuid.UUID
	TestCaseID uuid.UUID
	Version    int32
	Payload    json.RawMessage
	Status     TestCaseStatus
	CreatedAt  pgtype.Timestamptz
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	Name         string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Workflow struct {
	ID              uuid.UUID
	OrgID           uuid.UUID
	ProjectID       uuid.UUID
	Ref             string
	Name            string
	Path            json.RawMessage
	ExpectedOutcome string
	LastSeenRunID   uuid.NullUUID
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}
