// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pages.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const deletePage = `-- name: DeletePage :execrows
DELETE FROM pages WHERE org_id = $1 AND id = $2
`

type DeletePageParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) DeletePage(ctx context.Context, arg DeletePageParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePage, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPage = `-- name: GetPage :one
SELECT id, org_id, project_id, ref, path, title, auth_required, first_seen_run_id, last_seen_run_id, created_at, updated_at FROM pages WHERE org_id = $1 AND id = $2
`

type GetPageParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) GetPage(ctx context.Context, arg GetPageParams) (Page, error) {
	row := q.db.QueryRow(ctx, getPage, arg.OrgID, arg.ID)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Ref,
		&i.Path,
		&i.Title,
		&i.AuthRequired,
		&i.FirstSeenRunID,
		&i.LastSeenRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPageByRef = `-- name: GetPageByRef :one
SELECT id, org_id, project_id, ref, path, title, auth_required, first_seen_run_id, last_seen_run_id, created_at, updated_at FROM pages WHERE org_id = $1 AND project_id = $2 AND ref = $3
`

type GetPageByRefParams struct {
	OrgID     uuid.UUID
	ProjectID uuid.UUID
	Ref       string
}

func (q *Queries) GetPageByRef(ctx context.Context, arg GetPageByRefParams) (Page, error) {
	row := q.db.QueryRow(ctx, getPageByRef, arg.OrgID, arg.ProjectID, arg.Ref)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Ref,
		&i.Path,
		&i.Title,
		&i.AuthRequired,
		&i.FirstSeenRunID,
		&i.LastSeenRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPages = `-- name: ListPages :many
SELECT id, org_id, project_id, ref, path, title, auth_required, first_seen_run_id, last_seen_run_id, created_at, updated_at FROM pages
WHERE org_id = $1 AND project_id = $2
ORDER BY path
`

type ListPagesParams struct {
	OrgID     uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) ListPages(ctx context.Context, arg ListPagesParams) ([]Page, error) {
	rows, err := q.db.Query(ctx, listPages, arg.OrgID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Page{}
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.Ref,
			&i.Path,
			&i.Title,
			&i.AuthRequired,
			&i.FirstSeenRunID,
			&i.LastSeenRunID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStalePages = `-- name: ListStalePages :many
SELECT id, org_id, project_id, ref, path, title, auth_required, first_seen_run_id, last_seen_run_id, created_at, updated_at FROM pages
WHERE org_id = $1
  AND project_id = $2
  AND (last_seen_run_id IS NULL OR last_seen_run_id <> $3)
ORDER BY path
`

type ListStalePagesParams struct {
	OrgID     uuid.UUID
	ProjectID uuid.UUID
	RunID     uuid.NullUUID
}

// Stale-map filter: pages not observed by the given discovery run. Callers
// report these rather than deleting them, because live test cases may still
// reference them.
func (q *Queries) ListStalePages(ctx context.Context, arg ListStalePagesParams) ([]Page, error) {
	rows, err := q.db.Query(ctx, listStalePages, arg.OrgID, arg.ProjectID, arg.RunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Page{}
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.Ref,
			&i.Path,
			&i.Title,
			&i.AuthRequired,
			&i.FirstSeenRunID,
			&i.LastSeenRunID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPage = `-- name: UpsertPage :one
INSERT INTO pages (org_id, project_id, ref, path, title, auth_required,
                   first_seen_run_id, last_seen_run_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $7)
ON CONFLICT (project_id, ref) DO UPDATE
SET path = EXCLUDED.path,
    title = EXCLUDED.title,
    auth_required = EXCLUDED.auth_required,
    -- Discovery never resets first_seen_run_id: it is what dates a page.
    last_seen_run_id = coalesce(EXCLUDED.last_seen_run_id, pages.last_seen_run_id)
RETURNING id, org_id, project_id, ref, path, title, auth_required, first_seen_run_id, last_seen_run_id, created_at, updated_at
`

type UpsertPageParams struct {
	OrgID        uuid.UUID
	ProjectID    uuid.UUID
	Ref          string
	Path         string
	Title        string
	AuthRequired bool
	RunID        uuid.NullUUID
}

func (q *Queries) UpsertPage(ctx context.Context, arg UpsertPageParams) (Page, error) {
	row := q.db.QueryRow(ctx, upsertPage,
		arg.OrgID,
		arg.ProjectID,
		arg.Ref,
		arg.Path,
		arg.Title,
		arg.AuthRequired,
		arg.RunID,
	)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Ref,
		&i.Path,
		&i.Title,
		&i.AuthRequired,
		&i.FirstSeenRunID,
		&i.LastSeenRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
