// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pairing_codes.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumePairingCode = `-- name: ConsumePairingCode :one
UPDATE pairing_codes
SET consumed_at = now(), runtime_id = $1
WHERE code_hash = $2
  AND consumed_at IS NULL
  AND expires_at > now()
RETURNING id, org_id, code_hash, runtime_id, created_by, expires_at, consumed_at, created_at
`

type ConsumePairingCodeParams struct {
	RuntimeID uuid.NullUUID
	CodeHash  []byte
}

// Redemption. The UPDATE is the claim: `consumed_at IS NULL` in the predicate
// plus the row lock the UPDATE takes means two daemons racing on the same code
// produce exactly one winner, with no read-then-write window in between.
func (q *Queries) ConsumePairingCode(ctx context.Context, arg ConsumePairingCodeParams) (PairingCode, error) {
	row := q.db.QueryRow(ctx, consumePairingCode, arg.RuntimeID, arg.CodeHash)
	var i PairingCode
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CodeHash,
		&i.RuntimeID,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createPairingCode = `-- name: CreatePairingCode :one

INSERT INTO pairing_codes (org_id, code_hash, created_by, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, code_hash, runtime_id, created_by, expires_at, consumed_at, created_at
`

type CreatePairingCodeParams struct {
	OrgID     uuid.UUID
	CodeHash  []byte
	CreatedBy uuid.NullUUID
	ExpiresAt pgtype.Timestamptz
}

// One-time daemon pairing codes. Tenancy layer, like runtime_tokens.
func (q *Queries) CreatePairingCode(ctx context.Context, arg CreatePairingCodeParams) (PairingCode, error) {
	row := q.db.QueryRow(ctx, createPairingCode,
		arg.OrgID,
		arg.CodeHash,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i PairingCode
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CodeHash,
		&i.RuntimeID,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredPairingCodes = `-- name: DeleteExpiredPairingCodes :execrows
DELETE FROM pairing_codes WHERE consumed_at IS NULL AND expires_at < now()
`

func (q *Queries) DeleteExpiredPairingCodes(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredPairingCodes)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLivePairingCodeByHash = `-- name: GetLivePairingCodeByHash :one
SELECT id, org_id, code_hash, runtime_id, created_by, expires_at, consumed_at, created_at FROM pairing_codes
WHERE code_hash = $1
  AND consumed_at IS NULL
  AND expires_at > now()
`

// Redemption needs the org before it can create the runtime the code will be
// consumed against, so it reads the live row first. Expiry and prior
// consumption are filtered here; ConsumePairingCode is still the atomic claim.
func (q *Queries) GetLivePairingCodeByHash(ctx context.Context, codeHash []byte) (PairingCode, error) {
	row := q.db.QueryRow(ctx, getLivePairingCodeByHash, codeHash)
	var i PairingCode
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CodeHash,
		&i.RuntimeID,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPairingCodeByHash = `-- name: GetPairingCodeByHash :one
SELECT id, org_id, code_hash, runtime_id, created_by, expires_at, consumed_at, created_at FROM pairing_codes WHERE code_hash = $1
`

func (q *Queries) GetPairingCodeByHash(ctx context.Context, codeHash []byte) (PairingCode, error) {
	row := q.db.QueryRow(ctx, getPairingCodeByHash, codeHash)
	var i PairingCode
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CodeHash,
		&i.RuntimeID,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listLivePairingCodes = `-- name: ListLivePairingCodes :many
SELECT id, org_id, code_hash, runtime_id, created_by, expires_at, consumed_at, created_at FROM pairing_codes
WHERE org_id = $1 AND consumed_at IS NULL AND expires_at > now()
ORDER BY created_at DESC
`

// The org's outstanding codes, so the UI can show "a pairing code is waiting"
// without ever being able to show the code itself.
func (q *Queries) ListLivePairingCodes(ctx context.Context, orgID uuid.UUID) ([]PairingCode, error) {
	rows, err := q.db.Query(ctx, listLivePairingCodes, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PairingCode{}
	for rows.Next() {
		var i PairingCode
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.CodeHash,
			&i.RuntimeID,
			&i.CreatedBy,
			&i.ExpiresAt,
			&i.ConsumedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
