// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveProject = `-- name: ArchiveProject :one
UPDATE projects SET archived_at = now()
WHERE org_id = $1 AND id = $2 AND archived_at IS NULL
RETURNING id, org_id, name, base_url, archived_at, created_at, updated_at
`

type ArchiveProjectParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) ArchiveProject(ctx context.Context, arg ArchiveProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, archiveProject, arg.OrgID, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.BaseURL,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countProjects = `-- name: CountProjects :one
SELECT count(*) FROM projects
WHERE org_id = $1
  AND ($2::boolean OR archived_at IS NULL)
`

type CountProjectsParams struct {
	OrgID           uuid.UUID
	IncludeArchived bool
}

func (q *Queries) CountProjects(ctx context.Context, arg CountProjectsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProjects, arg.OrgID, arg.IncludeArchived)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (org_id, name, base_url)
VALUES ($1, $2, $3)
RETURNING id, org_id, name, base_url, archived_at, created_at, updated_at
`

type CreateProjectParams struct {
	OrgID   uuid.UUID
	Name    string
	BaseURL string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.OrgID, arg.Name, arg.BaseURL)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.BaseURL,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :execrows
DELETE FROM projects WHERE org_id = $1 AND id = $2
`

type DeleteProjectParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProject, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProject = `-- name: GetProject :one
SELECT id, org_id, name, base_url, archived_at, created_at, updated_at FROM projects WHERE org_id = $1 AND id = $2
`

type GetProjectParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) GetProject(ctx context.Context, arg GetProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, arg.OrgID, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.BaseURL,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByName = `-- name: GetProjectByName :one
SELECT id, org_id, name, base_url, archived_at, created_at, updated_at FROM projects WHERE org_id = $1 AND name = $2
`

type GetProjectByNameParams struct {
	OrgID uuid.UUID
	Name  string
}

// Retry path for CreateProject: on a unique violation the service reads the
// existing row back instead of surfacing a 409 for a duplicate submit.
func (q *Queries) GetProjectByName(ctx context.Context, arg GetProjectByNameParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByName, arg.OrgID, arg.Name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.BaseURL,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, org_id, name, base_url, archived_at, created_at, updated_at FROM projects
WHERE org_id = $1
  AND ($4::boolean OR archived_at IS NULL)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListProjectsParams struct {
	OrgID           uuid.UUID
	Limit           int32
	Offset          int32
	IncludeArchived bool
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects,
		arg.OrgID,
		arg.Limit,
		arg.Offset,
		arg.IncludeArchived,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.BaseURL,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = coalesce($3, name),
    base_url = coalesce($4, base_url)
WHERE org_id = $1 AND id = $2
RETURNING id, org_id, name, base_url, archived_at, created_at, updated_at
`

type UpdateProjectParams struct {
	OrgID   uuid.UUID
	ID      uuid.UUID
	Name    pgtype.Text
	BaseURL pgtype.Text
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.OrgID,
		arg.ID,
		arg.Name,
		arg.BaseURL,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.BaseURL,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
