// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_fixtures.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const deleteProjectFixture = `-- name: DeleteProjectFixture :execrows
DELETE FROM project_fixtures WHERE org_id = $1 AND project_id = $2 AND name = $3
`

type DeleteProjectFixtureParams struct {
	OrgID     uuid.UUID
	ProjectID uuid.UUID
	Name      string
}

func (q *Queries) DeleteProjectFixture(ctx context.Context, arg DeleteProjectFixtureParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProjectFixture, arg.OrgID, arg.ProjectID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listProjectFixtureNames = `-- name: ListProjectFixtureNames :many
SELECT name FROM project_fixtures
WHERE org_id = $1 AND project_id = $2
ORDER BY name
`

type ListProjectFixtureNamesParams struct {
	OrgID     uuid.UUID
	ProjectID uuid.UUID
}

// The plan-ingest read: names only, one statement, no row objects to build.
func (q *Queries) ListProjectFixtureNames(ctx context.Context, arg ListProjectFixtureNamesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listProjectFixtureNames, arg.OrgID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectFixtures = `-- name: ListProjectFixtures :many
SELECT id, org_id, project_id, name, description, created_at, updated_at FROM project_fixtures
WHERE org_id = $1 AND project_id = $2
ORDER BY name
`

type ListProjectFixturesParams struct {
	OrgID     uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) ListProjectFixtures(ctx context.Context, arg ListProjectFixturesParams) ([]ProjectFixture, error) {
	rows, err := q.db.Query(ctx, listProjectFixtures, arg.OrgID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectFixture{}
	for rows.Next() {
		var i ProjectFixture
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProjectFixture = `-- name: UpsertProjectFixture :one

INSERT INTO project_fixtures (org_id, project_id, name, description)
VALUES ($1, $2, $3, $4)
ON CONFLICT (project_id, name) DO UPDATE
SET description = EXCLUDED.description
RETURNING id, org_id, project_id, name, description, created_at, updated_at
`

type UpsertProjectFixtureParams struct {
	OrgID       uuid.UUID
	ProjectID   uuid.UUID
	Name        string
	Description string
}

// Fixture names. There is deliberately no query here that returns a
// credential, because there is no column that holds one.
// Registering the same fixture twice is the retry this upsert exists for.
func (q *Queries) UpsertProjectFixture(ctx context.Context, arg UpsertProjectFixtureParams) (ProjectFixture, error) {
	row := q.db.QueryRow(ctx, upsertProjectFixture,
		arg.OrgID,
		arg.ProjectID,
		arg.Name,
		arg.Description,
	)
	var i ProjectFixture
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
