// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// The claim. `accepted_at IS NULL` in the predicate plus the row lock the
	// UPDATE takes means two concurrent accepts of the same token produce exactly
	// one winner, with no read-then-write window in between.
	AcceptInvite(ctx context.Context, arg AcceptInviteParams) (Invite, error)
	// The run event stream. Delivery from the daemon is at-least-once, so every
	// write here is idempotent on (run_id, seq).
	// Returns 1 when the event was new and 0 when it was a redelivery, which is
	// what the WebSocket fan-out uses to decide whether to broadcast.
	AppendRunEvent(ctx context.Context, arg AppendRunEventParams) (int64, error)
	// Bulk form for a daemon flushing its backlog after a reconnect: one pgx
	// batch instead of a round trip per event, deduped by the same unique index.
	AppendRunEventBatch(ctx context.Context, arg []AppendRunEventBatchParams) *AppendRunEventBatchBatchResults
	ArchiveProject(ctx context.Context, arg ArchiveProjectParams) (Project, error)
	CancelRun(ctx context.Context, arg CancelRunParams) (Run, error)
	// Queue claim.
	//
	// FOR UPDATE SKIP LOCKED, not an advisory lock: the queue is a table we
	// already have to read, the work item is a row, and SKIP LOCKED lets N daemons
	// poll concurrently while each still gets a distinct run. An advisory lock
	// would need a second lookup to decide WHICH key to lock, which reintroduces
	// the race it is supposed to remove. The lock is released by the enclosing
	// transaction, so a worker that dies mid-claim simply loses its claim.
	//
	// The inner SELECT is what SKIP LOCKED applies to; the outer UPDATE then only
	// touches the one row this worker won.
	ClaimQueuedRun(ctx context.Context, arg ClaimQueuedRunParams) (Run, error)
	// Redemption. The UPDATE is the claim: `consumed_at IS NULL` in the predicate
	// plus the row lock the UPDATE takes means two daemons racing on the same code
	// produce exactly one winner, with no read-then-write window in between.
	ConsumePairingCode(ctx context.Context, arg ConsumePairingCodeParams) (PairingCode, error)
	// Guard for "demote/remove the last owner": an org with no owner cannot be
	// administered again.
	CountOwners(ctx context.Context, orgID uuid.UUID) (int64, error)
	CountProjects(ctx context.Context, arg CountProjectsParams) (int64, error)
	CountRunEvents(ctx context.Context, arg CountRunEventsParams) (int64, error)
	CountRuns(ctx context.Context, arg CountRunsParams) (int64, error)
	CountTestCases(ctx context.Context, arg CountTestCasesParams) (int64, error)
	CreateExecution(ctx context.Context, arg CreateExecutionParams) (Execution, error)
	// Seeds a run's whole work list in one statement from the cases it selected,
	// pinning each to the version that is current right now.
	CreateExecutionsForRun(ctx context.Context, arg CreateExecutionsForRunParams) ([]Execution, error)
	// Organization invites. Tenancy layer, like sessions and runtime_tokens: the
	// accept path is how an org_id is established for the invitee, so it looks the
	// row up by token hash and cannot take an org_id parameter.
	CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error)
	// Tenancy root. `organizations`, `users`, `memberships` and `sessions` are the
	// tenancy layer itself, so they are outside the org_id-parameter rule that
	// TestQueriesAreOrgScoped enforces on domain tables: these queries are how an
	// org_id is established in the first place.
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	// One-time daemon pairing codes. Tenancy layer, like runtime_tokens.
	CreatePairingCode(ctx context.Context, arg CreatePairingCodeParams) (PairingCode, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	// Runs, and the Postgres-backed job queue they double as.
	CreateRun(ctx context.Context, arg CreateRunParams) (Run, error)
	// The org comes from the redeemed pairing code, never from the daemon's
	// request body. `host_info` is what the machine says about itself at pairing
	// time; the authoritative capability report arrives later in the `hello` frame.
	CreateRuntime(ctx context.Context, arg CreateRuntimeParams) (Runtime, error)
	// Daemon credentials. Tenancy layer, like sessions: the token lookup is how an
	// org_id is established for a daemon connection, so it cannot take one.
	CreateRuntimeToken(ctx context.Context, arg CreateRuntimeTokenParams) (RuntimeToken, error)
	// Tenancy layer: see the note in organizations.sql. Sessions are keyed by the
	// SHA-256 of the cookie value, never by the cookie value itself.
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// Test cases. Every payload write here is snapshotted into test_case_versions
	// by a database trigger, so no query below has to remember to do it.
	CreateTestCase(ctx context.Context, arg CreateTestCaseParams) (TestCase, error)
	// Tenancy layer: see the note in organizations.sql.
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteArtifact(ctx context.Context, arg DeleteArtifactParams) (int64, error)
	DeleteElement(ctx context.Context, arg DeleteElementParams) (int64, error)
	// Housekeeping: an expired invite can never be accepted again.
	DeleteExpiredInvites(ctx context.Context, grace pgtype.Interval) (int64, error)
	DeleteExpiredPairingCodes(ctx context.Context) (int64, error)
	// Housekeeping: expired rows are useless and this table only grows.
	DeleteExpiredSessions(ctx context.Context, grace pgtype.Interval) (int64, error)
	DeleteFinding(ctx context.Context, arg DeleteFindingParams) (int64, error)
	DeleteMembership(ctx context.Context, arg DeleteMembershipParams) (int64, error)
	DeleteOrganization(ctx context.Context, id uuid.UUID) (int64, error)
	DeletePage(ctx context.Context, arg DeletePageParams) (int64, error)
	DeleteProject(ctx context.Context, arg DeleteProjectParams) (int64, error)
	DeleteRuntime(ctx context.Context, arg DeleteRuntimeParams) (int64, error)
	DeleteTestCase(ctx context.Context, arg DeleteTestCaseParams) (int64, error)
	DeleteUser(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteWorkflow(ctx context.Context, arg DeleteWorkflowParams) (int64, error)
	// Runs that exhausted their attempts are dead-lettered rather than retried
	// forever.
	// org-scope-exempt: platform maintenance sweeper, not reachable from a
	// tenant-facing handler; it never returns row contents, only ids to log.
	FailStaleRuns(ctx context.Context, arg FailStaleRunsParams) ([]FailStaleRunsRow, error)
	// Terminal write, guarded on the current result so a redelivered result frame
	// is a no-op rather than a rewrite.
	FinishExecution(ctx context.Context, arg FinishExecutionParams) (Execution, error)
	// Terminal transition. Guarded on the current status so a late duplicate
	// result frame from a reconnecting daemon cannot re-open or overwrite a run
	// that already finished.
	FinishRun(ctx context.Context, arg FinishRunParams) (Run, error)
	GetArtifact(ctx context.Context, arg GetArtifactParams) (Artifact, error)
	GetElement(ctx context.Context, arg GetElementParams) (Element, error)
	GetExecution(ctx context.Context, arg GetExecutionParams) (Execution, error)
	GetExecutionByRunAndCase(ctx context.Context, arg GetExecutionByRunAndCaseParams) (Execution, error)
	GetFinding(ctx context.Context, arg GetFindingParams) (Finding, error)
	GetLastRunEventSeq(ctx context.Context, arg GetLastRunEventSeqParams) (int64, error)
	// The acceptance read. Expiry, revocation and prior acceptance are filtered
	// here rather than in Go so no caller can forget one of the three.
	GetLiveInviteByTokenHash(ctx context.Context, tokenHash []byte) (Invite, error)
	// Redemption needs the org before it can create the runtime the code will be
	// consumed against, so it reads the live row first. Expiry and prior
	// consumption are filtered here; ConsumePairingCode is still the atomic claim.
	GetLivePairingCodeByHash(ctx context.Context, codeHash []byte) (PairingCode, error)
	// The daemon authentication read. Whatever runtime id the daemon claims in its
	// frames is ignored; the (org_id, runtime_id) pair on this row is the truth.
	GetLiveRuntimeTokenByHash(ctx context.Context, tokenHash []byte) (RuntimeToken, error)
	// The per-request session read. Expiry and revocation are filtered here rather
	// than in Go so that a handler cannot forget the check.
	GetLiveSessionByTokenHash(ctx context.Context, tokenHash []byte) (GetLiveSessionByTokenHashRow, error)
	// The authorization read on the request path: it answers "is this user a
	// member of this org, and as what?" in a single primary-key hit.
	GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error)
	GetOrganization(ctx context.Context, id uuid.UUID) (Organization, error)
	GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error)
	GetPage(ctx context.Context, arg GetPageParams) (Page, error)
	GetPageByRef(ctx context.Context, arg GetPageByRefParams) (Page, error)
	GetPairingCodeByHash(ctx context.Context, codeHash []byte) (PairingCode, error)
	GetProject(ctx context.Context, arg GetProjectParams) (Project, error)
	// Retry path for CreateProject: on a unique violation the service reads the
	// existing row back instead of surfacing a 409 for a duplicate submit.
	GetProjectByName(ctx context.Context, arg GetProjectByNameParams) (Project, error)
	GetRun(ctx context.Context, arg GetRunParams) (Run, error)
	// Retry path for CreateRun: a client that replays POST /runs with the same
	// Idempotency-Key gets its original run back instead of a second browser
	// session against the customer's application.
	GetRunByIdempotencyKey(ctx context.Context, arg GetRunByIdempotencyKeyParams) (Run, error)
	// Read-modify-write on a single run (status transitions, counter fixups) must
	// go through this so two writers cannot interleave.
	GetRunForUpdate(ctx context.Context, arg GetRunForUpdateParams) (Run, error)
	GetRuntime(ctx context.Context, arg GetRuntimeParams) (Runtime, error)
	GetTestCase(ctx context.Context, arg GetTestCaseParams) (TestCase, error)
	GetTestCaseByRef(ctx context.Context, arg GetTestCaseByRefParams) (TestCase, error)
	GetTestCaseVersion(ctx context.Context, arg GetTestCaseVersionParams) (TestCaseVersion, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	// The login lookup. citext makes this case-insensitive without a lower() cast
	// that one code path could forget.
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetWorkflow(ctx context.Context, arg GetWorkflowParams) (Workflow, error)
	HeartbeatRun(ctx context.Context, arg HeartbeatRunParams) (int64, error)
	LinkFindingEvidence(ctx context.Context, arg LinkFindingEvidenceParams) (int64, error)
	// The regression suite: what an `execute` run without an explicit selection
	// runs. One query, ordered so the report reads by priority.
	ListApprovedTestCases(ctx context.Context, arg ListApprovedTestCasesParams) ([]TestCase, error)
	ListArtifactsForExecution(ctx context.Context, arg ListArtifactsForExecutionParams) ([]Artifact, error)
	ListArtifactsForRun(ctx context.Context, arg ListArtifactsForRunParams) ([]Artifact, error)
	ListElementsForPage(ctx context.Context, arg ListElementsForPageParams) ([]Element, error)
	// Every element of a project in one query. Assembling the Application Map is
	// then: pages + this + workflows = three statements, whatever the map's size.
	// Fetching elements per page would be the N+1 this replaces.
	ListElementsForProject(ctx context.Context, arg ListElementsForProjectParams) ([]Element, error)
	ListExecutionAssertions(ctx context.Context, arg ListExecutionAssertionsParams) ([]ExecutionAssertion, error)
	// Every assertion of a run in one query. The analyst needs the failing
	// assertion's expected/actual pair to classify a failure at all, and fetching
	// them per execution would be the N+1 this replaces.
	ListExecutionAssertionsForRun(ctx context.Context, arg ListExecutionAssertionsForRunParams) ([]ExecutionAssertion, error)
	ListExecutionSteps(ctx context.Context, arg ListExecutionStepsParams) ([]ExecutionStep, error)
	// Every step of a run in one query, for the report view.
	ListExecutionStepsForRun(ctx context.Context, arg ListExecutionStepsForRunParams) ([]ExecutionStep, error)
	// The report read: executions plus the case they ran, in one join. Fetching
	// the test case per execution would be the N+1 this replaces.
	ListExecutionsForRun(ctx context.Context, arg ListExecutionsForRunParams) ([]ListExecutionsForRunRow, error)
	// Findings with their evidence for a whole run in one query. Fetching evidence
	// per finding would be the N+1 the join table exists to avoid.
	ListFindingEvidenceForRun(ctx context.Context, arg ListFindingEvidenceForRunParams) ([]ListFindingEvidenceForRunRow, error)
	ListFindingsForRun(ctx context.Context, arg ListFindingsForRunParams) ([]Finding, error)
	ListInvites(ctx context.Context, orgID uuid.UUID) ([]Invite, error)
	// The org's outstanding codes, so the UI can show "a pairing code is waiting"
	// without ever being able to show the code itself.
	ListLivePairingCodes(ctx context.Context, orgID uuid.UUID) ([]PairingCode, error)
	ListMembers(ctx context.Context, orgID uuid.UUID) ([]ListMembersRow, error)
	// Org picker for a signed-in user; the role comes along so the UI can hide
	// what the member cannot do.
	ListOrganizationsForUser(ctx context.Context, userID uuid.UUID) ([]ListOrganizationsForUserRow, error)
	ListPages(ctx context.Context, arg ListPagesParams) ([]Page, error)
	ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error)
	// Phase 6 input: how one case has behaved over its recent runs.
	ListRecentExecutionsForTestCase(ctx context.Context, arg ListRecentExecutionsForTestCaseParams) ([]Execution, error)
	// Backs `GET /runs/{id}/events?since={seq}`; served entirely by the
	// (run_id, seq) unique index.
	ListRunEventsSince(ctx context.Context, arg ListRunEventsSinceParams) ([]RunEvent, error)
	ListRuns(ctx context.Context, arg ListRunsParams) ([]Run, error)
	ListRuntimeTokens(ctx context.Context, arg ListRuntimeTokensParams) ([]ListRuntimeTokensRow, error)
	// `online` is derived from last_seen_at rather than stored: a daemon that is
	// SIGKILLed never gets to write a status column on its way out.
	ListRuntimes(ctx context.Context, arg ListRuntimesParams) ([]ListRuntimesRow, error)
	// Stale-map filter: pages not observed by the given discovery run. Callers
	// report these rather than deleting them, because live test cases may still
	// reference them.
	ListStalePages(ctx context.Context, arg ListStalePagesParams) ([]Page, error)
	ListTestCaseVersions(ctx context.Context, arg ListTestCaseVersionsParams) ([]TestCaseVersion, error)
	ListTestCases(ctx context.Context, arg ListTestCasesParams) ([]TestCase, error)
	ListWorkflows(ctx context.Context, arg ListWorkflowsParams) ([]Workflow, error)
	MarkExecutionRunning(ctx context.Context, arg MarkExecutionRunningParams) (Execution, error)
	MarkRunRunning(ctx context.Context, arg MarkRunRunningParams) (Run, error)
	// Written from the daemon `hello` frame. The org is taken from the runtime
	// token, never from the frame, so it is a parameter here and not a value the
	// daemon supplies.
	RecordRuntimeHello(ctx context.Context, arg RecordRuntimeHelloParams) (Runtime, error)
	// Recomputes the counters from the executions that actually exist, so a
	// dropped or duplicated result frame cannot leave the summary lying.
	RefreshRunCounters(ctx context.Context, arg RefreshRunCountersParams) (Run, error)
	// Requeue sweep for runs whose daemon stopped heart-beating. Runs across every
	// organization by design.
	// org-scope-exempt: platform maintenance sweeper, not reachable from a
	// tenant-facing handler; it never returns row contents, only ids to log.
	RequeueStaleRuns(ctx context.Context, arg RequeueStaleRunsParams) ([]RequeueStaleRunsRow, error)
	RevokeInvite(ctx context.Context, arg RevokeInviteParams) (int64, error)
	// Re-inviting somebody rotates the token instead of leaving two valid ones
	// outstanding. Run inside the same transaction as CreateInvite, otherwise the
	// partial unique index rejects the new row.
	RevokeLiveInvitesForEmail(ctx context.Context, arg RevokeLiveInvitesForEmailParams) (int64, error)
	RevokeRuntimeToken(ctx context.Context, arg RevokeRuntimeTokenParams) (int64, error)
	RevokeRuntimeTokensForRuntime(ctx context.Context, arg RevokeRuntimeTokensForRuntimeParams) (int64, error)
	RevokeSession(ctx context.Context, tokenHash []byte) (int64, error)
	// "Log out everywhere", also used after a password change.
	RevokeUserSessions(ctx context.Context, userID uuid.UUID) (int64, error)
	SetRunPhase(ctx context.Context, arg SetRunPhaseParams) (int64, error)
	SetRuntimeDisabled(ctx context.Context, arg SetRuntimeDisabledParams) (Runtime, error)
	SetTestCaseStatus(ctx context.Context, arg SetTestCaseStatusParams) (TestCase, error)
	// Failure-class breakdown for a project's recent runs.
	SummarizeFindingsByClass(ctx context.Context, arg SummarizeFindingsByClassParams) ([]SummarizeFindingsByClassRow, error)
	TouchRuntime(ctx context.Context, arg TouchRuntimeParams) (int64, error)
	TouchRuntimeToken(ctx context.Context, id uuid.UUID) (int64, error)
	TouchSession(ctx context.Context, id uuid.UUID) (int64, error)
	UnlinkFindingEvidence(ctx context.Context, arg UnlinkFindingEvidenceParams) (int64, error)
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	// Editing the payload bumps current_version and writes a version row, both by
	// trigger. `status` is deliberately not editable here: PATCH status is a
	// separate authorization decision (approve/archive).
	UpdateTestCasePayload(ctx context.Context, arg UpdateTestCasePayloadParams) (TestCase, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (int64, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	// Artifact metadata. The bytes go straight from the daemon to object storage
	// with a presigned PUT; the storage_key layout is enforced by a CHECK on the
	// table, so a key pointing outside this row's own org/run is rejected here.
	// Re-registering the same object after a daemon reconnect updates the row
	// rather than failing: the upload itself is idempotent on the same key.
	UpsertArtifact(ctx context.Context, arg UpsertArtifactParams) (Artifact, error)
	UpsertElement(ctx context.Context, arg UpsertElementParams) (Element, error)
	// Bulk form for the discovery ingest; see the note on UpsertPageBatch.
	UpsertElementBatch(ctx context.Context, arg []UpsertElementBatchParams) *UpsertElementBatchBatchResults
	UpsertExecutionAssertion(ctx context.Context, arg UpsertExecutionAssertionParams) (ExecutionAssertion, error)
	UpsertExecutionStep(ctx context.Context, arg UpsertExecutionStepParams) (ExecutionStep, error)
	// What the failure analyst concluded, and the evidence it cited.
	// One finding per execution; re-analysis updates in place so regenerating a
	// report does not stack duplicates.
	UpsertFinding(ctx context.Context, arg UpsertFindingParams) (Finding, error)
	// Tenancy layer: see the note in organizations.sql. This is the table the auth
	// middleware checks the X-Org-ID header against on every request.
	UpsertMembership(ctx context.Context, arg UpsertMembershipParams) (Membership, error)
	UpsertPage(ctx context.Context, arg UpsertPageParams) (Page, error)
	// Bulk form for the discovery ingest, issued as a single pgx batch: one
	// network round trip for the whole map instead of one per page. Fetching or
	// writing the map page by page is the N+1 this replaces.
	UpsertPageBatch(ctx context.Context, arg []UpsertPageBatchParams) *UpsertPageBatchBatchResults
	// Planner ingest: a re-run of the planner must not duplicate cases, and must
	// not silently overwrite a case a human already approved.
	UpsertPlannedTestCase(ctx context.Context, arg UpsertPlannedTestCaseParams) (TestCase, error)
	UpsertWorkflow(ctx context.Context, arg UpsertWorkflowParams) (Workflow, error)
}

var _ Querier = (*Queries)(nil)
