// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: run_events.sql

package dbgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendRunEvent = `-- name: AppendRunEvent :execrows

INSERT INTO run_events (org_id, run_id, seq, phase, level, code, message, data, ts)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (run_id, seq) DO NOTHING
`

type AppendRunEventParams struct {
	OrgID   uuid.UUID
	RunID   uuid.UUID
	Seq     int64
	Phase   string
	Level   RunEventLevel
	Code    string
	Message string
	Data    json.RawMessage
	Ts      pgtype.Timestamptz
}

// The run event stream. Delivery from the daemon is at-least-once, so every
// write here is idempotent on (run_id, seq).
// Returns 1 when the event was new and 0 when it was a redelivery, which is
// what the WebSocket fan-out uses to decide whether to broadcast.
func (q *Queries) AppendRunEvent(ctx context.Context, arg AppendRunEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, appendRunEvent,
		arg.OrgID,
		arg.RunID,
		arg.Seq,
		arg.Phase,
		arg.Level,
		arg.Code,
		arg.Message,
		arg.Data,
		arg.Ts,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countRunEvents = `-- name: CountRunEvents :one
SELECT count(*) FROM run_events WHERE org_id = $1 AND run_id = $2
`

type CountRunEventsParams struct {
	OrgID uuid.UUID
	RunID uuid.UUID
}

func (q *Queries) CountRunEvents(ctx context.Context, arg CountRunEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRunEvents, arg.OrgID, arg.RunID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getLastRunEventSeq = `-- name: GetLastRunEventSeq :one
SELECT coalesce(max(seq), -1)::bigint
FROM run_events
WHERE org_id = $1 AND run_id = $2
`

type GetLastRunEventSeqParams struct {
	OrgID uuid.UUID
	RunID uuid.UUID
}

func (q *Queries) GetLastRunEventSeq(ctx context.Context, arg GetLastRunEventSeqParams) (int64, error) {
	row := q.db.QueryRow(ctx, getLastRunEventSeq, arg.OrgID, arg.RunID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listRunEventsSince = `-- name: ListRunEventsSince :many
SELECT id, org_id, run_id, seq, phase, level, code, message, data, ts, created_at FROM run_events
WHERE org_id = $1 AND run_id = $2 AND seq > $3
ORDER BY seq
LIMIT $4
`

type ListRunEventsSinceParams struct {
	OrgID uuid.UUID
	RunID uuid.UUID
	Seq   int64
	Limit int32
}

// Backs `GET /runs/{id}/events?since={seq}`; served entirely by the
// (run_id, seq) unique index.
func (q *Queries) ListRunEventsSince(ctx context.Context, arg ListRunEventsSinceParams) ([]RunEvent, error) {
	rows, err := q.db.Query(ctx, listRunEventsSince,
		arg.OrgID,
		arg.RunID,
		arg.Seq,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunEvent{}
	for rows.Next() {
		var i RunEvent
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.RunID,
			&i.Seq,
			&i.Phase,
			&i.Level,
			&i.Code,
			&i.Message,
			&i.Data,
			&i.Ts,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
