// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runs.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelRun = `-- name: CancelRun :one
UPDATE runs
SET status = 'cancelled', finished_at = now()
WHERE org_id = $1 AND id = $2 AND status IN ('queued', 'assigned', 'running')
RETURNING id, org_id, project_id, runtime_id, mode, status, phase, idempotency_key, attempts, heartbeat_at, total_count, passed_count, failed_count, skipped_count, error_count, error_code, error_message, created_by, assigned_at, started_at, finished_at, created_at, updated_at
`

type CancelRunParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) CancelRun(ctx context.Context, arg CancelRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, cancelRun, arg.OrgID, arg.ID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.RuntimeID,
		&i.Mode,
		&i.Status,
		&i.Phase,
		&i.IdempotencyKey,
		&i.Attempts,
		&i.HeartbeatAt,
		&i.TotalCount,
		&i.PassedCount,
		&i.FailedCount,
		&i.SkippedCount,
		&i.ErrorCount,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedBy,
		&i.AssignedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimQueuedRun = `-- name: ClaimQueuedRun :one
UPDATE runs AS c
SET status = 'assigned',
    attempts = c.attempts + 1,
    assigned_at = now(),
    heartbeat_at = now()
WHERE c.org_id = $1
  AND c.id = (
    SELECT r.id
    FROM runs r
    WHERE r.org_id = $1
      AND r.runtime_id = $2
      AND r.status = 'queued'
    ORDER BY r.created_at
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING c.id, c.org_id, c.project_id, c.runtime_id, c.mode, c.status, c.phase, c.idempotency_key, c.attempts, c.heartbeat_at, c.total_count, c.passed_count, c.failed_count, c.skipped_count, c.error_count, c.error_code, c.error_message, c.created_by, c.assigned_at, c.started_at, c.finished_at, c.created_at, c.updated_at
`

type ClaimQueuedRunParams struct {
	OrgID     uuid.UUID
	RuntimeID uuid.NullUUID
}

// Queue claim.
//
// FOR UPDATE SKIP LOCKED, not an advisory lock: the queue is a table we
// already have to read, the work item is a row, and SKIP LOCKED lets N daemons
// poll concurrently while each still gets a distinct run. An advisory lock
// would need a second lookup to decide WHICH key to lock, which reintroduces
// the race it is supposed to remove. The lock is released by the enclosing
// transaction, so a worker that dies mid-claim simply loses its claim.
//
// The inner SELECT is what SKIP LOCKED applies to; the outer UPDATE then only
// touches the one row this worker won.
func (q *Queries) ClaimQueuedRun(ctx context.Context, arg ClaimQueuedRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, claimQueuedRun, arg.OrgID, arg.RuntimeID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.RuntimeID,
		&i.Mode,
		&i.Status,
		&i.Phase,
		&i.IdempotencyKey,
		&i.Attempts,
		&i.HeartbeatAt,
		&i.TotalCount,
		&i.PassedCount,
		&i.FailedCount,
		&i.SkippedCount,
		&i.ErrorCount,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedBy,
		&i.AssignedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimQueuedRunForRuntime = `-- name: ClaimQueuedRunForRuntime :one
UPDATE runs AS c
SET status = 'assigned',
    runtime_id = $1,
    attempts = c.attempts + 1,
    assigned_at = now(),
    heartbeat_at = now()
WHERE c.org_id = $2
  -- One run at a time per runtime: a daemon drives one browser session, and a
  -- second assignment would have it interleave two runs against the customer's
  -- application. The guard is inside the claim statement rather than a check
  -- the scheduler makes first, so two schedulers cannot both read "idle" and
  -- both assign.
  AND NOT EXISTS (
    SELECT 1 FROM runs busy
    WHERE busy.org_id = $2
      AND busy.runtime_id = $1
      AND busy.status IN ('assigned', 'running')
  )
  AND c.id = (
    SELECT r.id
    FROM runs r
    WHERE r.org_id = $2
      AND (r.runtime_id IS NULL OR r.runtime_id = $1)
      AND r.status = 'queued'
    ORDER BY r.created_at
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING c.id, c.org_id, c.project_id, c.runtime_id, c.mode, c.status, c.phase, c.idempotency_key, c.attempts, c.heartbeat_at, c.total_count, c.passed_count, c.failed_count, c.skipped_count, c.error_count, c.error_code, c.error_message, c.created_by, c.assigned_at, c.started_at, c.finished_at, c.created_at, c.updated_at
`

type ClaimQueuedRunForRuntimeParams struct {
	RuntimeID uuid.NullUUID
	OrgID     uuid.UUID
}

// The scheduler's claim. ClaimQueuedRun above pins to a runtime that was named
// at enqueue time; this one is what an idle daemon asks for, so it also picks
// up runs that were created without a runtime (`runtime_id IS NULL`) and
// stamps itself onto the row it wins.
//
// Same FOR UPDATE SKIP LOCKED as ClaimQueuedRun and for the same reason: the
// work item is a row we already have to read, and SKIP LOCKED lets every
// connected daemon poll concurrently while each still gets a distinct run. An
// advisory lock would need a prior lookup to decide WHICH key to lock, which
// reintroduces the race it is meant to remove.
func (q *Queries) ClaimQueuedRunForRuntime(ctx context.Context, arg ClaimQueuedRunForRuntimeParams) (Run, error) {
	row := q.db.QueryRow(ctx, claimQueuedRunForRuntime, arg.RuntimeID, arg.OrgID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.RuntimeID,
		&i.Mode,
		&i.Status,
		&i.Phase,
		&i.IdempotencyKey,
		&i.Attempts,
		&i.HeartbeatAt,
		&i.TotalCount,
		&i.PassedCount,
		&i.FailedCount,
		&i.SkippedCount,
		&i.ErrorCount,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedBy,
		&i.AssignedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countRuns = `-- name: CountRuns :one
SELECT count(*) FROM runs
WHERE org_id = $1
  AND ($2::uuid IS NULL OR project_id = $2::uuid)
`

type CountRunsParams struct {
	OrgID     uuid.UUID
	ProjectID uuid.NullUUID
}

func (q *Queries) CountRuns(ctx context.Context, arg CountRunsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRuns, arg.OrgID, arg.ProjectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRun = `-- name: CreateRun :one

INSERT INTO runs (org_id, project_id, runtime_id, mode, idempotency_key, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, org_id, project_id, runtime_id, mode, status, phase, idempotency_key, attempts, heartbeat_at, total_count, passed_count, failed_count, skipped_count, error_count, error_code, error_message, created_by, assigned_at, started_at, finished_at, created_at, updated_at
`

type CreateRunParams struct {
	OrgID          uuid.UUID
	ProjectID      uuid.UUID
	RuntimeID      uuid.NullUUID
	Mode           RunMode
	IdempotencyKey pgtype.Text
	CreatedBy      uuid.NullUUID
}

// Runs, and the Postgres-backed job queue they double as.
func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.OrgID,
		arg.ProjectID,
		arg.RuntimeID,
		arg.Mode,
		arg.IdempotencyKey,
		arg.CreatedBy,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.RuntimeID,
		&i.Mode,
		&i.Status,
		&i.Phase,
		&i.IdempotencyKey,
		&i.Attempts,
		&i.HeartbeatAt,
		&i.TotalCount,
		&i.PassedCount,
		&i.FailedCount,
		&i.SkippedCount,
		&i.ErrorCount,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedBy,
		&i.AssignedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failStaleRuns = `-- name: FailStaleRuns :many
UPDATE runs
SET status = 'error',
    finished_at = now(),
    error_code = 'runtime_lost',
    error_message = 'the runtime stopped reporting before the run finished'
WHERE status IN ('assigned', 'running')
  AND heartbeat_at < now() - $1::interval
  AND attempts >= $2::integer
RETURNING id, org_id
`

type FailStaleRunsParams struct {
	StaleAfter  pgtype.Interval
	MaxAttempts int32
}

type FailStaleRunsRow struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

// Runs that exhausted their attempts are dead-lettered rather than retried
// forever.
// org-scope-exempt: platform maintenance sweeper, not reachable from a
// tenant-facing handler; it never returns row contents, only ids to log.
func (q *Queries) FailStaleRuns(ctx context.Context, arg FailStaleRunsParams) ([]FailStaleRunsRow, error) {
	rows, err := q.db.Query(ctx, failStaleRuns, arg.StaleAfter, arg.MaxAttempts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FailStaleRunsRow{}
	for rows.Next() {
		var i FailStaleRunsRow
		if err := rows.Scan(&i.ID, &i.OrgID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishRun = `-- name: FinishRun :one
UPDATE runs
SET status = $1,
    finished_at = now(),
    error_code = $2,
    error_message = $3
WHERE org_id = $4
  AND id = $5
  AND status IN ('queued', 'assigned', 'running')
RETURNING id, org_id, project_id, runtime_id, mode, status, phase, idempotency_key, attempts, heartbeat_at, total_count, passed_count, failed_count, skipped_count, error_count, error_code, error_message, created_by, assigned_at, started_at, finished_at, created_at, updated_at
`

type FinishRunParams struct {
	Status       RunStatus
	ErrorCode    string
	ErrorMessage string
	OrgID        uuid.UUID
	ID           uuid.UUID
}

// Terminal transition. Guarded on the current status so a late duplicate
// result frame from a reconnecting daemon cannot re-open or overwrite a run
// that already finished.
func (q *Queries) FinishRun(ctx context.Context, arg FinishRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, finishRun,
		arg.Status,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.OrgID,
		arg.ID,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.RuntimeID,
		&i.Mode,
		&i.Status,
		&i.Phase,
		&i.IdempotencyKey,
		&i.Attempts,
		&i.HeartbeatAt,
		&i.TotalCount,
		&i.PassedCount,
		&i.FailedCount,
		&i.SkippedCount,
		&i.ErrorCount,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedBy,
		&i.AssignedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, org_id, project_id, runtime_id, mode, status, phase, idempotency_key, attempts, heartbeat_at, total_count, passed_count, failed_count, skipped_count, error_count, error_code, error_message, created_by, assigned_at, started_at, finished_at, created_at, updated_at FROM runs WHERE org_id = $1 AND id = $2
`

type GetRunParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) GetRun(ctx context.Context, arg GetRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, getRun, arg.OrgID, arg.ID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.RuntimeID,
		&i.Mode,
		&i.Status,
		&i.Phase,
		&i.IdempotencyKey,
		&i.Attempts,
		&i.HeartbeatAt,
		&i.TotalCount,
		&i.PassedCount,
		&i.FailedCount,
		&i.SkippedCount,
		&i.ErrorCount,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedBy,
		&i.AssignedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRunByIdempotencyKey = `-- name: GetRunByIdempotencyKey :one
SELECT id, org_id, project_id, runtime_id, mode, status, phase, idempotency_key, attempts, heartbeat_at, total_count, passed_count, failed_count, skipped_count, error_count, error_code, error_message, created_by, assigned_at, started_at, finished_at, created_at, updated_at FROM runs WHERE org_id = $1 AND idempotency_key = $2
`

type GetRunByIdempotencyKeyParams struct {
	OrgID          uuid.UUID
	IdempotencyKey pgtype.Text
}

// Retry path for CreateRun: a client that replays POST /runs with the same
// Idempotency-Key gets its original run back instead of a second browser
// session against the customer's application.
func (q *Queries) GetRunByIdempotencyKey(ctx context.Context, arg GetRunByIdempotencyKeyParams) (Run, error) {
	row := q.db.QueryRow(ctx, getRunByIdempotencyKey, arg.OrgID, arg.IdempotencyKey)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.RuntimeID,
		&i.Mode,
		&i.Status,
		&i.Phase,
		&i.IdempotencyKey,
		&i.Attempts,
		&i.HeartbeatAt,
		&i.TotalCount,
		&i.PassedCount,
		&i.FailedCount,
		&i.SkippedCount,
		&i.ErrorCount,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedBy,
		&i.AssignedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRunForRuntime = `-- name: GetRunForRuntime :one
SELECT id, org_id, project_id, runtime_id, mode, status, phase, idempotency_key, attempts, heartbeat_at, total_count, passed_count, failed_count, skipped_count, error_count, error_code, error_message, created_by, assigned_at, started_at, finished_at, created_at, updated_at FROM runs
WHERE org_id = $1 AND id = $2 AND runtime_id = $3
`

type GetRunForRuntimeParams struct {
	OrgID     uuid.UUID
	ID        uuid.UUID
	RuntimeID uuid.NullUUID
}

// Belongs-to check for the daemon control plane: a `run.event` frame is only
// accepted for a run in the token's own organization that is assigned to the
// token's own runtime. Both halves are in the WHERE clause, so a frame that
// names another tenant's run reads as "no such run" rather than as a
// permission decision made in Go.
func (q *Queries) GetRunForRuntime(ctx context.Context, arg GetRunForRuntimeParams) (Run, error) {
	row := q.db.QueryRow(ctx, getRunForRuntime, arg.OrgID, arg.ID, arg.RuntimeID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.RuntimeID,
		&i.Mode,
		&i.Status,
		&i.Phase,
		&i.IdempotencyKey,
		&i.Attempts,
		&i.HeartbeatAt,
		&i.TotalCount,
		&i.PassedCount,
		&i.FailedCount,
		&i.SkippedCount,
		&i.ErrorCount,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedBy,
		&i.AssignedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRunForUpdate = `-- name: GetRunForUpdate :one
SELECT id, org_id, project_id, runtime_id, mode, status, phase, idempotency_key, attempts, heartbeat_at, total_count, passed_count, failed_count, skipped_count, error_count, error_code, error_message, created_by, assigned_at, started_at, finished_at, created_at, updated_at FROM runs WHERE org_id = $1 AND id = $2 FOR UPDATE
`

type GetRunForUpdateParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

// Read-modify-write on a single run (status transitions, counter fixups) must
// go through this so two writers cannot interleave.
func (q *Queries) GetRunForUpdate(ctx context.Context, arg GetRunForUpdateParams) (Run, error) {
	row := q.db.QueryRow(ctx, getRunForUpdate, arg.OrgID, arg.ID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.RuntimeID,
		&i.Mode,
		&i.Status,
		&i.Phase,
		&i.IdempotencyKey,
		&i.Attempts,
		&i.HeartbeatAt,
		&i.TotalCount,
		&i.PassedCount,
		&i.FailedCount,
		&i.SkippedCount,
		&i.ErrorCount,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedBy,
		&i.AssignedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const heartbeatRun = `-- name: HeartbeatRun :execrows
UPDATE runs SET heartbeat_at = now()
WHERE org_id = $1 AND id = $2 AND status IN ('assigned', 'running')
`

type HeartbeatRunParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) HeartbeatRun(ctx context.Context, arg HeartbeatRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, heartbeatRun, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const heartbeatRunsForRuntime = `-- name: HeartbeatRunsForRuntime :execrows
UPDATE runs
SET heartbeat_at = now()
WHERE org_id = $1
  AND runtime_id = $2
  AND id = ANY ($3::uuid[])
  AND status IN ('assigned', 'running')
`

type HeartbeatRunsForRuntimeParams struct {
	OrgID     uuid.UUID
	RuntimeID uuid.NullUUID
	Ids       []uuid.UUID
}

// Lease refresh for everything a daemon says it is still working on, in one
// statement. The runtime is bound as a parameter, so a heartbeat can only
// extend the lease on runs that daemon actually holds — a frame listing another
// runtime's run in the same organization updates nothing.
func (q *Queries) HeartbeatRunsForRuntime(ctx context.Context, arg HeartbeatRunsForRuntimeParams) (int64, error) {
	result, err := q.db.Exec(ctx, heartbeatRunsForRuntime, arg.OrgID, arg.RuntimeID, arg.Ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listInFlightRunsForRuntime = `-- name: ListInFlightRunsForRuntime :many
SELECT id, org_id, project_id, runtime_id, mode, status, phase, idempotency_key, attempts, heartbeat_at, total_count, passed_count, failed_count, skipped_count, error_count, error_code, error_message, created_by, assigned_at, started_at, finished_at, created_at, updated_at FROM runs
WHERE org_id = $1 AND runtime_id = $2 AND status IN ('assigned', 'running')
ORDER BY created_at
`

type ListInFlightRunsForRuntimeParams struct {
	OrgID     uuid.UUID
	RuntimeID uuid.NullUUID
}

// Runs a daemon is still expected to be working on. Used when a control-plane
// connection drops so the runs it held can be dealt with immediately rather
// than waiting out the heartbeat lease.
func (q *Queries) ListInFlightRunsForRuntime(ctx context.Context, arg ListInFlightRunsForRuntimeParams) ([]Run, error) {
	rows, err := q.db.Query(ctx, listInFlightRunsForRuntime, arg.OrgID, arg.RuntimeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.RuntimeID,
			&i.Mode,
			&i.Status,
			&i.Phase,
			&i.IdempotencyKey,
			&i.Attempts,
			&i.HeartbeatAt,
			&i.TotalCount,
			&i.PassedCount,
			&i.FailedCount,
			&i.SkippedCount,
			&i.ErrorCount,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedBy,
			&i.AssignedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuns = `-- name: ListRuns :many
SELECT id, org_id, project_id, runtime_id, mode, status, phase, idempotency_key, attempts, heartbeat_at, total_count, passed_count, failed_count, skipped_count, error_count, error_code, error_message, created_by, assigned_at, started_at, finished_at, created_at, updated_at FROM runs
WHERE org_id = $1
  AND ($4::uuid IS NULL OR project_id = $4::uuid)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListRunsParams struct {
	OrgID     uuid.UUID
	Limit     int32
	Offset    int32
	ProjectID uuid.NullUUID
}

func (q *Queries) ListRuns(ctx context.Context, arg ListRunsParams) ([]Run, error) {
	rows, err := q.db.Query(ctx, listRuns,
		arg.OrgID,
		arg.Limit,
		arg.Offset,
		arg.ProjectID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.RuntimeID,
			&i.Mode,
			&i.Status,
			&i.Phase,
			&i.IdempotencyKey,
			&i.Attempts,
			&i.HeartbeatAt,
			&i.TotalCount,
			&i.PassedCount,
			&i.FailedCount,
			&i.SkippedCount,
			&i.ErrorCount,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedBy,
			&i.AssignedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRunRunning = `-- name: MarkRunRunning :one
UPDATE runs
SET status = 'running', started_at = coalesce(started_at, now()), heartbeat_at = now(),
    phase = $3
WHERE org_id = $1 AND id = $2 AND status IN ('assigned', 'running')
RETURNING id, org_id, project_id, runtime_id, mode, status, phase, idempotency_key, attempts, heartbeat_at, total_count, passed_count, failed_count, skipped_count, error_count, error_code, error_message, created_by, assigned_at, started_at, finished_at, created_at, updated_at
`

type MarkRunRunningParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
	Phase string
}

func (q *Queries) MarkRunRunning(ctx context.Context, arg MarkRunRunningParams) (Run, error) {
	row := q.db.QueryRow(ctx, markRunRunning, arg.OrgID, arg.ID, arg.Phase)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.RuntimeID,
		&i.Mode,
		&i.Status,
		&i.Phase,
		&i.IdempotencyKey,
		&i.Attempts,
		&i.HeartbeatAt,
		&i.TotalCount,
		&i.PassedCount,
		&i.FailedCount,
		&i.SkippedCount,
		&i.ErrorCount,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedBy,
		&i.AssignedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const refreshRunCounters = `-- name: RefreshRunCounters :one
UPDATE runs r
SET total_count   = c.total,
    passed_count  = c.passed,
    failed_count  = c.failed,
    skipped_count = c.skipped,
    error_count   = c.errored
FROM (
    SELECT count(*)                                        AS total,
           count(*) FILTER (WHERE e.result = 'pass')        AS passed,
           count(*) FILTER (WHERE e.result = 'fail')        AS failed,
           count(*) FILTER (WHERE e.result = 'skipped')     AS skipped,
           count(*) FILTER (WHERE e.result = 'error')       AS errored
    FROM executions e
    WHERE e.org_id = $1 AND e.run_id = $2
) c
WHERE r.org_id = $1 AND r.id = $2
RETURNING r.id, r.org_id, r.project_id, r.runtime_id, r.mode, r.status, r.phase, r.idempotency_key, r.attempts, r.heartbeat_at, r.total_count, r.passed_count, r.failed_count, r.skipped_count, r.error_count, r.error_code, r.error_message, r.created_by, r.assigned_at, r.started_at, r.finished_at, r.created_at, r.updated_at
`

type RefreshRunCountersParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

// Recomputes the counters from the executions that actually exist, so a
// dropped or duplicated result frame cannot leave the summary lying.
func (q *Queries) RefreshRunCounters(ctx context.Context, arg RefreshRunCountersParams) (Run, error) {
	row := q.db.QueryRow(ctx, refreshRunCounters, arg.OrgID, arg.ID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.RuntimeID,
		&i.Mode,
		&i.Status,
		&i.Phase,
		&i.IdempotencyKey,
		&i.Attempts,
		&i.HeartbeatAt,
		&i.TotalCount,
		&i.PassedCount,
		&i.FailedCount,
		&i.SkippedCount,
		&i.ErrorCount,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedBy,
		&i.AssignedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const releaseClaimedRun = `-- name: ReleaseClaimedRun :execrows
UPDATE runs
SET status = 'queued', assigned_at = NULL, heartbeat_at = NULL
WHERE org_id = $1 AND id = $2 AND status = 'assigned'
`

type ReleaseClaimedRunParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

// Undo of a claim whose `run.assign` never made it onto the wire (the daemon
// disconnected between the claim and the send). Returning the run to the queue
// immediately is what keeps assignment latency at one scheduler tick instead of
// one lease expiry. `attempts` is deliberately NOT decremented: a runtime that
// keeps dropping mid-assign must still exhaust its attempts.
func (q *Queries) ReleaseClaimedRun(ctx context.Context, arg ReleaseClaimedRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseClaimedRun, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const requeueStaleRuns = `-- name: RequeueStaleRuns :many
UPDATE runs
SET status = 'queued', assigned_at = NULL, heartbeat_at = NULL
WHERE status IN ('assigned', 'running')
  AND heartbeat_at < now() - $1::interval
  AND attempts < $2::integer
RETURNING id, org_id
`

type RequeueStaleRunsParams struct {
	StaleAfter  pgtype.Interval
	MaxAttempts int32
}

type RequeueStaleRunsRow struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

// Requeue sweep for runs whose daemon stopped heart-beating. Runs across every
// organization by design.
// org-scope-exempt: platform maintenance sweeper, not reachable from a
// tenant-facing handler; it never returns row contents, only ids to log.
func (q *Queries) RequeueStaleRuns(ctx context.Context, arg RequeueStaleRunsParams) ([]RequeueStaleRunsRow, error) {
	rows, err := q.db.Query(ctx, requeueStaleRuns, arg.StaleAfter, arg.MaxAttempts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RequeueStaleRunsRow{}
	for rows.Next() {
		var i RequeueStaleRunsRow
		if err := rows.Scan(&i.ID, &i.OrgID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRunPhase = `-- name: SetRunPhase :execrows
UPDATE runs SET phase = $3, heartbeat_at = now()
WHERE org_id = $1 AND id = $2 AND status IN ('assigned', 'running')
`

type SetRunPhaseParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
	Phase string
}

func (q *Queries) SetRunPhase(ctx context.Context, arg SetRunPhaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, setRunPhase, arg.OrgID, arg.ID, arg.Phase)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
