// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runtimes.sql

package dbgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRuntime = `-- name: CreateRuntime :one
INSERT INTO runtimes (org_id, name, version, host_info)
VALUES ($1, $2, $3, COALESCE($4::jsonb, '{}'::jsonb))
RETURNING id, org_id, name, version, browsers, agents, last_seen_at, disabled_at, created_at, updated_at, host_info
`

type CreateRuntimeParams struct {
	OrgID    uuid.UUID
	Name     string
	Version  string
	HostInfo []byte
}

// The org comes from the redeemed pairing code, never from the daemon's
// request body. `host_info` is what the machine says about itself at pairing
// time; the authoritative capability report arrives later in the `hello` frame.
func (q *Queries) CreateRuntime(ctx context.Context, arg CreateRuntimeParams) (Runtime, error) {
	row := q.db.QueryRow(ctx, createRuntime,
		arg.OrgID,
		arg.Name,
		arg.Version,
		arg.HostInfo,
	)
	var i Runtime
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Version,
		&i.Browsers,
		&i.Agents,
		&i.LastSeenAt,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HostInfo,
	)
	return i, err
}

const deleteRuntime = `-- name: DeleteRuntime :execrows
DELETE FROM runtimes WHERE org_id = $1 AND id = $2
`

type DeleteRuntimeParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) DeleteRuntime(ctx context.Context, arg DeleteRuntimeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRuntime, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRuntime = `-- name: GetRuntime :one
SELECT id, org_id, name, version, browsers, agents, last_seen_at, disabled_at, created_at, updated_at, host_info FROM runtimes WHERE org_id = $1 AND id = $2
`

type GetRuntimeParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) GetRuntime(ctx context.Context, arg GetRuntimeParams) (Runtime, error) {
	row := q.db.QueryRow(ctx, getRuntime, arg.OrgID, arg.ID)
	var i Runtime
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Version,
		&i.Browsers,
		&i.Agents,
		&i.LastSeenAt,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HostInfo,
	)
	return i, err
}

const listRuntimes = `-- name: ListRuntimes :many
SELECT id, org_id, name, version, browsers, agents, last_seen_at, disabled_at, created_at, updated_at, host_info,
       (disabled_at IS NULL
        AND last_seen_at IS NOT NULL
        AND last_seen_at > now() - $2::interval) AS online
FROM runtimes
WHERE org_id = $1
ORDER BY name
`

type ListRuntimesParams struct {
	OrgID        uuid.UUID
	OnlineWithin pgtype.Interval
}

type ListRuntimesRow struct {
	ID         uuid.UUID
	OrgID      uuid.UUID
	Name       string
	Version    string
	Browsers   json.RawMessage
	Agents     json.RawMessage
	LastSeenAt pgtype.Timestamptz
	DisabledAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	HostInfo   json.RawMessage
	Online     pgtype.Bool
}

// `online` is derived from last_seen_at rather than stored: a daemon that is
// SIGKILLed never gets to write a status column on its way out.
func (q *Queries) ListRuntimes(ctx context.Context, arg ListRuntimesParams) ([]ListRuntimesRow, error) {
	rows, err := q.db.Query(ctx, listRuntimes, arg.OrgID, arg.OnlineWithin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRuntimesRow{}
	for rows.Next() {
		var i ListRuntimesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Version,
			&i.Browsers,
			&i.Agents,
			&i.LastSeenAt,
			&i.DisabledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HostInfo,
			&i.Online,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordRuntimeHello = `-- name: RecordRuntimeHello :one
UPDATE runtimes
SET version = $3,
    browsers = $4,
    agents = $5,
    last_seen_at = now()
WHERE org_id = $1 AND id = $2
RETURNING id, org_id, name, version, browsers, agents, last_seen_at, disabled_at, created_at, updated_at, host_info
`

type RecordRuntimeHelloParams struct {
	OrgID    uuid.UUID
	ID       uuid.UUID
	Version  string
	Browsers json.RawMessage
	Agents   json.RawMessage
}

// Written from the daemon `hello` frame. The org is taken from the runtime
// token, never from the frame, so it is a parameter here and not a value the
// daemon supplies.
func (q *Queries) RecordRuntimeHello(ctx context.Context, arg RecordRuntimeHelloParams) (Runtime, error) {
	row := q.db.QueryRow(ctx, recordRuntimeHello,
		arg.OrgID,
		arg.ID,
		arg.Version,
		arg.Browsers,
		arg.Agents,
	)
	var i Runtime
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Version,
		&i.Browsers,
		&i.Agents,
		&i.LastSeenAt,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HostInfo,
	)
	return i, err
}

const setRuntimeDisabled = `-- name: SetRuntimeDisabled :one
UPDATE runtimes
SET disabled_at = CASE WHEN $3::boolean THEN now() ELSE NULL END
WHERE org_id = $1 AND id = $2
RETURNING id, org_id, name, version, browsers, agents, last_seen_at, disabled_at, created_at, updated_at, host_info
`

type SetRuntimeDisabledParams struct {
	OrgID    uuid.UUID
	ID       uuid.UUID
	Disabled bool
}

func (q *Queries) SetRuntimeDisabled(ctx context.Context, arg SetRuntimeDisabledParams) (Runtime, error) {
	row := q.db.QueryRow(ctx, setRuntimeDisabled, arg.OrgID, arg.ID, arg.Disabled)
	var i Runtime
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Version,
		&i.Browsers,
		&i.Agents,
		&i.LastSeenAt,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HostInfo,
	)
	return i, err
}

const touchRuntime = `-- name: TouchRuntime :execrows
UPDATE runtimes SET last_seen_at = now() WHERE org_id = $1 AND id = $2
`

type TouchRuntimeParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) TouchRuntime(ctx context.Context, arg TouchRuntimeParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchRuntime, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
