// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runtime_tokens.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRuntimeToken = `-- name: CreateRuntimeToken :one

INSERT INTO runtime_tokens (org_id, runtime_id, token_hash)
VALUES ($1, $2, $3)
RETURNING id, org_id, runtime_id, token_hash, created_at, last_used_at, revoked_at
`

type CreateRuntimeTokenParams struct {
	OrgID     uuid.UUID
	RuntimeID uuid.UUID
	TokenHash []byte
}

// Daemon credentials. Tenancy layer, like sessions: the token lookup is how an
// org_id is established for a daemon connection, so it cannot take one.
func (q *Queries) CreateRuntimeToken(ctx context.Context, arg CreateRuntimeTokenParams) (RuntimeToken, error) {
	row := q.db.QueryRow(ctx, createRuntimeToken, arg.OrgID, arg.RuntimeID, arg.TokenHash)
	var i RuntimeToken
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RuntimeID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getLiveRuntimeTokenByHash = `-- name: GetLiveRuntimeTokenByHash :one
SELECT id, org_id, runtime_id, token_hash, created_at, last_used_at, revoked_at FROM runtime_tokens
WHERE token_hash = $1 AND revoked_at IS NULL
`

// The daemon authentication read. Whatever runtime id the daemon claims in its
// frames is ignored; the (org_id, runtime_id) pair on this row is the truth.
func (q *Queries) GetLiveRuntimeTokenByHash(ctx context.Context, tokenHash []byte) (RuntimeToken, error) {
	row := q.db.QueryRow(ctx, getLiveRuntimeTokenByHash, tokenHash)
	var i RuntimeToken
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RuntimeID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listRuntimeTokens = `-- name: ListRuntimeTokens :many
SELECT id, org_id, runtime_id, created_at, last_used_at, revoked_at
FROM runtime_tokens
WHERE org_id = $1 AND runtime_id = $2
ORDER BY created_at DESC
`

type ListRuntimeTokensParams struct {
	OrgID     uuid.UUID
	RuntimeID uuid.UUID
}

type ListRuntimeTokensRow struct {
	ID         uuid.UUID
	OrgID      uuid.UUID
	RuntimeID  uuid.UUID
	CreatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

func (q *Queries) ListRuntimeTokens(ctx context.Context, arg ListRuntimeTokensParams) ([]ListRuntimeTokensRow, error) {
	rows, err := q.db.Query(ctx, listRuntimeTokens, arg.OrgID, arg.RuntimeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRuntimeTokensRow{}
	for rows.Next() {
		var i ListRuntimeTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.RuntimeID,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeRuntimeToken = `-- name: RevokeRuntimeToken :execrows
UPDATE runtime_tokens SET revoked_at = now()
WHERE org_id = $1 AND id = $2 AND revoked_at IS NULL
`

type RevokeRuntimeTokenParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) RevokeRuntimeToken(ctx context.Context, arg RevokeRuntimeTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRuntimeToken, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeRuntimeTokensForRuntime = `-- name: RevokeRuntimeTokensForRuntime :execrows
UPDATE runtime_tokens SET revoked_at = now()
WHERE org_id = $1 AND runtime_id = $2 AND revoked_at IS NULL
`

type RevokeRuntimeTokensForRuntimeParams struct {
	OrgID     uuid.UUID
	RuntimeID uuid.UUID
}

func (q *Queries) RevokeRuntimeTokensForRuntime(ctx context.Context, arg RevokeRuntimeTokensForRuntimeParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRuntimeTokensForRuntime, arg.OrgID, arg.RuntimeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchRuntimeToken = `-- name: TouchRuntimeToken :execrows
UPDATE runtime_tokens SET last_used_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) TouchRuntimeToken(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, touchRuntimeToken, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
