// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, revoked_at, last_used_at, created_at
`

type CreateSessionParams struct {
	UserID    uuid.UUID
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
}

// Tenancy layer: see the note in organizations.sql. Sessions are keyed by the
// SHA-256 of the cookie value, never by the cookie value itself.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at < now() - $1::interval
`

// Housekeeping: expired rows are useless and this table only grows.
func (q *Queries) DeleteExpiredSessions(ctx context.Context, grace pgtype.Interval) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions, grace)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLiveSessionByTokenHash = `-- name: GetLiveSessionByTokenHash :one
SELECT s.id, s.user_id, s.token_hash, s.expires_at, s.revoked_at, s.last_used_at, s.created_at, u.id, u.email, u.password_hash, u.name, u.created_at, u.updated_at
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1
  AND s.revoked_at IS NULL
  AND s.expires_at > now()
`

type GetLiveSessionByTokenHashRow struct {
	Session Session
	User    User
}

// The per-request session read. Expiry and revocation are filtered here rather
// than in Go so that a handler cannot forget the check.
func (q *Queries) GetLiveSessionByTokenHash(ctx context.Context, tokenHash []byte) (GetLiveSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getLiveSessionByTokenHash, tokenHash)
	var i GetLiveSessionByTokenHashRow
	err := row.Scan(
		&i.Session.ID,
		&i.Session.UserID,
		&i.Session.TokenHash,
		&i.Session.ExpiresAt,
		&i.Session.RevokedAt,
		&i.Session.LastUsedAt,
		&i.Session.CreatedAt,
		&i.User.ID,
		&i.User.Email,
		&i.User.PasswordHash,
		&i.User.Name,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE sessions SET revoked_at = now() WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, tokenHash []byte) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSession, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeUserSessions = `-- name: RevokeUserSessions :execrows
UPDATE sessions SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
`

// "Log out everywhere", also used after a password change.
func (q *Queries) RevokeUserSessions(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeUserSessions, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchSession = `-- name: TouchSession :execrows
UPDATE sessions SET last_used_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) TouchSession(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, touchSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
