// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: test_cases.sql

package dbgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countApprovedTestCasesByCategory = `-- name: CountApprovedTestCasesByCategory :many
SELECT category, count(*) AS total FROM test_cases
WHERE org_id = $1 AND project_id = $2 AND status = 'approved'
GROUP BY category
`

type CountApprovedTestCasesByCategoryParams struct {
	OrgID     uuid.UUID
	ProjectID uuid.UUID
}

type CountApprovedTestCasesByCategoryRow struct {
	Category TestCategory
	Total    int64
}

// How many approved cases a project has in each category, for the coverage
// report. Counted in the database rather than by loading the suite: the
// coverage endpoint already reads every approved payload for its ref sets, and
// this is the one number it needs that does not come from them.
func (q *Queries) CountApprovedTestCasesByCategory(ctx context.Context, arg CountApprovedTestCasesByCategoryParams) ([]CountApprovedTestCasesByCategoryRow, error) {
	rows, err := q.db.Query(ctx, countApprovedTestCasesByCategory, arg.OrgID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountApprovedTestCasesByCategoryRow{}
	for rows.Next() {
		var i CountApprovedTestCasesByCategoryRow
		if err := rows.Scan(&i.Category, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countTestCases = `-- name: CountTestCases :one
SELECT count(*) FROM test_cases
WHERE org_id = $1
  AND project_id = $2
  AND ($3::test_case_status IS NULL
       OR status = $3::test_case_status)
`

type CountTestCasesParams struct {
	OrgID     uuid.UUID
	ProjectID uuid.UUID
	Status    NullTestCaseStatus
}

func (q *Queries) CountTestCases(ctx context.Context, arg CountTestCasesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTestCases, arg.OrgID, arg.ProjectID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTestCase = `-- name: CreateTestCase :one

INSERT INTO test_cases (org_id, project_id, ref, name, priority, category, status,
                        payload, source_run_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, org_id, project_id, ref, name, priority, category, status, payload, current_version, source_run_id, created_at, updated_at
`

type CreateTestCaseParams struct {
	OrgID       uuid.UUID
	ProjectID   uuid.UUID
	Ref         string
	Name        string
	Priority    TestPriority
	Category    TestCategory
	Status      TestCaseStatus
	Payload     json.RawMessage
	SourceRunID uuid.NullUUID
}

// Test cases. Every payload write here is snapshotted into test_case_versions
// by a database trigger, so no query below has to remember to do it.
func (q *Queries) CreateTestCase(ctx context.Context, arg CreateTestCaseParams) (TestCase, error) {
	row := q.db.QueryRow(ctx, createTestCase,
		arg.OrgID,
		arg.ProjectID,
		arg.Ref,
		arg.Name,
		arg.Priority,
		arg.Category,
		arg.Status,
		arg.Payload,
		arg.SourceRunID,
	)
	var i TestCase
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Ref,
		&i.Name,
		&i.Priority,
		&i.Category,
		&i.Status,
		&i.Payload,
		&i.CurrentVersion,
		&i.SourceRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTestCase = `-- name: DeleteTestCase :execrows
DELETE FROM test_cases WHERE org_id = $1 AND id = $2
`

type DeleteTestCaseParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) DeleteTestCase(ctx context.Context, arg DeleteTestCaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTestCase, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTestCase = `-- name: GetTestCase :one
SELECT id, org_id, project_id, ref, name, priority, category, status, payload, current_version, source_run_id, created_at, updated_at FROM test_cases WHERE org_id = $1 AND id = $2
`

type GetTestCaseParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) GetTestCase(ctx context.Context, arg GetTestCaseParams) (TestCase, error) {
	row := q.db.QueryRow(ctx, getTestCase, arg.OrgID, arg.ID)
	var i TestCase
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Ref,
		&i.Name,
		&i.Priority,
		&i.Category,
		&i.Status,
		&i.Payload,
		&i.CurrentVersion,
		&i.SourceRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTestCaseByRef = `-- name: GetTestCaseByRef :one
SELECT id, org_id, project_id, ref, name, priority, category, status, payload, current_version, source_run_id, created_at, updated_at FROM test_cases WHERE org_id = $1 AND project_id = $2 AND ref = $3
`

type GetTestCaseByRefParams struct {
	OrgID     uuid.UUID
	ProjectID uuid.UUID
	Ref       string
}

func (q *Queries) GetTestCaseByRef(ctx context.Context, arg GetTestCaseByRefParams) (TestCase, error) {
	row := q.db.QueryRow(ctx, getTestCaseByRef, arg.OrgID, arg.ProjectID, arg.Ref)
	var i TestCase
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Ref,
		&i.Name,
		&i.Priority,
		&i.Category,
		&i.Status,
		&i.Payload,
		&i.CurrentVersion,
		&i.SourceRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTestCaseVersion = `-- name: GetTestCaseVersion :one
SELECT id, org_id, test_case_id, version, payload, status, created_at FROM test_case_versions
WHERE org_id = $1 AND test_case_id = $2 AND version = $3
`

type GetTestCaseVersionParams struct {
	OrgID      uuid.UUID
	TestCaseID uuid.UUID
	Version    int32
}

func (q *Queries) GetTestCaseVersion(ctx context.Context, arg GetTestCaseVersionParams) (TestCaseVersion, error) {
	row := q.db.QueryRow(ctx, getTestCaseVersion, arg.OrgID, arg.TestCaseID, arg.Version)
	var i TestCaseVersion
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TestCaseID,
		&i.Version,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listApprovedTestCasePayloads = `-- name: ListApprovedTestCasePayloads :many
SELECT id, ref, payload FROM test_cases
WHERE org_id = $1 AND project_id = $2 AND status = 'approved'
ORDER BY ref
`

type ListApprovedTestCasePayloadsParams struct {
	OrgID     uuid.UUID
	ProjectID uuid.UUID
}

type ListApprovedTestCasePayloadsRow struct {
	ID      uuid.UUID
	Ref     string
	Payload json.RawMessage
}

// The coverage read: what the project actually runs as regression. Approved
// only, because a draft nobody has read is not a test this project runs.
func (q *Queries) ListApprovedTestCasePayloads(ctx context.Context, arg ListApprovedTestCasePayloadsParams) ([]ListApprovedTestCasePayloadsRow, error) {
	rows, err := q.db.Query(ctx, listApprovedTestCasePayloads, arg.OrgID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApprovedTestCasePayloadsRow{}
	for rows.Next() {
		var i ListApprovedTestCasePayloadsRow
		if err := rows.Scan(&i.ID, &i.Ref, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApprovedTestCases = `-- name: ListApprovedTestCases :many
SELECT id, org_id, project_id, ref, name, priority, category, status, payload, current_version, source_run_id, created_at, updated_at FROM test_cases
WHERE org_id = $1 AND project_id = $2 AND status = 'approved'
ORDER BY priority, ref
`

type ListApprovedTestCasesParams struct {
	OrgID     uuid.UUID
	ProjectID uuid.UUID
}

// The regression suite: what an `execute` run without an explicit selection
// runs. One query, ordered so the report reads by priority.
func (q *Queries) ListApprovedTestCases(ctx context.Context, arg ListApprovedTestCasesParams) ([]TestCase, error) {
	rows, err := q.db.Query(ctx, listApprovedTestCases, arg.OrgID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestCase{}
	for rows.Next() {
		var i TestCase
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.Ref,
			&i.Name,
			&i.Priority,
			&i.Category,
			&i.Status,
			&i.Payload,
			&i.CurrentVersion,
			&i.SourceRunID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestCasePayloads = `-- name: ListTestCasePayloads :many
SELECT id, ref, status, payload FROM test_cases
WHERE org_id = $1 AND project_id = $2
ORDER BY ref
`

type ListTestCasePayloadsParams struct {
	OrgID     uuid.UUID
	ProjectID uuid.UUID
}

type ListTestCasePayloadsRow struct {
	ID      uuid.UUID
	Ref     string
	Status  TestCaseStatus
	Payload json.RawMessage
}

// The dedupe read for the planner ingest: every existing case's ref, status
// and payload, so a freshly planned case whose normalised steps match one of
// them can be dropped instead of stored as a second row for the same test.
//
// Every status, not just approved. An approved match must not be re-queued for
// review, an archived one must not come back after somebody retired it, and a
// draft one must not be stored twice under two ids — which is what a re-plan
// produces, because a planner renumbers its cases every run.
//
// Payloads rather than a stored fingerprint column on purpose: the
// normalisation is contract-aware Go (see internal/testcase/plan.go), and a
// fingerprint written by an older version of that function would silently stop
// matching one written by a newer one, with no backfill path and no way to
// notice. Normalising both sides at read time cannot drift.
func (q *Queries) ListTestCasePayloads(ctx context.Context, arg ListTestCasePayloadsParams) ([]ListTestCasePayloadsRow, error) {
	rows, err := q.db.Query(ctx, listTestCasePayloads, arg.OrgID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTestCasePayloadsRow{}
	for rows.Next() {
		var i ListTestCasePayloadsRow
		if err := rows.Scan(
			&i.ID,
			&i.Ref,
			&i.Status,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestCaseVersions = `-- name: ListTestCaseVersions :many
SELECT id, org_id, test_case_id, version, payload, status, created_at FROM test_case_versions
WHERE org_id = $1 AND test_case_id = $2
ORDER BY version DESC
LIMIT $3
`

type ListTestCaseVersionsParams struct {
	OrgID      uuid.UUID
	TestCaseID uuid.UUID
	Limit      int32
}

func (q *Queries) ListTestCaseVersions(ctx context.Context, arg ListTestCaseVersionsParams) ([]TestCaseVersion, error) {
	rows, err := q.db.Query(ctx, listTestCaseVersions, arg.OrgID, arg.TestCaseID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestCaseVersion{}
	for rows.Next() {
		var i TestCaseVersion
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.TestCaseID,
			&i.Version,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestCases = `-- name: ListTestCases :many
SELECT id, org_id, project_id, ref, name, priority, category, status, payload, current_version, source_run_id, created_at, updated_at FROM test_cases
WHERE org_id = $1
  AND project_id = $2
  AND ($5::test_case_status IS NULL
       OR status = $5::test_case_status)
ORDER BY priority, ref
LIMIT $3 OFFSET $4
`

type ListTestCasesParams struct {
	OrgID     uuid.UUID
	ProjectID uuid.UUID
	Limit     int32
	Offset    int32
	Status    NullTestCaseStatus
}

func (q *Queries) ListTestCases(ctx context.Context, arg ListTestCasesParams) ([]TestCase, error) {
	rows, err := q.db.Query(ctx, listTestCases,
		arg.OrgID,
		arg.ProjectID,
		arg.Limit,
		arg.Offset,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestCase{}
	for rows.Next() {
		var i TestCase
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.Ref,
			&i.Name,
			&i.Priority,
			&i.Category,
			&i.Status,
			&i.Payload,
			&i.CurrentVersion,
			&i.SourceRunID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestCasesByIDs = `-- name: ListTestCasesByIDs :many
SELECT id, org_id, project_id, ref, name, priority, category, status, payload, current_version, source_run_id, created_at, updated_at FROM test_cases
WHERE org_id = $1
  AND project_id = $2
  AND id = ANY ($3::uuid[])
ORDER BY priority, ref
`

type ListTestCasesByIDsParams struct {
	OrgID     uuid.UUID
	ProjectID uuid.UUID
	Ids       []uuid.UUID
}

// Resolves an explicit test-case selection in one statement.
//
// Both the organization and the project are bound, so a selection that names a
// case from another project (or another tenant) simply returns fewer rows than
// were asked for, and the caller reports that as "not found" without ever
// learning which id was the bad one.
func (q *Queries) ListTestCasesByIDs(ctx context.Context, arg ListTestCasesByIDsParams) ([]TestCase, error) {
	rows, err := q.db.Query(ctx, listTestCasesByIDs, arg.OrgID, arg.ProjectID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestCase{}
	for rows.Next() {
		var i TestCase
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.Ref,
			&i.Name,
			&i.Priority,
			&i.Category,
			&i.Status,
			&i.Payload,
			&i.CurrentVersion,
			&i.SourceRunID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestCasesByRefs = `-- name: ListTestCasesByRefs :many
SELECT id, org_id, project_id, ref, name, priority, category, status, payload, current_version, source_run_id, created_at, updated_at FROM test_cases
WHERE org_id = $1
  AND project_id = $2
  AND ref = ANY ($3::text[])
`

type ListTestCasesByRefsParams struct {
	OrgID     uuid.UUID
	ProjectID uuid.UUID
	Refs      []string
}

// Resolves the case refs a result frame names, in one statement.
//
// A run.result carries up to 500 executions and as many findings, each naming
// its case by ref ("TC-001"); looking them up one at a time is the N+1 this
// replaces, and it would run inside the ingest transaction.
func (q *Queries) ListTestCasesByRefs(ctx context.Context, arg ListTestCasesByRefsParams) ([]TestCase, error) {
	rows, err := q.db.Query(ctx, listTestCasesByRefs, arg.OrgID, arg.ProjectID, arg.Refs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestCase{}
	for rows.Next() {
		var i TestCase
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.Ref,
			&i.Name,
			&i.Priority,
			&i.Category,
			&i.Status,
			&i.Payload,
			&i.CurrentVersion,
			&i.SourceRunID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTestCaseStatus = `-- name: SetTestCaseStatus :one
UPDATE test_cases SET status = $3
WHERE org_id = $1 AND id = $2
RETURNING id, org_id, project_id, ref, name, priority, category, status, payload, current_version, source_run_id, created_at, updated_at
`

type SetTestCaseStatusParams struct {
	OrgID  uuid.UUID
	ID     uuid.UUID
	Status TestCaseStatus
}

func (q *Queries) SetTestCaseStatus(ctx context.Context, arg SetTestCaseStatusParams) (TestCase, error) {
	row := q.db.QueryRow(ctx, setTestCaseStatus, arg.OrgID, arg.ID, arg.Status)
	var i TestCase
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Ref,
		&i.Name,
		&i.Priority,
		&i.Category,
		&i.Status,
		&i.Payload,
		&i.CurrentVersion,
		&i.SourceRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTestCasePayload = `-- name: UpdateTestCasePayload :one
UPDATE test_cases
SET name = coalesce($1, name),
    priority = coalesce($2, priority),
    category = coalesce($3, category),
    payload = $4
WHERE org_id = $5 AND id = $6
RETURNING id, org_id, project_id, ref, name, priority, category, status, payload, current_version, source_run_id, created_at, updated_at
`

type UpdateTestCasePayloadParams struct {
	Name     pgtype.Text
	Priority NullTestPriority
	Category NullTestCategory
	Payload  json.RawMessage
	OrgID    uuid.UUID
	ID       uuid.UUID
}

// Editing the payload bumps current_version and writes a version row, both by
// trigger. `status` is deliberately not editable here: PATCH status is a
// separate authorization decision (approve/archive).
func (q *Queries) UpdateTestCasePayload(ctx context.Context, arg UpdateTestCasePayloadParams) (TestCase, error) {
	row := q.db.QueryRow(ctx, updateTestCasePayload,
		arg.Name,
		arg.Priority,
		arg.Category,
		arg.Payload,
		arg.OrgID,
		arg.ID,
	)
	var i TestCase
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Ref,
		&i.Name,
		&i.Priority,
		&i.Category,
		&i.Status,
		&i.Payload,
		&i.CurrentVersion,
		&i.SourceRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPlannedTestCase = `-- name: UpsertPlannedTestCase :one
INSERT INTO test_cases (org_id, project_id, ref, name, priority, category, payload, source_run_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (project_id, ref) DO UPDATE
SET name = EXCLUDED.name,
    priority = EXCLUDED.priority,
    category = EXCLUDED.category,
    payload = EXCLUDED.payload,
    source_run_id = EXCLUDED.source_run_id
WHERE test_cases.status = 'draft'
RETURNING id, org_id, project_id, ref, name, priority, category, status, payload, current_version, source_run_id, created_at, updated_at
`

type UpsertPlannedTestCaseParams struct {
	OrgID       uuid.UUID
	ProjectID   uuid.UUID
	Ref         string
	Name        string
	Priority    TestPriority
	Category    TestCategory
	Payload     json.RawMessage
	SourceRunID uuid.NullUUID
}

// Planner ingest: a re-run of the planner must not duplicate cases, and must
// not silently overwrite a case a human already approved.
func (q *Queries) UpsertPlannedTestCase(ctx context.Context, arg UpsertPlannedTestCaseParams) (TestCase, error) {
	row := q.db.QueryRow(ctx, upsertPlannedTestCase,
		arg.OrgID,
		arg.ProjectID,
		arg.Ref,
		arg.Name,
		arg.Priority,
		arg.Category,
		arg.Payload,
		arg.SourceRunID,
	)
	var i TestCase
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Ref,
		&i.Name,
		&i.Priority,
		&i.Category,
		&i.Status,
		&i.Payload,
		&i.CurrentVersion,
		&i.SourceRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
