// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflows.sql

package dbgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const deleteWorkflow = `-- name: DeleteWorkflow :execrows
DELETE FROM workflows WHERE org_id = $1 AND id = $2
`

type DeleteWorkflowParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) DeleteWorkflow(ctx context.Context, arg DeleteWorkflowParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWorkflow, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWorkflow = `-- name: GetWorkflow :one
SELECT id, org_id, project_id, ref, name, path, expected_outcome, last_seen_run_id, created_at, updated_at FROM workflows WHERE org_id = $1 AND id = $2
`

type GetWorkflowParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) GetWorkflow(ctx context.Context, arg GetWorkflowParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, getWorkflow, arg.OrgID, arg.ID)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Ref,
		&i.Name,
		&i.Path,
		&i.ExpectedOutcome,
		&i.LastSeenRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkflows = `-- name: ListWorkflows :many
SELECT id, org_id, project_id, ref, name, path, expected_outcome, last_seen_run_id, created_at, updated_at FROM workflows
WHERE org_id = $1 AND project_id = $2
ORDER BY name
`

type ListWorkflowsParams struct {
	OrgID     uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) ListWorkflows(ctx context.Context, arg ListWorkflowsParams) ([]Workflow, error) {
	rows, err := q.db.Query(ctx, listWorkflows, arg.OrgID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workflow{}
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.Ref,
			&i.Name,
			&i.Path,
			&i.ExpectedOutcome,
			&i.LastSeenRunID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertWorkflow = `-- name: UpsertWorkflow :one
INSERT INTO workflows (org_id, project_id, ref, name, path, expected_outcome, last_seen_run_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (project_id, ref) DO UPDATE
SET name = EXCLUDED.name,
    path = EXCLUDED.path,
    expected_outcome = EXCLUDED.expected_outcome,
    last_seen_run_id = coalesce(EXCLUDED.last_seen_run_id, workflows.last_seen_run_id)
RETURNING id, org_id, project_id, ref, name, path, expected_outcome, last_seen_run_id, created_at, updated_at
`

type UpsertWorkflowParams struct {
	OrgID           uuid.UUID
	ProjectID       uuid.UUID
	Ref             string
	Name            string
	Path            json.RawMessage
	ExpectedOutcome string
	RunID           uuid.NullUUID
}

func (q *Queries) UpsertWorkflow(ctx context.Context, arg UpsertWorkflowParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, upsertWorkflow,
		arg.OrgID,
		arg.ProjectID,
		arg.Ref,
		arg.Name,
		arg.Path,
		arg.ExpectedOutcome,
		arg.RunID,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Ref,
		&i.Name,
		&i.Path,
		&i.ExpectedOutcome,
		&i.LastSeenRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
